### ISSUE TITLE
Arithmetic operation resulted in overflow.

### ISSUE THREAD

**Issue by Esidar** [icsharpcode/SharpZipLib#108]
In "Inflater.cs" line 431:
`if ((int) adler.Value != readAdler) {
`
I'm getting "Arithmetic operation resulted in overflow." in .NET 4.6.1, Debug, x64.

adler.Value is 0x00000000e4bcbb62
readAdler is 0xe4bcbb62

**Comment by McNeight** [comment]
As I was cleaning up the build files, I turned on overflow/underflow checking for the library. It seems that the CRC functions depend on being able to overflow, so performing any function will throw this exception.

I'll turn off the overflow/underflow checking, and look at how to exempt specific functions when I turn it back on again.

-Neil

**Comment by jfreilly** [comment]
Have a look at the unchecked keyword

**Comment by piksel** [comment]
This doesn't seem like it is relevant anymore, at least not as a bug. Closing it.
