### ISSUE TITLE
[QUESTION] Patent license required?

### ISSUE THREAD

**Issue by sgustafsson** [icsharpcode/SharpZipLib#111]
The zip file format specification file located at https://github.com/icsharpcode/SharpZipLib/blob/master/Documentation/specification/appnote.txt says in section 1.4.3 "Certain technological components provided in this document are the patented proprietary technology of PKWARE and as such require a separate, executed license agreement from PKWARE". Section 10.1 says: "10.1 The Use or Implementation in a product of APPNOTE technological components pertaining to either strong encryption or patching requires a separate, executed license agreement from PKWARE".
As SharpZipLib does provide a ZIP implementation, are there any patent licenses required in order to use SharpZipLib? Is strong encryption or patching supported and implemented in SharpZipLib?

**Comment by jfreilly** [comment]
Nothing in SharpZip requires licensing.  This includes the mentioned patching and strong encryption.
