### ISSUE TITLE
Can I choose a different filename / location other than its filepath

### ISSUE THREAD

**Issue by ChangePlaces** [icsharpcode/SharpZipLib#112]
### Steps to reproduce
1. Create a zip file with `ZipFile.Create`
2. `Begin` and `Add(aFilename)` which may be `baseFolder/anotherFolder/filename.txt`
### Expected behavior

Is it possible to instead choose the path within the zip file? So that, `baseFolder/anotherFolder/filename.txt` could instead, for example, become `readme.txt`?
### Actual behavior

See that directory structure automatically created in the zipfile which may be undesirable.
### Version of SharpZipLib

Using NuGet version 0.86.0.518

**Comment by Numpsy** [comment]
Does the 

```
public void Add(string fileName, string entryName)
```

override @
https://github.com/icsharpcode/SharpZipLib/blob/fed3bd219f8bd2bac5287b6217b9c4c384bed35f/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L1726

Handle this case now?

**Comment by ChangePlaces** [comment]
Well done chaps! Only 4 years and one pandemic later ;)
