### ISSUE TITLE
StreamUtils.Copy Progress

### ISSUE THREAD

**Issue by iamrunar** [icsharpcode/SharpZipLib#113]
```
static public void StreamUtils.Copy(Stream source, Stream destination,
            byte[] buffer,
            ProgressHandler progressHandler, TimeSpan updateInterval,
            object sender, string name, long fixedTarget)
```

endless copying process

**Comment by McNeight** [comment]
How are you using this function?

**Comment by Numpsy** [comment]
This seems too light on context - does that mean that it copies endlessly, or there's an issue with the progress reporting?

**Comment by piksel** [comment]
I have no idea. Four years of "awaiting feedback" is enough to consider this closed though 🙂

**Comment by Zero-Xiong** [comment]
I have faced one issue here.  If I tried to zip the file size over **60Gb**, it will dead, no more progress announced. Seems like never process the copying.


using (var streamToZip = new FileStream(fileToZip, FileMode.Open, FileAccess.Read, FileShare.None, 4096, false))
                                {
                                    var buffer = new byte[4096]; // [blockSize]; <-- revised at 22Sep2020

                                    StreamUtils.Copy(streamToZip, zipStream, buffer, MyProgressHandler, TimeSpan.FromMinutes(15), "ZipFile", zipedFile);
                                    streamToZip.Close();
                                }



public static void MyProgressHandler(object sender, ProgressEventArgs e)
        {
            Logger.Log("The file [" + e.Name + "] PercentComplete [" + e.PercentComplete.ToString("N2") + " %], Total (The number of bytes to process) [" + (e.Target / 1024).ToString("N2") + " ], The number of bytes processed so far [" + (e.Processed/1024).ToString("N2") + " ]");
        }

**Comment by piksel** [comment]
Does it not report any progress at all, or just when reaching 60 GB? There might be something in the implementation that doesn't work correctly with large stream sizes.
Compressing 60 GB of data using managed code seems like it would take an awfully long time though 🤔

**Comment by targor** [comment]
It seems, that the copy method does not provide percentage correctly, but you can calculate it if you provide your zipfile to the progresshandler:

`
ProgressHandler myProgressHandler= new ProgressHandler((object sender, ProgressEventArgs e) =>
{
	ZipEntry entry = (ZipEntry)sender;
        // event that refreshes a progressbar
	PercentExtracted?.Invoke(null, (int)(100.0d / ((double)entry.Size) * ((double)e.Processed))   ); 
});

StreamUtils.Copy(zipStream, streamWriter, buffer,myProgressHandler,new TimeSpan(0,0,0,0,200), zipEntry, zipEntry.Name);
`
