### ISSUE TITLE
Trailing garbage bytes no longer ignored in GZipInputStream

### ISSUE THREAD

**Issue by silijon** [icsharpcode/SharpZipLib#116]
### Steps to reproduce
1.  gzip a file
2.  concatenate some random data to the end of the file (enough to over-run at least one buffer in the inflation stream)
3.  try to decompress with **GZipInputStream**

### Expected behavior
When doing this with gunzip command line tool, a warning about trailing garbage is presented, but since at least one block was processed fully and correctly, it still finishes decompressing the original file without issue.  Verified that this is also handled gracefully in the 0.85.3 version of SharpZipLib (prior to the addition of multiple block handling.)

### Actual behavior
The **GZipInputStream** assumes a second block is pending, so it looks for the header and, not finding it, throws an exception:  Error GZIP header, first magic byte doesn't match.  Interestingly, [this SO post](http://stackoverflow.com/questions/4928560/how-can-i-work-with-gzip-files-which-contain-extra-data) indicates that the Python standard library gzip implementation has (had?) the exact same issue:

(Read top answer for explanation)

### Version of SharpZipLib
Verified with current master branch build

### Obtained from (place an x between the brackets for all that apply)
- [X] Compiled from source
 - branch: master
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by McNeight** [comment]
Resolved by PR #117
