### ISSUE TITLE
Not compatible with Xamarin Studio 6.0 and Mono.Android.6.0 (not installed by nuget)

### ISSUE THREAD

**Issue by edynamic90** [icsharpcode/SharpZipLib#119]
### Steps to reproduce
1. Just Compil in Xamarin Project on Xamarin Studio 6.0 and Mono.Android 6.0
2. Check not installed because not compatible with version 6.0
3. Just read message on install
### Expected behavior

Tell us what should happen
A lot of compatible with Xamarin Studio 6.0
### Actual behavior

Tell us what happens instead
### Version of SharpZipLib

The last stable
### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
  - branch: _______
  - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
  - [x] NuGet
  - [ ] MyGet
  - [ ] Chocolatey

**Comment by Numpsy** [comment]
This might be another one for the 'are these environments relevant any more' set?

**Comment by piksel** [comment]
Yep! Thanks
