### ISSUE TITLE
Why is the current version 0.85 instead of 0.86?

### ISSUE THREAD

**Issue by gabisandor** [icsharpcode/SharpZipLib#122]
The latest released version of sharpziplib is 0.86, but i see that the GitHub releases are at version 0.85. What happened to 0.86? There were some useful APIs in 0.86 such as FastZip.ExtractZip from a stream instead of a file, which are now missing.

**Comment by McNeight** [comment]
@gabisandor the "0.86" release was never an official release from ICSharpCode. The next official release will be version 1.0.

If you could point me to the release you were using, I could check if there is an easy way for me to pull that code in. I'm also willing to accept a pull request with the missing functionality, so long as it is licensed under the new MIT license.

-Neil
