### ISSUE TITLE
FastZip closes not owned stream in method CreateZip

### ISSUE THREAD

**Issue by TalyCraft** [icsharpcode/SharpZipLib#124]
### Steps to reproduce
1. Download and install latest nuget package
2. Initialize new FastZip and new MemoryStrram
3. Call method CreateZip with created MemoryStream as argument
### Expected behavior

MemoryStream instance is filled with data and is in operable state, not disposed
### Actual behavior

MemoryStream instance was disposed after control returned from CreateZip method
### Version of SharpZipLib

SharpZipLib.0.86.0
### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
  - branch: _______
  - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
  - [x ] NuGet
  - [ ] MyGet
  - [ ] Chocolatey

**Comment by gabisandor** [comment]
Is this the NuGet packet you're using: https://www.nuget.org/packages/SharpZipLib/ ? Note that it is way out of date with respect to the GitHub sources.

**Comment by Numpsy** [comment]
Can this be closed as a dup of #78?

**Comment by piksel** [comment]
Yeah!
