### ISSUE TITLE
Compression method not supported - 11gb file

### ISSUE THREAD

**Issue by euginesm** [icsharpcode/SharpZipLib#136]
I am trying to extract the file from 1gb .zip(Actual file size is 11gb). In both .TAR.gz and .zip is getting this error. TarEntry entry = tarInStream.GetNextEntry(); this line getting this error.

FileStream fileStreamIn = new FileStream
                (SrcFile, FileMode.Open, FileAccess.Read);
            TarInputStream tarInStream = new TarInputStream(fileStreamIn);
            
            TarEntry entry = tarInStream.GetNextEntry();
            FileStream fileStreamOut = new FileStream
                (WorkingFile + @"\" + entry.Name, FileMode.Create, FileAccess.Write);
            int size;
            byte[] buffer = new byte[BufferSize];
            do
            {
                size = tarInStream.Read(buffer, 0, buffer.Length);
                fileStreamOut.Write(buffer, 0, size);
            } while (size > 0);
            tarInStream.Close();
            fileStreamOut.Close();
            fileStreamIn.Close();

**Comment by McNeight** [comment]
@euginesm 

You have not submitted enough information to determine if this is a problem with SharpZipLib, or a problem with your code. When you are able to generate more specific information, please open another issue.

-Neil
