### ISSUE TITLE
Is dogfood the current version?

### ISSUE THREAD

**Issue by jruizaranguren** [icsharpcode/SharpZipLib#142]
### Steps to reproduce
1. Search in nuget for SharpZipLib.
### Expected behavior

Find a single official SharpZipLib package.
### Actual behavior

Find version 0.86 (last published in 2011), dogfood version 1.0.89 
### Version of SharpZipLib

That is the question.
Which is the official release? Does it match with any of those nuget packages?
Should I download it from SourceForge, Releases page in Github or nuget?

Thanks.

**Comment by MatthewSteeples** [comment]
It would appear that the dogfood version belongs to @McNeight who seems to be assigned to a lot of the open issues. There's nothing wrong with the version from 2011 (assuming it does what you want it to) and hopefully the libraries will merge back into one at some point

**Comment by McNeight** [comment]
Greetings.

The dogfood builds have been a way for me to test the ability to automatically build and distribute NuGet packages. These packages will disappear once SharpZipLib 1.0 is released, and there is no guarantee that they will be compatible with the final SharpZipLib 1.0.

-Neil

**Comment by christophwille** [comment]
We now have official alpha packages on the main feed.
