### ISSUE TITLE
License for Historical Builds 

### ISSUE THREAD

**Issue by mtpress** [icsharpcode/SharpZipLib#155]
### Steps to reproduce
1. Download version http://icsharpcode.github.io/SharpZipLib/
### Expected behavior
License for version should be MIT
### Actual behavior
License for version is GPL
### Version of SharpZipLib
0.86

I was hoping to look for a clarification on what license the last release build 0.86 is under. I saw that the latest version on GitHub, was converted to MIT and I wanted to see if it applied to the complied version available for download.

**Comment by anthony-tietjen-navex** [comment]
Any news?

**Comment by christophwille** [comment]
We cannot change the license for historical builds as those actually shipped with that license. For SharpDevelop, we usually documeted a date and commit hash from which going forward the license was considered changed. 

@McNeight should we create such a tag in the repo? (date of final approval received)
