### ISSUE TITLE
Different from win10,win7 and 2012 when create tar.gz

### ISSUE THREAD

**Issue by lystormenvoy** [icsharpcode/SharpZipLib#158]
````
private void AddDirectoryFilesToTar(TarArchive tarArchive, string sourceDirectory, bool recurse)
        {

            TarEntry tarEntry = TarEntry.CreateEntryFromFile(sourceDirectory);
            tarArchive.WriteEntry(tarEntry, false);

            string[] filenames = Directory.GetFiles(sourceDirectory);
            foreach (string filename in filenames)
            {
                tarEntry = TarEntry.CreateEntryFromFile(filename);
                tarArchive.WriteEntry(tarEntry, true);
            }

            if (recurse)
            {
                string[] directories = Directory.GetDirectories(sourceDirectory);
                foreach (string directory in directories)
                    AddDirectoryFilesToTar(tarArchive, directory, recurse);
            }
        }

        /// <summary>
        /// 打包成tar
        /// </summary>
        /// <param name="propath">dir to pack</param>
        /// <param name="tarname">tar file fullname</param>
        void Packer(string propath, string tarname)  
        {
            try
            {
                Stream outStream = File.Create(tarname);
                Stream gzoStream = new GZipOutputStream(outStream);
                TarArchive tarArchive = TarArchive.CreateOutputTarArchive(gzoStream);
                tarArchive.RootPath = (propath).Replace('\\', '/');
                if (tarArchive.RootPath.EndsWith("/"))
                    tarArchive.RootPath = tarArchive.RootPath.Remove(tarArchive.RootPath.Length - 1);

                AddDirectoryFilesToTar(tarArchive, propath + "\\webapps", true);

                tarArchive.Close();

            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }
````

my code ↑

ex. propath = d:\app\sample
I want to pack d:\app\sample\webapps into a tar file d:\app\sample.tar.gz

When win10, is correct
sample.tar.gz 
--webapps 
----file1  
----file2  
...

When win7 2012,is
sample.tar.gz
--sample
----webapps
------file1
------file2
...

and when I open it use 7zip, is
sample.tar.gz
--sample.tar
----webapps
------file1
------file2
...

**Comment by dpethes** [comment]
Which version of SharpLibZip did you use?

**Comment by lystormenvoy** [comment]
I use the latest version.
Now I have resolved.
`public bool CreatTarGzArchive(string strBasePath, string TarFileName)
        {
            if (string.IsNullOrEmpty(strBasePath)
                || !System.IO.Directory.Exists(strBasePath))
            {
                return false;
            }

            Environment.CurrentDirectory = strBasePath;

            Stream outTmpStream = new FileStream(TarFileName, FileMode.Create);

            Stream outStream = new GZipOutputStream(outTmpStream);
            TarArchive archive = TarArchive.CreateOutputTarArchive(outStream, TarBuffer.DefaultBlockFactor);
            TarEntry entry = TarEntry.CreateEntryFromFile(strBasePath + "webapps");
            archive.WriteEntry(entry, true);

            if (archive != null)
            {
                archive.Close();
            }


            outTmpStream.Close();
            outStream.Close();
            Environment.CurrentDirectory = "\\";
            return true;
        }`

**Comment by piksel** [comment]
From what I can gather, this was a problem with Directory separators. Closing it since it is resolved.
