### ISSUE TITLE
I think need to update github pages.

### ISSUE THREAD

**Issue by ntjtomohide** [icsharpcode/SharpZipLib#163]
Now, your license policy is confused.

- [github](https://github.com/icsharpcode/SharpZipLib/) -> MIT
- [githubPages](https://icsharpcode.github.io/SharpZipLib/) -> GPL

I'm very confused... so please update githubpage's description.

**Comment by anthony-tietjen-navex** [comment]
Any news?

**Comment by christophwille** [comment]
https://github.com/icsharpcode/SharpZipLib/issues/177
