### ISSUE TITLE
FileInfo-Problem with Daylight saving time

### ISSUE THREAD

**Issue by Raffi84** [icsharpcode/SharpZipLib#17]
I have written an application that uses the ZipEntry class to add files to a zip file.

The file to be zipped, was created in the winter time (December 1, 2012 11:00 AM).
The zip file was created on a Windows Server 2003.

In the zip file, the file has the following date (December 1, 2012 10:00 AM)

It does not matter if I give the correct date via 'Zipentry.Datetime' or not.

When you unzip the file via Winzip the date is also wrong.

The ZipEntry class seems to have a problem with the summer and winter time.

**Comment by piksel** [comment]
The library does not handle daylight savings time implicitly, so that should not be a problem. Further I have not been able to reproduce this. If this is still a problem, please create a new issue using the template.
