### ISSUE TITLE
Why can't I open this with vs2013?

### ISSUE THREAD

**Issue by dimante** [icsharpcode/SharpZipLib#172]
### Steps to reproduce
1. Try to open master in vs 2013

### Expected behavior
Should load.

### Actual behavior
Errors and cannot find project components

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by dpethes** [comment]
Seems that the last merge broke support for older versions, try the version from last year (commit 9ad7f5845222c99ff009a1daddedc051d25a06b9) in the meantime - works with VS2015, maybe older as well.

**Comment by dimante** [comment]
Not sure how to pull an old verison...

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by dpethes** [comment]
This is my fork in the state that worked then: https://github.com/dpethes/SharpZipLib/tree/crc_speedup

**Comment by dimante** [comment]
[image: Inline image 1]

I downloaded the source via the link and the project is still not
compiling.  Thanks for trying though!

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

**Comment by christophwille** [comment]
The current development dependency set is Visual Studio 2017 Version 15.3 with .NET Core SDK 2.0.
