### ISSUE TITLE
I have multiple file zipped using the library and when I try to unzip them i get a "Cannot find central directory" issue.

### ISSUE THREAD

**Issue by anurag1227** [icsharpcode/SharpZipLib#173]
### Steps to reproduce
The Issue that i get is in ZipFile.ReadEntries() where when the code goes looking for EndOfCentralDirectorySignature it does not find it and returns an error.
The error rate is very low so I cannot reproduce it (1 in 100). But just wanted to post it here if anyone here is aware of a similar problems. Because all the files that I have have the "EndOfCentralDirectorySignature" missing. 

### Actual behavior
Exception "Cannot find central directory" is thrown

### Version of SharpZipLib
 0.86.x

**Comment by piksel** [comment]
Could you provide a sample file where the issue occurs?

You did not fill out the Issue template correctly which makes it hard to pinpoint the problem.
Are you saying that the files actually all are missing the EndOfCentralDirectorySignature? If so, why should the library not throw an Exception when reading the file?
