### ISSUE TITLE
Which version is official on NuGet?

### ISSUE THREAD

**Issue by xoofx** [icsharpcode/SharpZipLib#174]
Hi there,

While trying to use a latest netstandard1.3/CoreCLR compatible version of SharpZipLib, I was surprised that it is actually unclear which version on NuGet is official (check the [listing](https://www.nuget.org/packages?q=sharpziplib))

The first one [`SharpZipLib`](https://www.nuget.org/packages/SharpZipLib/) has been released just once more than 6 years ago...

There is a [SharpZipLib-dogfood](https://www.nuget.org/packages/ICSharpCode.SharpZipLib-dogfood/) but the message in VS says `"DogFood" builds for testing purposes. Even *I* wouldn't put this code into production`

- So, which version is recommended? 
- Could we have a nuget link on the project readme? (I can PR it if you have the link to the official version)
- Curious what is the story behind this non-official NuGet package?

Thanks!

**Comment by McNeight** [comment]
@xoofx

Right now, the official released version remains at 0.86. I've been working on making time to get a 1.0 release out, but I doubt that release will be netcore2.0.

I believe that once the 1.0 release is out, we will provide a link to the official NuGet package.

In the mean time, these "dogfood" builds are a daily build out of my fork, automatically uploaded from AppVeyor. It was meant to be more of a test of the whole automated build process as well as the NuGet packaging. While it's not official, it is closer to what is current and pre-built than any other option.

-Neil

**Comment by xoofx** [comment]
No problem, thanks for the precision.
