### ISSUE TITLE
Add support for Original filename field in gzip header

### ISSUE THREAD

**Issue by afonsoft** [icsharpcode/SharpZipLib#175]
### Steps to reproduce
1. Compress file `foo.txt` using gzip to `foo.txt.gz`
2. Rename `foo.txt.gz` to `bar.txt.gz`
3. Decompress file `bar.txt.gz`

### Expected behavior
Output filename should be `foo.txt`

### Actual behavior
Output filename is `bar.txt`

### Obtained from (place an x between the brackets for all that apply)
- Compiled from source
  - branch: Master
  - commit:  be53259
- Downloaded DLL from GitHub

**Comment by afonsoft** [comment]
#175
Change this file ICSharpCode.SharpZipLib.GZip.GZipOutputStream.cs

Create a two property

`/// <summary>
		/// Get the current compression level.
		/// </summary>
		/// <returns>The current compression level.</returns>
		public int GetLevel()
		{
			return deflater_.GetLevel();
		}

		/// <summary>
		/// Set a file name internal gzip
		/// </summary>
		/// <param name="filename">name of file zipped</param>
	    public void SetFileName(string filename)
	    {
	        _fileName = filename;
	    }`

On "Support Routines" modify the method  WriteHeader().

After the code baseOutputStream_.Write(gzipHeader, 0, gzipHeader.Length);

Inlude a code
`if (!string.IsNullOrEmpty(_fileName)) 
			    { 
			        var fileNameBytes = System.Text.Encoding.GetEncoding("ISO-8859-1").GetBytes(_fileName); 
			        Array.Resize<byte>(ref fileNameBytes, fileNameBytes.Length + 1); 
			        fileNameBytes[fileNameBytes.Length - 1] = 0; 
			        baseOutputStream_.Write(fileNameBytes, 0, fileNameBytes.Length); 
			    }`

**Comment by piksel** [comment]
I've updated the question and the proposed solution to what I understand is the issue, please correct me if I misunderstood.

A filename can be added to the gzip header if the flag FNAME is set.
Reference: https://tools.ietf.org/html/rfc1952#section-2.3.1 

This could be made into a PR.
