### ISSUE TITLE
Provide MSBuild 2003 project versions for MonoDevelop/xbuild compatibility

### ISSUE THREAD

**Issue by Protagores** [icsharpcode/SharpZipLib#178]
### Steps to reproduce
1. Install and start [MonoDevelop](http://www.monodevelop.com/)
2. In menu: File → Open
3. In the dialog box: find the solution and open it

Alternatively, use `xbuild` command (if available) in the command line with a project pathname as its argument.

### Expected behavior
All projects should be opened without errors and builds should be possible.

### Actual behavior
* MonoDevelop 6.3 — error: Unknown solution item type.
* MonoDevelop 5.10 — error: Project file doesn't have a valid ProjectGuid.
* xbuild 14.0 — error: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

### Version of SharpZipLib
See commit below.

### Obtained from (place an x between the brackets for all that apply)
- [x] Compiled from source
 - branch: master
 - commit: be53259
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by Protagores** [comment]
As an alternative, [Cake](http://cakebuild.net/) support may be added instead, so that it would be possible to build the library with Mono on non-Windows OS.

**Comment by AlexeiScherbakov** [comment]
Since mono 5 xbuild is deprecated. (http://www.mono-project.com/docs/about-mono/releases/5.0.0/#msbuild)

**Comment by christophwille** [comment]
We are targetting netstandard1.3 now - I'd need to check on my Mac whether we are now compat with Visual Studio for Mac 7.1.

**Comment by Numpsy** [comment]
fwiw, Seems to be buildable on a Mac using both the VS UI and the dotnet command line tools (though i did see an error about libgitsharp when building in VS, which I think is an issue with libgitsharp or sourcelink rather than SharpZipLib)

**Comment by Numpsy** [comment]
given that xbuild doesn't seem to be relevant any more, and the new format project files being useable with Visual Studio / Visual Studio for Mac / VS Code, and the Core SDK from the command line cross platform, is there any need for the old project versions? (would that even work for the .NET Standard build anyway?)

**Comment by christophwille** [comment]
I think the modern SDK-style csprojs should be fine in 2020.

**Comment by piksel** [comment]
Agreed. I use SharpZipLib as much on mac and linux as I do on windows.
