### ISSUE TITLE
256 bit AES Encryption doesn't work

### ISSUE THREAD

**Issue by mattosaurus** [icsharpcode/SharpZipLib#181]
256 bit AES encryption doesn't work, an error message of "System.ArgumentException: 'Specified initialization vector (IV) does not match the block size for this algorithm.'" is generated on line 87 of ZipAESTransform.cs during the creation of the encryptor. 128 bit AES encryption works as expected.

```C#
_encryptor = rm.CreateEncryptor(byteKey1, byteKey2);
```

### Steps to reproduce
Try and encrypt file with 256bit AES encryption

```C#
class Program
{
    static void Main(string[] args)
    {
        ZipFile(@"C:\TEMP\test\test.txt", @"C:\TEMP\test\test.zip", "password");
    }

    public static void ZipFile(string srcPath, string outPath, string password)
    {
        using (ZipOutputStream zipStream = new ZipOutputStream(File.Create(outPath)))
        {
            zipStream.SetLevel(9); // 0-9, 9 being the highest level of compression

            // optional. Null is the same as not setting. Required if using AES.
            zipStream.Password = password; 

            ZipEntry zipEntry = new ZipEntry(Path.GetFileName(srcPath));

            // Specifying the AESKeySize triggers AES encryption. 
            // Allowable values are 0 (off), 128 or 256. 
            // A password on the ZipOutputStream is required if using AES.
            zipEntry.AESKeySize = 256; 
            zipEntry.DateTime = DateTime.Now;

            zipStream.PutNextEntry(zipEntry);

            byte[] buffer = new byte[4096]; // Zip the file in buffered chunks

            using (FileStream fileStream = File.OpenRead(sourceFilePath))
            {
                // Using a fixed size buffer here makes no noticeable difference
                // for output but keeps a lid on memory usage.
                int sourceBytes = fileStream.Read(buffer, 0, buffer.Length);

                while (sourceBytes > 0)
                {
                    zipStream.Write(buffer, 0, sourceBytes);
                    sourceBytes = fileStream.Read(buffer, 0, buffer.Length);
                }
            }
        }
    }
}
```

### Expected behavior
Password protected zip file should be created.

### Actual behavior
Fails to encrypt zip file.

### Version of SharpZipLib
0.86.0.518

### Obtained from (place an x between the brackets for all that apply)
- Compiled from source
 - branch: master
 - commit: be53259

**Comment by fabien367** [comment]
Hello, for me it's the same.
I tried to change => public ZipAESTransform (string key, byte[] saltBytes, int blockSize, bool writeMode)
into byte[] byteKey2 =  pdb.GetBytes(_blockSize/2);

It work but I can't open the zip with the password because password is incorrect....

**Comment by konark** [comment]
@mattosaurus @fabien367 - I ran into a similar issue. Were you able to get around this?

**Comment by mattosaurus** [comment]
Hi @konark, I got round this using 7zip and calling the executable directly, not the tidiest solution but it worked for me.

`
public static void SevenZipFile(string sourceFilePath, string destinationArchiveFilePath, string password, string executablePath)
{
	System.Diagnostics.Process process = new System.Diagnostics.Process();
	System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
	startInfo.FileName = "\"" + executablePath + "\"";
	startInfo.Arguments = "a " + "\"" + destinationArchiveFilePath + "\"" + " -p" + "\"" + password + "\" -mem=AES256 \"" + sourceFilePath + "\"";
	process.StartInfo = startInfo;
	process.Start();
	process.WaitForExit();
}
`

**Comment by harrisonmeister** [comment]
Don't know if this will help at all, but experimenting with this library I found I received the exception when trying to zip a zero length (empty file). Specifically the part where you copy bytes into the zipentry stream. It's simple enough to resolve by checking the length of the file. If it's 0, don't do any copying. I have a sample snippet of code if anyone would find it useful

**Comment by alexhiggins732** [comment]
I don't receive an exception using 256. It creates the file but when attempting to open it says wrong password.

**Comment by FastJack2** [comment]
The Problem is in ZipAESTransform.cs functino ZipAESTransform()

if you alter it this way, it should work:

`public ZipAESTransform(string key, byte[] saltBytes, int blockSize, bool writeMode)
		{

			if (blockSize != 16 && blockSize != 32) // 24 valid for AES but not supported by Winzip
				throw new Exception("Invalid blocksize " + blockSize + ". Must be 16 or 32.");
			if (saltBytes.Length != blockSize / 2)
				throw new Exception("Invalid salt len. Must be " + blockSize / 2 + " for blocksize " + blockSize);
			// initialise the encryption buffer and buffer pos
			_blockSize = blockSize;
			_encryptBuffer = new byte[_blockSize];
			_encrPos = ENCRYPT_BLOCK;

			// Performs the equivalent of derive_key in Dr Brian Gladman's pwd2key.c
			var pdb = new Rfc2898DeriveBytes(key, saltBytes, KEY_ROUNDS);
            var rm = new AesManaged();//Aes.Create();
			rm.Mode = CipherMode.ECB;           // No feedback from cipher for CTR mode
			_counterNonce = new byte[_blockSize];
			byte[] byteKey1 = pdb.GetBytes(_blockSize);
			byte[] byteIV = pdb.GetBytes(_blockSize);
            if (byteIV.Length > 16)
            {
                byte[] byteInit = new byte[16];
                Buffer.BlockCopy(byteIV, 0, byteInit, 0, 16);
                byteIV = byteInit;
            }
            _encryptor = rm.CreateEncryptor(byteKey1, byteIV);
			_pwdVerifier = pdb.GetBytes(PWD_VER_LENGTH);
			//
			_hmacsha1 = IncrementalHash.CreateHMAC(HashAlgorithmName.SHA1, byteIV);
			_writeMode = writeMode;
		}`

problem seems to be that aes always needs 16 byte IV, even in 256bit mode, so just use the lower 16...

**Comment by piksel** [comment]
This looks like the solution. Want to make a PR?


________________________________

**Comment by harrisonmeister** [comment]
@piksel - I can raise one if you want. Which branch should I target?

**Comment by FastJack2** [comment]
Pull reuqest created:
https://github.com/icsharpcode/SharpZipLib/pull/260

**Comment by piksel** [comment]
@harrisonmeister This seems like a different issue. Could you make a separate issue with repro?

**Comment by AlexKeySmith** [comment]
Hi guys, out of interest did this ever make it into a nuget package? @harrisonmeister  @siegfriedpammer  thanks for looking after the project!

**Comment by piksel** [comment]
This is planned for v1.1, which will hopefully be released this weekend if I get the time.

**Comment by AlexKeySmith** [comment]
Great thanks @piksel
