### ISSUE TITLE
Undocumented .Net core dependencies when used with Windows Desktop

### ISSUE THREAD

**Issue by KimikoMuffin** [icsharpcode/SharpZipLib#184]
### Steps to reproduce
1. Check out a the latest commit 
2. Add a reference in a .Net Framework project to [the only available .csproj in /src/](https://github.com/icsharpcode/SharpZipLib/blob/master/src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj), which is .Net Core

### Actual behavior
It complains, within the .Net Framework project, that I need to install System.IO.FileSystem. When I actually try to run it, it throws an exception mentioning System.Security.Cryptography.Primitives. Since I was just quickly testing it, I'm not even sure I've caught everything that would need to be added.

### Version of SharpZipLib
The only available version currently, that is, the .Net Core version. The .Net 4.5 project from 9ad7f5845222c99ff009a1daddedc051d25a06b9 (deleted in 661f813fd16e1afaaba5a6fba958a5b57a4fdd37) works fine.

### Obtained from (place an x between the brackets for all that apply)
- [x] Compiled from source
 - branch: master
 - commit: 2ea330b92d4f91295611f0c61047e7cedb8d2b83
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by christophwille** [comment]
Yes, the current master on the repo is targetting netstandard (netstandard1.3 to be precise). Now NuGet support has landed for VS2015:

https://blog.nuget.org/20170815/Whats-nu-in-NuGet-with-VS2017-15-3.html#update-to-the-nuget-client-in-visual-studio-2015

This means future packages will be able to be added to almost any project type, given that the target framework supports netstandard1.3:

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Yes, this will cut off < 4.6 NETFW (for reference https://en.wikipedia.org/wiki/.NET_Framework_version_history#.NET_Framework_4.6)

**Comment by christophwille** [comment]
I think I can shed some light onto the issue now that I changed the samples to require the latest alpha package:

https://github.com/dotnet/corefx/issues/15570

Fix (packages.config snippet):

  &lt;package id="System.Security.Cryptography.Algorithms" version="4.2.0" targetFramework="net461" />
  &lt;package id="System.Security.Cryptography.Primitives" version="4.0.0" targetFramework="net461" />

You need to revert Algorithms to 4.2 (from 4.3) and Primitives to 4.0 (from 4.3). Don't know of a more elegant solution yet.

**Comment by christophwille** [comment]
https://github.com/dotnet/corefx/issues/23344

**Comment by ericstj** [comment]
@christophwille when you added the reference to the .net standard project from the .net framework project, was the .net framework project using packages.config?  If so then you must ensure you add a dependency to the NETStandard.Library package (this happens automatically when using PackageReference).  Packages.config projects don't automatically flow their nuget dependencies so you always need to copy them.

**Comment by christophwille** [comment]
@ericstj How it happened for me - the samples in https://github.com/icsharpcode/SharpZipLib/tree/master/samples/ICSharpCode.SharpZipLib.Samples were using direct project references (net461). I did the following:

deleted the project reference
installed the preview Nuget of SharpZipLib (alpha1)

This worked fine with the new Nuget 3.6 for VS 2015. Now, on running the sample (eg vb\viewzipfile) I got the loading exception on s.s.c.primitives (it expected 4.0). After some searching, I downgraded both s.s.c.algorithms (4.2; don't know if this even was necessary) and s.s.c.primitives to 4.0. Then it started working. https://github.com/icsharpcode/SharpZipLib/blob/master/samples/ICSharpCode.SharpZipLib.Samples/vb/viewzipfile/packages.config is "plain vanilla" except for the downgrades I manually performed.

What I don't understand is that the netstandard1.3 SharpZipLib binds against 4.0 in the first place.

**Comment by christophwille** [comment]
On creating a repro, I did a blank 461 project. This worked. Maybe those samples/.vb|csproj files are weird because they are like 10+ years old (the only difference seems that it references netstandard 2.0 nuget instead of 1.6.1)

**Comment by ericstj** [comment]
That sounds like you were missing bindingRedirects in the net461 project.  

Whenever we have builds of a library (especially different API) we have to give the library its own unique version so that it can be safely installed to the GAC without downgrading someone else's app-local copy.  Even within the single package we have differing versions between different TFMs (like netstandard1.3 and netstandard1.4 or net461) if the API exposed is different for this reason.  The result is that almost always need to enable bindingRedirects for desktop projects consuming nuget packages.  You'd run into the same thing with third-party libraries that version their assemblies (like Json.Net).
