### ISSUE TITLE
DocFX

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/SharpZipLib#185]
DocFX will be the new doc generator. However, this does not work with Core projects (yet)

https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#3-use-docfx-integrated-with-visual-studio

**Comment by christophwille** [comment]
https://github.com/icsharpcode/SharpZipLib/commit/b2948ab646ea0675a15bd413c84571ce696eb8a6
https://github.com/dotnet/docfx/issues/1752

**Comment by christophwille** [comment]
First version is online https://icsharpcode.github.io/SharpZipLib/help/

**Comment by Numpsy** [comment]
Is there anything that needs doing with this now?

**Comment by christophwille** [comment]
From my point of view - no.

**Comment by piksel** [comment]
Since #542 this is now built and updated on every release. Closing this.
