### ISSUE TITLE
State of the Union August 2017

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/SharpZipLib#187]
You will have noticed the recent activity by @siegfriedpammer and myself. Neither of us is the "maintainer" of this repository: I am the "custodian" (best description I could come up with) of the ic#code projects, and I roped in @siegfriedpammer (ILSpy) to help me put finishing touches on the almost-finished netstandard1.3 work after the Visual Studio 2017 Version 15.3 launch, which brought a couple of things:

 * .NET Core 2.0 final (which makes the unit tests work with NUnit properly)
 * NuGet support in VS 2015 (NuGet 3.6+ from nuget.org/downloads) to allow proper referencing of netstandard1.3 projects

This is reflected in that there are now -alpha builds available on NuGet.org for SharpZipLib. Why -alpha? Neither of us has followed the project for the past few years closely enough to make a proper judgement on the current quality at this point in time (we are still learning).

## What do you need to use the -alpha bits?

At least VS2015 with this applied https://blog.nuget.org/20170815/Whats-nu-in-NuGet-with-VS2017-15-3.html#update-to-the-nuget-client-in-visual-studio-2015

## Which .NET platforms will it work on?

See https://docs.microsoft.com/en-us/dotnet/standard/net-standard With -alpha1 targetting netstandard1.3, full .NET Framework 4.6 and newer for example. Details are in the matrix. Yes, this means for older projects, you are stuck with 0.86.

## About the license - what's the story here?

Yes, with -alpha1 the license switch to MIT is now fully realized. No more "It is amost like LGPL". Clean and simple.

## What do you need to open SharpZipLib's source code (dev)?

At least VS2017 Version 15.3 with the .NET Core 2.0 SDK installed.

## What about the open PRs with "NeedMIT" tag?

Those miss the following paragraph: "I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License."

Please always supply this. See Contributing.md.

## Want to help? (user of SharpZipLib)

Our pri1 item - please put the new -alpha packages through their paces! (notable change: Dispose instead of Close on streams)

## Want to help? (contributing to SharpZipLib)

SharpZipLib's code base has evolved over more than a decade (that's an understatement). It needs a (preferably more than one) maintainer that helps the community and can carefully evolve the library (no revolutions please, too many people depend on it). It needs more features, tests, performance, documentation, ... you name it. Feel free to ping me (email address on my profile) if interested in taking on this role.

The reason I am not asking for PRs (at least not in the first paragraph) is that both of us are not the maintainers (and maybe won't be around for long). But I am sure maintainers would love every help they can get!

**Comment by MichaelKetting** [comment]
@christophwille I've just noticed your state of the union adress. 

I'm very interested in learning why there is a need for dropping .NET 4.5 support? Are you depending on .NET APIs only available in .NET 4.6 and if so, it would be great if there was a list :)

Thanks, Michael

**Comment by christophwille** [comment]
From the above text: "Which .NET platforms will it work on? See https://docs.microsoft.com/en-us/dotnet/standard/net-standard With -alpha1 targetting netstandard1.3, full .NET Framework 4.6 and newer for example. Details are in the matrix. Yes, this means for older projects, you are stuck with 0.86."

**Comment by MichaelKetting** [comment]
Ah, I see. It's just a matter of doing a simple .NET Standard-Build without cross-compiling for .NET 4.5.

**Comment by renemadsen** [comment]
Hi,

I'm interested in taking over the maintenance of this project, so it can live on.

Let me know if that's something that is interesting.
