### ISSUE TITLE
API documentation missing?

### ISSUE THREAD

**Issue by HebaruSan** [icsharpcode/SharpZipLib#189]
### Steps to reproduce
1. Navigate to https://github.com/icsharpcode/SharpZipLib/blob/master/docs/help/index.md
2. Click "Looking for the API Documentation?"
3. Note that you end up on a [mostly empty page](https://github.com/icsharpcode/SharpZipLib/blob/master/docs/help/api/index.md) with no documentation. It mentions "the tree on the left side", but no such thing is visible.

Also check the [root README.md](https://github.com/icsharpcode/SharpZipLib/blob/master/README.md), the [home page](https://icsharpcode.github.io/SharpZipLib/), [project wiki](https://github.com/icsharpcode/SharpZipLib/wiki), the [FAQ](https://github.com/icsharpcode/SharpZipLib/wiki/FAQ), [Useful Links](https://github.com/icsharpcode/SharpZipLib/wiki/Links), etc., without luck.

### Expected behavior
Classes, properties, functions, parameters, etc. of the library should be listed with explanation of their use. Ideally some sample code as well. Should be easy to find via a web search of the package name.

### Actual behavior
No information is presented.

### Version of SharpZipLib
Github master HEAD

### Obtained from (place an x between the brackets for all that apply)
N/A

**Comment by christophwille** [comment]
Not missing: https://github.com/icsharpcode/SharpZipLib/blob/master/docs/help/BuildingHelpInfo.txt

It is live at https://icsharpcode.github.io/SharpZipLib/help/api/index.html

Chris

**Comment by HebaruSan** [comment]
But do you see how it _appears_ to be missing? I listed six places where it could reasonably be expected to be linked, and ultimately I was not able to find it at all. Could at least some of those places be updated with that link? (I'll pop over to the wiki myself now...)
