### ISSUE TITLE
TarOutputStream doesn't write final record on Finish()

### ISSUE THREAD

**Issue by zou1003** [icsharpcode/SharpZipLib#191]
because the last block was not written to outputStream.  
so TarOutputStream.Finish() should call buffer.WriteFinalRecord() method as fellow：
```.cs
public void Finish()
{
	if (IsEntryOpen) {
		CloseEntry();
	}
            
	WriteEofBlock(); 
	//write the FinalRecord To outputStream
	buffer.WriteFinalRecord();
}
```

**Comment by Numpsy** [comment]
Is this actually the same issue as #14 ?

**Comment by piksel** [comment]
Yeah, im not really sure what the correct behaviour is here. I always close the streams, but I guess calling `Finish()`

**Comment by Numpsy** [comment]
Ditto.
#14 suggests it could be a documentation issue rather than a bug, I'm not sure if changing the behaviour of Finish() at this point could break any existing usage or not.

**Comment by piksel** [comment]
Closing this as a duplicate of #14
