### ISSUE TITLE
1 is not a supported code page. parameter name: codepage

### ISSUE THREAD

**Issue by dileepkumars1** [icsharpcode/SharpZipLib#195]
We are using the SharpZipLib library for many years. The version used now is 0.86.0 obtained as Nuget. The issue is a functionality in our application used for zipping a stream with password is now failing with the error "1 is not a supported code page. parameter name: codepage". This is in azure environment and so this might not be because of the system locale. I have verified the locale and it is English US.

We were expecting this error in client machines as the system locale may be different and if the code page error was thrown, the default codepage was set to utf-8. 

The functionality was working fine in Azure till last month and all of a sudden without any code change this is failing now. Could this because of a change in the environment due to a windows update?

Please help!!!!

**Comment by amitgobare23** [comment]
@dileepkumars1 why this issue was closed?
Please give me solution for same error to read .xlsx file
Thanks in Advance!

**Comment by dileepkumars1** [comment]
@amitgobare23 I closed the issue as I didn't get any updates from anybody. I do not have a solution other than the one I mentioned in the question. Either set DefaultCodePage as 850 or use the latest version of the library. I was using an older version of the library and the current version is defaulting to UTF8.

Hope this helps.
Thanks

**Comment by sgryt** [comment]
Windows 10 users that are forced to live with 'older' versions of the library (for some reason or the other) can try the following, which worked for us (using version 0.86.0.518).

Set the first Preferred Language to "English (United States)" under the Language section in the Settings App (Start Menu -> Settings -> Time & Language -> Language).

We had a situation where there would be no problems on one machine, but the error showed up consistently on another machine. The faulting machine had "English (Denmark)" set as the first preferred language, and "English (United States)" as the second. Swapping the order made the problem go away.

**Comment by ankitjaadoo** [comment]
Hi, what exactly is the DefaultCodePage configuration all about? I am getting this error: 1 is not a supported codepage. But not sure where to change this default codepage settings to 850 as mentioned above by @dileepkumars1

**Comment by piksel** [comment]
@ankitjaadoo I think it was in `ZipConstants.DefaultCodePage`, I presume you are using v0.86?

**Comment by m-stilling** [comment]
Sorry for pinging an old issue. In our case it was specifically the regional formatting settings which we had to change from Danish to English (United States) to resolve the issue. No restart necessary.
