### ISSUE TITLE
Invalid Size - PutNextEntry

### ISSUE THREAD

**Issue by Biztactix-Ryan** [icsharpcode/SharpZipLib#196]
### Steps to reproduce
```
 Dim strmFile As IO.FileStream = File.OpenRead(tobezipped.OriginalFileName)
            Dim objZipEntry As ZipEntry = New ZipEntry(tobezipped.Location & "\" & tobezipped.Filename)
            objZipEntry.DateTime = DateTime.FromFileTimeUtc(tobezipped.CreateTimeUTC)
            objZipEntry.Size = tobezipped.FileSize
            ZipStream.PutNextEntry(objZipEntry)
```
I use the above code in a loop, where I zip all the files, I've done this hundreds of times, Then suddenly it started throwing an exception

### Expected behavior
Should just add the file

### Actual behavior
Exception "Additional information: size was 1378351, but I expected 1378346"
However the file I'm trying to add to the zip is not that size at all... I guess it's related to the object size, But I'm not sure why it started doing this.

### Version of SharpZipLib
0.86.0

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ x ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**********************
I believe it's related to 
Line 435 in ZipOutputStream
else if (curEntry.Size != size) {
				throw new ZipException("size was " + size + ", but I expected " + curEntry.Size);
			}

**Comment by tithibh** [comment]
I am having exact same issue. But I don't see any reply on this thread.
I have noticed this issue happens when the size of the folder is quiet big(17Gb)
Also I want to know how the size is set to ZipSteam. coz I fill issue is between Size of zipsteam and size of zipentry.
should we call Zipstream.Write before ZipStream.PutNextEntry to set the zip stream size

**Comment by piksel** [comment]
There is a VB example in the wiki: [Create-a-Zip-with-full-control-over-content](https://github.com/icsharpcode/SharpZipLib/wiki/Create-a-Zip-with-full-control-over-content) (after the C# one).

My guess is that the issue above was because of some mistake in the authors code, hence why it was self closed.

> Also I want to know how the size is set to ZipSteam. coz I fill issue is between Size of zipsteam and size of zipentry.
should we call Zipstream.Write before ZipStream.PutNextEntry to set the zip stream size

Are you talking about the compressed size?
The uncompressed size is set in the entry, which *has* to be set *before* writing to the stream:
```vb
Using fileStream As FileStream = File.OpenRead(filename)
        Dim newEntry As New ZipEntry(entryName)
        newEntry.Size = fileStream.Length
        zipStream.PutNextEntry(newEntry)
        fileStream.CopyTo(zipStream, 4096)
End Using
```

**Comment by tithibh** [comment]
Hi pikksel,
I am doing the exact same thing in C#.
but when the folder size is big that time the exception is thrown 
"ZLib.ZipException: size was 1544595, but I expected 1494912
   at ZLib.Zip.ZipOutputStream.CloseEntry()
   at ZLib.Zip.ZipOutputStream.PutNextEntry(ZipEntry entry)"

when I checked the ZipOutputStream.cs class
here are those 2 methods
    public void PutNextEntry(ZipEntry entry)
    {
      if (this.entries == null)
        throw new InvalidOperationException("ZipOutputStream was finished");
      CompressionMethod compressionMethod = entry.CompressionMethod;
      int num = 0;
      entry.IsCrypted = this.Password != null;
      switch (compressionMethod)
      {
        case CompressionMethod.Stored:
          if (entry.CompressedSize >= 0L)
          {
            if (entry.Size < 0L)
              entry.Size = entry.CompressedSize;
            else if (entry.Size != entry.CompressedSize)
              throw new ZipException("Method STORED, but compressed size != size");
          }
          else
            entry.CompressedSize = entry.Size;
          if (entry.IsCrypted)
            entry.CompressedSize += 12L;
          if (entry.Size < 0L)
            throw new ZipException("Method STORED, but size not set");
          if (entry.Crc < 0L)
            throw new ZipException("Method STORED, but crc not set");
          break;
        case CompressionMethod.Deflated:
          if (entry.CompressedSize < 0L || entry.Size < 0L || entry.Crc < 0L)
          {
            num |= 8;
            break;
          }
          break;
      }
      if (this.curEntry != null)
        this.CloseEntry();
      if (entry.IsCrypted)
        num |= 1;
      entry.Flags = num;
      entry.Offset = this.offset;
      entry.CompressionMethod = compressionMethod;
      this.curMethod = compressionMethod;
      this.WriteLeInt(67324752);
      this.WriteLeShort(compressionMethod == CompressionMethod.Stored ? 10 : 20);
      if ((num & 8) == 0)
      {
        this.WriteLeShort(num);
        this.WriteLeShort((int) (byte) compressionMethod);
        this.WriteLeInt((int) entry.DosTime);
        this.WriteLeInt((int) entry.Crc);
        this.WriteLeInt((int) entry.CompressedSize);
        this.WriteLeInt((int) entry.Size);
      }
      else
      {
        if (this.baseOutputStream.CanSeek)
        {
          this.shouldWriteBack = true;
          this.WriteLeShort((int) (short) (num & -9));
        }
        else
        {
          this.shouldWriteBack = false;
          this.WriteLeShort(num);
        }
        this.WriteLeShort((int) (byte) compressionMethod);
        this.WriteLeInt((int) entry.DosTime);
        if (this.baseOutputStream.CanSeek)
          this.seekPos = this.baseOutputStream.Position;
        this.WriteLeInt(0);
        this.WriteLeInt(0);
        this.WriteLeInt(0);
      }
      byte[] array = ZipConstants.ConvertToArray(entry.Name);
      if (array.Length > (int) ushort.MaxValue)
        throw new ZipException("Name too long.");
      byte[] buffer = entry.ExtraData ?? new byte[0];
      if (buffer.Length > (int) ushort.MaxValue)
        throw new ZipException("Extra data too long.");
      this.WriteLeShort(array.Length);
      this.WriteLeShort(buffer.Length);
      this.baseOutputStream.Write(array, 0, array.Length);
      this.baseOutputStream.Write(buffer, 0, buffer.Length);
      if (this.Password != null)
      {
        this.InitializePassword(this.Password);
        byte[] numArray = new byte[12];
        Random random = new Random();
        for (int index = 0; index < numArray.Length; ++index)
          numArray[index] = (byte) random.Next();
        this.EncryptBlock(numArray, 0, numArray.Length);
        this.baseOutputStream.Write(numArray, 0, numArray.Length);
      }
      this.offset += 30 + array.Length + buffer.Length;
      this.curEntry = entry;
      this.crc.Reset();
      if (compressionMethod == CompressionMethod.Deflated)
        this.def.Reset();
      this.size = 0;
    }

--------
    public void CloseEntry()
    {
      if (this.curEntry == null)
        throw new InvalidOperationException("No open entry");
      if (this.curMethod == CompressionMethod.Deflated)
        base.Finish();
      int num = this.curMethod == CompressionMethod.Deflated ? this.def.TotalOut : this.size;
      if (this.curEntry.Size < 0L)
        this.curEntry.Size = (long) this.size;
      else if (this.curEntry.Size != (long) this.size)
        throw new ZipException("size was " + (object) this.size + ", but I expected " + (object) this.curEntry.Size);
      if (this.curEntry.IsCrypted)
        num += 12;
      if (this.curEntry.CompressedSize < 0L)
        this.curEntry.CompressedSize = (long) num;
      else if (this.curEntry.CompressedSize != (long) num)
        throw new ZipException("compressed size was " + (object) num + ", but I expected " + (object) this.curEntry.CompressedSize);
      if (this.curEntry.Crc < 0L)
        this.curEntry.Crc = this.crc.Value;
      else if (this.curEntry.Crc != this.crc.Value)
        throw new ZipException("crc was " + (object) this.crc.Value + ", but I expected " + (object) this.curEntry.Crc);
      this.offset += num;
      if (this.curMethod == CompressionMethod.Deflated && (uint) (this.curEntry.Flags & 8) > 0U)
      {
        if (this.shouldWriteBack)
        {
          this.curEntry.Flags &= -9;
          long position = this.baseOutputStream.Position;
          this.baseOutputStream.Seek(this.seekPos, SeekOrigin.Begin);
          this.WriteLeInt((int) this.curEntry.Crc);
          this.WriteLeInt((int) this.curEntry.CompressedSize);
          this.WriteLeInt((int) this.curEntry.Size);
          this.baseOutputStream.Seek(position, SeekOrigin.Begin);
          this.shouldWriteBack = false;
        }
        else
        {
          this.WriteLeInt(134695760);
          this.WriteLeInt((int) this.curEntry.Crc);
          this.WriteLeInt((int) this.curEntry.CompressedSize);
          this.WriteLeInt((int) this.curEntry.Size);
          this.offset += 16;
        }
      }
      this.entries.Add((object) this.curEntry);
      this.curEntry = (ZipEntry) null;
    }
-------------
I am getting exception from ----else if (this.curEntry.Size != (long) this.size)
        throw new ZipException("size was " + (object) this.size + ", but I expected " + (object) this.curEntry.Size);

So I am curious about this.size field and how the value gets set there.

**Comment by piksel** [comment]
`ZipOutputStream.size` is a counter that is incremented when data is written to the stream:
https://github.com/icsharpcode/SharpZipLib/blob/8c0a16904a0fa545c198c2ebe56335974925d120/src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs#L753-L786

It looks like the last 49683 bytes are not written before the next entry is added. Create a new [Discussion](https://github.com/icsharpcode/SharpZipLib/discussions/categories/q-a) with your code if you want assistance in finding out why.
