### ISSUE TITLE
The http://icsharpcode.github.io/SharpZipLib/ page still shows the GPL license instead of MIT

### ISSUE THREAD

**Issue by fastrocket** [icsharpcode/SharpZipLib#200]
Would be great if that page could be updated to reflect the MIT license since it is linked from this project's home page.

**Comment by hrieke** [comment]
If you download the latest version, 0.86.0.518, the license files (ReadMe.rtf, Copying.txt) are GNU General Public License v2.0 w/Classpath exception.
I think the change to MIT License will take a while, but until then, they really should move everything back to the GPL listed.
Also, please don't forget to update the license text in the source code too!
Thanks!

**Comment by Numpsy** [comment]
Looks to have all been updated now.

**Comment by piksel** [comment]
Yes, not sure why this wasn't closed.
