### ISSUE TITLE
The number of blocks is larger than the maximum of '50000'

### ISSUE THREAD

**Issue by jianguoj** [icsharpcode/SharpZipLib#207]
### Steps to reproduce
1. With the number of blocks greater than 50000
2. instantiate a ICSharpCode.SharpZipLib.Zip.Zipper 
3. call the Add()

### Expected behavior
No error

### Actual behavior
The call threw an exception: The number of blocks is larger than the maximum of '50000'

### Version of SharpZipLib
Runtime Version: v4.0.30319
Version 0.90.0.0
### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [X] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by piksel** [comment]
There is no `ICSharpCode.SharpZipLib.Zip.Zipper` and no v0.90 nuget package.

Maybe you are using a fork?
