### ISSUE TITLE
Error with unzipping .zip file zipped with 7-zip

### ISSUE THREAD

**Issue by Nisefal** [icsharpcode/SharpZipLib#211]
### Steps to reproduce
1. zip something with 7-zip 
2. try to unzip with FastZip
3. it throws error "central directory cannot be found" or like

### Expected behavior
It should unzip

### Actual behavior
It doesn't

### Version of SharpZipLib
0.86.0

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [x ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

Comment: IMHO it does not recognize ziped folders.

**Comment by IanYates** [comment]
Can you attach an example zip file made from 7-Zip and the settings used to create it?

**Comment by Nisefal** [comment]
Uh, sorry. Looks like problem was not with your code, but with file. It was corrupted while sending.
