### ISSUE TITLE
Can not open project in Visual Studio 2015

### ISSUE THREAD

**Issue by KHerron** [icsharpcode/SharpZipLib#217]
### Steps to reproduce
1. Downloaded project as Zip
2. Moved to development folder
3. UnZipped compressed file
4. Opened Visual Studio 2015
5. File -> Open -> Project/Solution  C:\DevelopmentFolder\SharpZipLib-Master\ICSharpCodeSharpZipLib.Sln.

### Expected behavior
Project Loads in to Visual Studio

### Actual behavior
ERROR: SharpZipLib-master\src\ICSharpCode.SharpZipLib\ICSharpCode.SharpZipLib.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  J:\OSA Files\SharpZipLib-master\SharpZipLib-master\src\ICSharpCode.SharpZipLib\ICSharpCode.SharpZipLib.csproj

**Comment by johntiger1** [comment]
@testlump Is it not supported at all in VS2015/VS2010?

**Comment by testlump** [comment]
The latest source here contains on github .NET core compatability and so the project opens only in VS2017. You can get older copy of the source (functionally identical I think) which is compatible with earlier VS versions from the releases page here: https://github.com/icsharpcode/SharpZipLib/releases - Download **SharpZipLib_0860_SourceSamples.zip** and then you can open the solution in either VS2005, 2008, 2010 or even 2013 - see the **SrcSamples\src\** folder inside the archive.

**Comment by KHerron** [comment]
Yes, thank you to everyone who commented.
The library works fine in my project that I am creating using VS-15.
I was just wanting to play with some of the samples, to see what all I could do in my project.
I have over come my issue and am moving forward with good progress.

Thanks again.
