### ISSUE TITLE
I cant extract zipfile with empty directroy by using FastZip, why?

### ISSUE THREAD

**Issue by zyplay** [icsharpcode/SharpZipLib#221]
TestCaption = @"d:\Test\ziptest.zip";
            TestCaption2 = @"D:\Test\unZip";
            FastZip fz = new FastZip();
            fz.RestoreDateTimeOnExtract = true; 
            fz.ExtractZip(TestCaption, TestCaption2, "");
There is a empty dir in ziptest.zip, but I cant find it in unZip, why?
and the same happens when I use CreateZip.

**Comment by swat199538** [comment]
How did you solve the problem?

**Comment by swat199538** [comment]
var fastzip = new FastZip();
fastzip.CreateEmptyDirectories = true

can solve this problem
