### ISSUE TITLE
How to build it in VS2008 with .NET Compact Framework?

### ISSUE THREAD

**Issue by ropinheiro** [icsharpcode/SharpZipLib#227]
### Expected behavior
Open (with or without ninja hacks) some csproj ou sln in VS2008 and build it in .NET Compact Framework

### Actual behavior
It opens only in VS2017.

### Version of SharpZipLib
Latest.

**Comment by piksel** [comment]
Compact Framework is currently not supported.

If you want to attempt to get it working, I'd suggest starting with commit 2c458be35c4f21a66aab2f625fdb0e94d93be809 as it used the old solution syntax.

I don't have VS2008 on any of my machines, nor do I have any experience with CF, so unfortunately I have not been able to test this.
