### ISSUE TITLE
TestArchive hangs 

### ISSUE THREAD

**Issue by dlloyd525** [icsharpcode/SharpZipLib#229]
[afmlsxmio.zip](https://github.com/icsharpcode/SharpZipLib/files/2030928/afmlsxmio.zip)

### Steps to reproduce
The attached zip file is apparently corrupted.  It was received from a GOES satellite.  Using the TestArchive method results in the component hanging.

### Expected behavior
Return false - indicating that the archive failed.

### Actual behavior
The component hangs at
Worker Thread	ICSharpCode.SharpZipLib.dll!ICSharpCode.SharpZipLib.Checksums.Crc32.Update

### Version of SharpZipLib
0.86.0.518

### Obtained from (place an x between the brackets for all that apply)
- [ X] Downloaded DLL from GitHub

**Comment by jfreilly** [comment]
The archive has an invalid CRC.
