### ISSUE TITLE
Could I use it on android with Unity3d?

### ISSUE THREAD

**Issue by ZhengzhongSun** [icsharpcode/SharpZipLib#231]
Any suggestion will be appreciated

**Comment by piksel** [comment]
As of [2018.1](https://blogs.unity3d.com/2018/03/28/updated-scripting-runtime-in-unity-2018-1-what-does-the-future-hold/) it seems like it should work, but I have not tried it.
Both the target profiles are supported by SharpZipLib v1.0+:
 - .NET Standard 2.0
 - .NET 4.x. (should be equivalent to 4.7.1)

Please let us know if you get it working!

**Comment by Dkcrow1997** [comment]
If you use this plugin in Unity version 19 or higher and the project runs on Android.
You need to be in this path in the Unity editor below version 19: editor \ Data \ Mono \ lib \ mono \ unity.Copy some DLL files to your project
![image](https://user-images.githubusercontent.com/37021979/82775787-573cf480-9e7b-11ea-8612-532f38897051.png)
