### ISSUE TITLE
GZip decompression works as expected on Windows, but fails on Linux (Mono)

### ISSUE THREAD

**Issue by AlexeyEvlampiev** [icsharpcode/SharpZipLib#237]
### Steps to reproduce
1. Compile and execute the code below on Windows
2. Compile and execute the code below on Linux (Mono)

```cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ConsoleAppl
{
	class MainClass
	{
		public static void Main (string[] args)
		{			
			var helloWorldZippedBytes = Convert.FromBase64String ("H4sIAAAAAAAAA/NIzcnJVwAAwPwt6gYAAAAfiwgAAAAAAAADUyjPL8pJUQQAqd+XkgcAAAA=");

			using (var buffer = new MemoryStream (helloWorldZippedBytes))
			using(var gz = new System.IO.Compression.GZipStream(buffer, System.IO.Compression.CompressionMode.Decompress)){
				var reader = new StreamReader (gz);
				Console.WriteLine ("{0,-16} <- by Microsoft",reader.ReadToEnd());
			}
				

			using (var buffer = new MemoryStream (helloWorldZippedBytes))
			using(var gz = new ICSharpCode.SharpZipLib.GZip.GZipInputStream(buffer)){
				var reader = new StreamReader (gz);
				Console.WriteLine ("{0,-16} <- by SharpZipLib",reader.ReadToEnd());
			}

		}
	}
}
```

### Expected behavior
Decompression with SharpZipLib should yield `Hello world!` on both Windows and Linux

### Actual behavior
Decompression with SharpZipLib yields `Hello world!` only on Windows. Decompression on Linux yields just the `Hello` part of the phrase.
Note: The standard MSFT library yields always only the `Hello` part, which is a known bug.

### Version of SharpZipLib
4.84.0.0

**Comment by piksel** [comment]
What version of the library are you using? Are you building from source? 4.48 is not a official version, do you mean 0.84?

**Comment by AlexeyEvlampiev** [comment]
My apologies, the version is 0.86.0

**Comment by piksel** [comment]
Do you have a link to said bug?

I have reproduced the result, although it works correctly on .NET Core.
Do you know what triggers the bug? Is it just for short inputs? Are the double spaces important?

**Comment by AlexeyEvlampiev** [comment]
I don't have a link yet. Recently I managed to inform the MSFT .NET team on the issue and am expecting to receive an update from them. I could reproduce the issue with .NET Core as well as with Mono on both Windows and Linux. Which version of .NET Core worked fine for you? On which OS?
Apparently the native stream adapter sees EOS at the position prior to the next gzip part in the appended gzip. Appended gzip files of any length cannot be decompressed correctly. The double spaces do not play any role here. In Big Data workflows practically all files are appended gzips, so the problem manifests itself clearly.

**Comment by piksel** [comment]
## Working:
```
OS: Microsoft Windows NT 6.2.9200.0 (Windows 10 x64 Ultimate)
Framework: .NETCoreApp,Version=v2.1

Hello            <- by Microsoft
Bytes: 48 65 6c 6c 6f 20
Read count: 6
Hello  world!    <- by SharpZipLib
Bytes: 48 65 6c 6c 6f 20 20 77 6f 72 6c 64 21
Read count: 13
______________________________________________________________

OS: Microsoft Windows NT 6.2.9200.0 (Windows 10 x64 Ultimate)
Framework: .NETCoreApp,Version=v2.0

Hello            <- by Microsoft
Bytes: 48 65 6c 6c 6f 20
Read count: 6
Hello  world!    <- by SharpZipLib
Bytes: 48 65 6c 6c 6f 20 20 77 6f 72 6c 64 21
Read count: 13
______________________________________________________________

OS: Microsoft Windows NT 6.2.9200.0 (Windows 10 x64 Ultimate)
Framework: .NETFramework,Version=v4.6

Hello            <- by Microsoft
Bytes: 48 65 6c 6c 6f 20
Read count: 6
Hello  world!    <- by SharpZipLib
Bytes: 48 65 6c 6c 6f 20 20 77 6f 72 6c 64 21
Read count: 13
______________________________________________________________

OS: Unix 4.15.0.23 (ubuntu 18.04 x64)
Framework: .NETCoreApp,Version=v2.0

Hello            <- by Microsoft
Bytes: 48 65 6c 6c 6f 20
Read count: 6
Hello  world!    <- by SharpZipLib
Bytes: 48 65 6c 6c 6f 20 20 77 6f 72 6c 64 21
Read count: 13

OS: Microsoft Windows NT 6.2.9200.0 (Windows 10 x64 Ultimate)
Framework: .NETFramework,Version=v4.6 (Mono v5.12.0)

Hello            <- by Microsoft
Bytes: 48 65 6c 6c 6f 20
Read count: 6
Hello  world!    <- by SharpZipLib
Bytes: 48 65 6c 6c 6f 20 20 77 6f 72 6c 64 21
Read count: 13
```

## Not working:
```
OS: Unix 4.15.0.23 (ubuntu 18.04 x64)
Framework: .NETFramework,Version=v4.5 (Mono v4.6.2)

Hello            <- by Microsoft
Bytes: 48 65 6c 6c 6f 20
Read count: 6
Hello            <- by SharpZipLib
Bytes: 48 65 6c 6c 6f 20
```

**Comment by AlexeyEvlampiev** [comment]
Upgraded software on my ubuntu 18.04 machine, did solve the problem. I am a bit  puzzled with the dependency on the Mono version, but am absolutely satisfied with the issue being resolved. Thank you very much!

**Comment by piksel** [comment]
Okay, I found the cause!

You mentioned v4.84, which is indeed the "correct" version.
As it turns out, mono ships it's own ICSharpCode.SharpZipLib!

Output from the mono v5.10:
```
Framework: .NETFramework,Version=v4.6.1 CLR: 4.0.30319.42000
OS: Unix 4.14.12.41412 X64 X64

System.IO.Compression.GZipStream (System v4.0.0.0):
Result: Hello         48 65 6c 6c 6f 20                       ( 6)

ICSharpCode.SharpZipLib.GZip.GZipInputStream (ICSharpCode.SharpZipLib v4.84.0.0):
Result: Hello         48 65 6c 6c 6f 20                       ( 6)
```

But from the release notes of v5.12:
> The ICSharpCode.SharpZipLib assembly was marked as obsolete and will be removed in a future release. We recommend replacing the very old implementation we ship with the official NuGet package available at https://www.nuget.org/packages/SharpZipLib/.

So as of [mono/mono@2a03be3](https://github.com/mono/mono/commit/2a03be316d4e762168dd602a493d94944ccc9446) it's not in the GAC anymore and the correct version is being used.

**Comment by AlexeyEvlampiev** [comment]
Ah, I see. First I read the version from the referenced assembly right from within MonoDevelop and then corrected myself after checking out the NuGet packages. So apparently my executable was binding with GAC instead of the NuGet library. The case is clear now. Thanks a lot!
