### ISSUE TITLE
Filename access isnt supported

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#25]
[SD-354](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=354), originally created on 4/26/2005 21:20:24 by John Reilly

The reading and writing of fields and the associated flags in gzip
headers isn't supported.

bit 0 FTEXT
bit 1 FHCRC
bit 2 FEXTRA
bit 3 FNAME

**Comment by piksel** [comment]
Closing this in favor of #418 and #175
