### ISSUE TITLE
ZipConstants.DefaultCodePage is set as UTF-8, but the default for FileEntry.IsUnicodeText is still false

### ISSUE THREAD

**Issue by tabhuang** [icsharpcode/SharpZipLib#251]
Zip chinese filename, but I get filename with garbled text.
#NET45 
#C Sharp
#v1.0.0 RC1
#ZipEntry
https://github.com/icsharpcode/SharpZipLib/releases

Test Chinese Filename
[測試.txt](https://github.com/icsharpcode/SharpZipLib/files/2197070/default.txt)

Zip Filename like "測試.txt", but I get filename "皜祈岫.txt".
![2018-07-16_172858](https://user-images.githubusercontent.com/8554884/42751584-d4ab86e0-891d-11e8-8d9d-419366f331ec.png)

Version 0.86.0.518 is OK, but 1.0.0 is wrong.

**Comment by piksel** [comment]
Could you provide a sample file that does not work? You can upload it here by dragging it into the textbox.

**Comment by cerasumat** [comment]
I got the same problem, my file directory contains chinese like '/mnt/img/汉字/1.png', the file in the zip file turned to '/mnt/img/xxx(messy code)/1.png'.
enviroment: centOS 7.1, .net core 2.1

**Comment by piksel** [comment]
Update to @cerasumat:
Works if the correct encoding is specified:
```
$ unzip -l -v -O UTF-8 test.zip
Archive:  test.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     306  Defl:N      249  19% 2018-07-18 17:54 19dbc344  測試.txt
--------          -------  ---                            -------
     306              249  19%                            1 file
```

**Comment by shikelong** [comment]
How to fix it?

**Comment by tabhuang** [comment]
It is work.

Step1. 
I try to edit the file [ZipConstants.cs]
[ZipConstants.txt](https://github.com/icsharpcode/SharpZipLib/files/2213373/ZipConstants.txt)

Step2.
In my program, before use zip, insert code like the:
Encoding big5 = Encoding.GetEncoding("Big5");
ZipConstants.DefaultCodePage = big5.CodePage;

**Comment by piksel** [comment]
@tabhuang Yes, you can just use 
```.cs
ZipConstants.DefaultCodePage = Encoding.GetEncoding("Big5").CodePage;
```
To use a custom code page for the file names.

To use Unicode you have to set the `ZipEntry.IsUnicodeText` to `true`.
If you are using `FastZip` you can just set it on the EntryFactory:
```.cs
fastZip.EntryFactory = new ZipEntryFactory
{
    IsUnicodeText = true
};
```

**Comment by piksel** [comment]
Turns out, this is a bug after all.

The default settings for file name encoding yields the wrong output.
