### ISSUE TITLE
Tar filenames with national characters not correctly stored.

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#26]
[SD-406](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=406), originally created on 8/9/2005 12:00:36 by John Reilly

Hello,
I have this problem:
When adding files with national characters in filenames to the
tar, the tar is corrupted (e.g. PowerArchiver can't extract it. It can
do it with itself-created TAR with the same contents (files), so the
problem is definitely on #ziplib side )

The code
Console.WriteLine("Adding file '"+ entry.Name +"'");
writes the entry's filename right.

Is there some way to push #ziplib to support national characters in
filenames? (or should I use other format/library?)

Thank you very much

**Comment by Numpsy** [comment]
would this be handled by #364?

**Comment by piksel** [comment]
Yes! Nice find.
