### ISSUE TITLE
Consideration: Use encryption library?

### ISSUE THREAD

**Issue by piksel** [icsharpcode/SharpZipLib#263]
There are industry-standard encryption libraries that might be better suited for the encryption implementation in zip.
They can be included by source to avoid adding additional dependencies, and to only include the necessary parts.

Drawbacks:
 - Increased binary size
 - Probably slower due to not using native code

Requirements:
 - MIT License or equivalent
 - Modular source

Candidates:
 - [Bouncy Castle](http://www.bouncycastle.org/csharp/)
 - [sodium](https://github.com/adamcaudill/libsodium-net)

**Comment by christophwille** [comment]
I strongly vote for using what's inside the framework(s), and only then dragging in a third-party library (because it causes a dependency for the downstream user, who already might be using a different version of said library - or it is way too heavy).

**Comment by piksel** [comment]
@christophwille It's only a really small subset that needs to be included, and it would be included in the source, using a separate namespace. The only parts we need are Symmetric CTR mode for Rijndael, HMAC-SHA1 and PBKDF2.
One of the problems with the current code is that `System.Security.Cryptography.AsymmetricAlgorithm` lacks support for CTR.
It is instead done manually in `ZipAESTransform` by using ECB mode and I lack the cryptography knowledge to verify that it's correctly implemented. That's why I leave crypto implementations to NaCl and BC which I trust.

That being said, archives created with AES encryption (since 975d5b0) are extractable by 7-zip without errors, so it *should* be fine.

**Comment by christophwille** [comment]
Including actual cryptographical algorithm implementations has potential legal implications; using / adapting "stuff" that's inside the framework or a separate library is ok (after all, we do not ship the implementations).

**Comment by piksel** [comment]
@christophwille Good point. I didn't even consider the US crypto export regulation and such. I didn't think that was a problem anymore, but I'd rather not find out.

So we stick with the current implementation. I am fine with that, I just wanted to bring this up for discussion.
