### ISSUE TITLE
Enable SourceLink for easier debugging

### ISSUE THREAD

**Issue by MagicAndre1981** [icsharpcode/SharpZipLib#269]
### Expected  behavior

Press F11 to step into code and debug the code

### Actual behavior

because no PDBs + source info are found, debugger steps over

### Version of SharpZipLib

1.0.0

### Obtained from (place an x between the brackets for all that apply)
- Package installed using:
  - NuGet
### Solution: 

[enable SourceLink](https://github.com/dotnet/sourcelink#using-sourcelink) + [pack PDBs inside the NuGet package](https://github.com/aspnet/Universe/issues/131#issuecomment-363269268) to [fetch the source from github](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md#source-link-file-specification) during debugging to be able to step into the code.

**Comment by MagicAndre1981** [comment]
Here is a blog post about it:

https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html

**Comment by piksel** [comment]
The PDB's will probably not be added, but SourceLink should be in the next release.

**Comment by MagicAndre1981** [comment]
without PDBs you have no SourceLink. The JSON with the SourceLink data is embedded to the PDB.

**Comment by MagicAndre1981** [comment]
thanks, works fine so far.

**Comment by MagicAndre1981** [comment]
@piksel  1 thing. You need to add to release notes, that the [new csproj format does't copy the PDB to output](https://github.com/dotnet/sdk/issues/1458).
