### ISSUE TITLE
Encoding can't be set as intended

### ISSUE THREAD

**Issue by Muffexx** [icsharpcode/SharpZipLib#274]
### Steps to reproduce
Encode ZipFile using 7Zip (including non ASCII characters like "ä", "ü")
Try to unzip using SharpZipLib with _CodePage_ set to "850".

### Expected behavior
Characters should be decoded correctly (including non ASCII characters).

### Actual behavior
Non ASCII characters aren't decoded correctly.

### Version of SharpZipLib
1.0.0

### Obtained from (place an x between the brackets for all that apply)
- Package installed using:
  - NuGet

### Comment
when looking at (in ZipStrings)

```.cs
private static Encoding EncodingFromFlag(int flags)
			=> ((flags & (int)GeneralBitFlags.UnicodeText) != 0)
				? Encoding.UTF8
                                : Encoding.GetEncoding(_SystemDefaultCodePage_)
```

I'm not sure whether this is as intended - since the _Codepage_ Property could be used instead of _SystemDefaultCodePage_.

The only way to get the characters decoded correctly is to encrypt via 7Zip with the cu-flag set to on (7-Zip uses UTF-8 for file names that contain non-ASCII symbols)
or setting the _SystemDefaultCodePage_ via reflection to a suitable codepage.

Maybe a setter for _SystemDefaultCodePage_ can be added
or _Codepage_ can be used in the mentioned code part?

Hope I didn't overlook anything.
regards

**Comment by piksel** [comment]
Setting a custom encoding is not currently supported for extracting an archive, but it should be kind of trivial to add. Like adding a `CustomEncoding` property that, if set, is used instead of `SystemDefaultCodePage`.

A PR would be welcomed!

Also: I am a bit confused about your description, perhaps you could clarify this?

First in steps to reproduce:
> Encode ZipFile using 7Zip (including non ASCII characters like "ä", "ü")
> Try to unzip using SharpZipLib with CodePage set to "850".

But later on:
> (7-Zip uses UTF-8 for file names that contain non-ASCII symbols)

Why do you try to extract it with another encoding then?

**Comment by Muffexx** [comment]
Yes, a custom encoding would be very helpful.

When using 7-Zip with default parameters it won't encode in UTF-8 by default (at least on my system).
Then when unzipping, UTF-8 is used by SharpZipLib since my local codepage won't support the special characters.
To resolve my issue I have three options:

- encode via 7-Zip and set codepage 850
- encode via 7-Zip and set UTF-8 to "on"
- decode via SharpZipLib using a custom codepage (which I did via reflection)

Maybe there is a smarter approach.
