### ISSUE TITLE
(413) The request body is too large and exceeds the maximum permissible limit- Zip streaming to blob storage using ICSharpCode.SharpZipLib

### ISSUE THREAD

**Issue by ashkansirous** [icsharpcode/SharpZipLib#276]
### Steps to reproduce
1. Try puting more than 50,000 small files into a zip file on Azure blob storage using SharpZipLib

### Expected behavior
It should be able to write them on the fly az the total size of 50k of small files won't be that big. maybe several haundred MBs or a couple of GBs

### Actual behavior
It breaks at 50,000th files. It seems that every time I run PutNewEntry, it actually do something to the stream that make Azure use a new block and thus we hit the 50,000 block limit.

### Version of SharpZipLib
1.0.0
### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ x] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

### The complete story

I need to create a big zip file on my azure blob storage using my files on another container on the same Azure blob storage. Number of files can be hundreds of thousands and it can be several gigabytes of data.

Using WindowsAzure.Storage and SharpZipLib I wrote the code below:

```
 <package id="WindowsAzure.Storage" version="7.2.1" targetFramework="net461" />
  <package id="SharpZipLib" version="1.0.0" targetFramework="net461" />
```

-

```
CloudBlobContainer backupContainer = _myservice.GetBlobBackupContainer();
tempZipBlockBlob = container.GetBlockBlobReference(Path.Combine(MyBlobStoragePaths.BackupsTempFolder, backupId));
tempZipBlockBlob.DeleteIfExists();
using (CloudBlobStream blobStream = tempZipBlockBlob.OpenWrite(AccessCondition.GenerateIfNotExistsCondition()))
{
  using (var zipOutputStream = new ZipOutputStream(blobStream))
  {
            zipOutputStream.SetLevel(0);
            foreach (CloudBlockBlob cloudBlob in snapshots)
            {
                string blobName = Path.Combine(prefix, cloudBlob.Name.Replace('/', '\\'));
                try
                {
                    var buffer = new byte[4096];

                    using (Stream readStream = cloudBlob.OpenRead())
                    {
                        var zipEntry = new    ZipEntry(ZipEntry.CleanName(blobName)) {Size = readStream.Length};
                        zipOutputStream.PutNextEntry(zipEntry);
                        StreamUtils.Copy(readStream, zipOutputStream, buffer);
                     }
                  zipOutputStream.Flush();
                 }
                 catch (Exception e)
                 {
                   Log.Error(e, "CopySnapshotToZipOutputStream failed for   {blobName}.",  blobName);
                   throw;
                  }
              }
  }
}
```
The code works fine in my dev and on test for many containers but it fails for 1.

Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (413) The request body is too large and exceeds the maximum permissible limit.. ---> System.Net.WebException: The remote server returned an error: (413) The request body is too large and exceeds the maximum permissible limit.. [10/17/2018 14:55:11 > 9d4928: INFO] at T Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException(HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase cmd, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Shared\Protocol\HttpResponseParsers.Common.cs:line 50 [10/17/2018 14:55:11 > 9d4928: INFO] at RESTCommand Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.PutBlockImpl(Stream source, string blockId, string contentMD5, AccessCondition accessCondition, BlobRequestOptions options)+(RESTCommand cmd, HttpWebResponse resp, Exception ex, OperationContext ctx) => { } in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 2380 [10/17/2018 14:55:11 > 9d4928: INFO] at void Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse(IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299 [10/17/2018 14:55:11 > 9d4928: INFO] --- End of inner exception stack trace --- [10/17/2018 14:55:11 > 9d4928: INFO] at void Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Flush() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 234 [10/17/2018 14:55:11 > 9d4928: INFO] at void ICSharpCode.SharpZipLib.Zip.Compression.Streams.DeflaterOutputStream.Finish() [10/17/2018 14:55:11 > 9d4928: INFO] at void ICSharpCode.SharpZipLib.Zip.ZipOutputStream.CloseEntry() [10/17/2018 14:55:11 > 9d4928: INFO] at void ICSharpCode.SharpZipLib.Zip.ZipOutputStream.PutNextEntry(ZipEntry entry)

The size on the blob is not a problem since it is only ~3 GB in total. The problem seems to be having more than 50000 blocks on the blob as if we are creating a new block everytime we run         zipOutputStream.PutNextEntry(zipEntry);

**Comment by piksel** [comment]
I'm sorry, but I don't think I can help with this issue. It is way to specific and relates to using a third-party service as the underlying stream. If you do find a solution for the problem I would be happy to accept a PR, though.
