### ISSUE TITLE
ZipStrings is static. Can't use different encodings for different zip files

### ISSUE THREAD

**Issue by EvilBeaver** [icsharpcode/SharpZipLib#279]
This is proposal.

Today, ZipStrings class is static and encoding properties are static. This means I can't use different encodings for different ZipFile instances. In a multithreading environment it's very hard to use value that was set globally somewhere.

## Proposal 

use instance-wide encoding for a ZipFile class. Encoding must be an instance property of a ZipFile, not a global one.

### Expected behavior

* It's possible to have 2 instances of ZipFile which can read 2 files with different encodings inside.
* Static dependency from ZipStrings.CodePage is removed

**Comment by piksel** [comment]
A different PR would be better, this might be a larger overhaul with additional tests etc.

I totally agree and am not found of the static ZipStrings approach for the above reasons.
