### ISSUE TITLE
After decompressing Chinese compression, the file name is garbled.

### ISSUE THREAD

**Issue by Feaskye** [icsharpcode/SharpZipLib#288]
### Steps to reproduce
 why？ what should I use it？ 
1.ZipFile zf = new ZipFile(archiveFilenameIn);
2.foreach (ZipEntry zipEntry in zf)
  {
   String entryFileName = zipEntry.Name;//this Name show garbled？
   //eg:��������.xls     I set IsUnicodeText=true，but it is not useful
  //what can I do？ I hope you help me，thanks
  }

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Version of SharpZipLib
 version 1.0.0

### Obtained from (only keep the relevant lines)
- Compiled from source, commit: _______
- Downloaded from GitHub
- Package installed using NuGet

**Comment by piksel** [comment]
The file you are trying to decompress does not have the Unicode bit set. Overriding this by using `ZipStrings.UseUnicode = true;` is merged and will be coming the next release.

**Comment by Feaskye** [comment]
Nice ! Thank you very much !
