### ISSUE TITLE
Extend VB samples

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#29]
[SD-1195](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1195), originally created on 11/6/2006 03:19:07 by John Reilly

The Vb samples are not as full as the C# ones and cause a fair bit of
traffic in the forum.  Extending these would help greatly.

**Comment by piksel** [comment]
I don't think we have had a single VB-related issue in Github since I started maintaining this repo. More VB examples would of course be welcomed, but I am closing this since it's probably not going to happen.
