### ISSUE TITLE
Tar file modification times: nanoseond resolution and restore

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#30]
[SD-1310](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1310), originally created on 2/9/2007 00:11:51 by John Reilly

What kind of effort would be required to implement nanosecond resolution
for file modification times for the Tar format?  This was implemented in
GNU Tar 1.16, and I would find support for this in SharpZipLib to be
very useful.

 From Thread 15102 in forum.

 Related issue:
 Add a  TarArchive.RestoreDateTimeOnExtract  bool property similar to
that in FastZip.
 Currently the ExtractContents method results in created files having
the date/time of extraction. Perhaps also a flag to allow setting
Creation time and/or Modification time. 

 Forum [thread
11551](http://community.sharpdevelop.net/forums/t/11551.aspx) and thread
[15930](http://community.sharpdevelop.net/forums/t/15930.aspx).

**Comment by piksel** [comment]
This would need a new issue with an updated use case. It didn't get implemented in 7 years in this state.
