### ISSUE TITLE
Blob stored in Azure with AES password protected

### ISSUE THREAD

**Issue by eldridgemartinez** [icsharpcode/SharpZipLib#303]
### Steps to reproduce
1. Create a zip in Winrar WITH a password. I'm using Winrar so that the default password in AES instead of the ZipLegacy. Make sure one of the files inside the zip is at least 17KB. 
2. Upload the file to Azure as BlockBlob
3. Create a sample program that uses 'Microsoft.WindowsAzure.Storage' SDK and calls the OpenRead() method passed to the new ZipFile() constructor.  
  Important Note: Set the StreamMinimumReadSizeInBytes property of CloudBlockBlob object to 16384 (or any value less than one of the files inside your zip)

An example code (also in [ZipTest.zip](https://github.com/icsharpcode/SharpZipLib/files/2754376/ZipTest.zip) the complete project):
```cs
using ICSharpCode.SharpZipLib.Core;
using ICSharpCode.SharpZipLib.Zip;
using Microsoft.WindowsAzure.Storage;
using System;
using System.IO;

namespace ZipTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var blobConString = @"<replace-with-your-azure-conn-string>";
            var storageAccount = CloudStorageAccount.Parse(blobConString);
            var myClient = storageAccount.CreateCloudBlobClient();
            var container = myClient.GetContainerReference("test");
            var blockBlob = container.GetBlockBlobReference("TestZip-pass-is-testing.zip");

            // Mininum is 16KB.. This needs to be smaller to one of the files in the
            // zip in order to replicate the issue
            blockBlob.StreamMinimumReadSizeInBytes = 16384;

            var zipFile = new ZipFile(blockBlob.OpenRead())
            {
                Password = "testing"
            };

            var outputFolder = $@"c:\temp\out\{Guid.NewGuid()}";
            WriteToDisk(zipFile, outputFolder);

            Console.WriteLine($"Zip file extracted to {outputFolder}. Press any key to exit.");
            Console.ReadKey();
        }

        private static void WriteToDisk(ZipFile zipFile, string outFolder)
        {
            foreach (ZipEntry zipEntry in zipFile)
            {
                if (!zipEntry.IsFile)
                    continue;

                var fileName = Path.GetFileName(zipEntry.Name);
                var fullZipToPath = Path.Combine(outFolder, fileName);

                var directoryName = Path.GetDirectoryName(fullZipToPath);
                Directory.CreateDirectory(directoryName);

                Console.WriteLine($"Extracting file '{zipEntry.Name}'");

                using (var stream = zipFile.GetInputStream(zipEntry))
                {
                    byte[] buffer = new byte[4096];
                    using (FileStream streamWriter = File.Create(fullZipToPath))
                    {
                        StreamUtils.Copy(stream, streamWriter, buffer);
                    }
                }
            }
        }
    }
}
```

### Expected behavior
Should be able to extract the AES protected zip file. 

### Actual behavior
SharpZipLib throws ```System.Exception: 'AES Authentication Code does not match. This is a super-CRC check on the data in the file after compression and encryption. ``` 

The potential fix I can see is inside the "Potential Fix" block below. I make another read from stream if the returned bytes is less than what I expect. I'm aware of the end-of-file scenario and I think its not breaking.
 
File: ZipFile.cs
Class: PartialInputStream
Method: public override int Read(byte[] buffer, int offset, int count)

```cs
public override int Read(byte[] buffer, int offset, int count)
{
    lock (baseStream_)
    {
        if (count > end_ - readPos_)
        {
            count = (int)(end_ - readPos_);
            if (count == 0)
            {
                return 0;
            }
        }
        // Protect against Stream implementations that throw away their buffer on every Seek
        // (for example, Mono FileStream)
        if (baseStream_.Position != readPos_)
        {
            baseStream_.Seek(readPos_, SeekOrigin.Begin);
        }
        int readCount = baseStream_.Read(buffer, offset, count);


        // ***** Potential Fix Start
        // Azure CloudBlockBlob SDK Stream implementation is: Returns only the bytes in its buffer and does not fetch from remote until its buffer is empty.
        // This observation causes an issue in above baseStream_.Read call because the buffer is only filled partially
        // To fix: read the next bytes 
        int correctReadCount = readCount;
        if (readCount > 0 && readCount < count)
        {
            // save to readPos
            readPos_ += readCount;

            // get the remaining bytes
            readCount = baseStream_.Read(buffer, offset + readCount, count - readCount);
            
            // set correct count
            correctReadCount += readCount;						
        }
        // ***** Potential Fix End

        if (readCount > 0)
        {
            readPos_ += readCount;
        }

        return correctReadCount;
    }
}
```

### Version of SharpZipLib
Version 1.1.0 - which includes the fixed for the AES256 from PR260

### Obtained from (only keep the relevant lines)
- Downloaded from GitHub

**Comment by piksel** [comment]
As per [System.IO.Stream.Read](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=netframework-4.7.2#System_IO_Stream_Read_System_Byte___System_Int32_System_Int32_) (Remarks section), a stream is allowed to return less than the requested amount of bytes. It should only be considered EndOfStream when it returns 0 byte.
So an additional read attempt should probably be added.

**Comment by eldridgemartinez** [comment]
> Would something like
> 
> [Numpsy@c328b3c](https://github.com/Numpsy/SharpZipLib/commit/c328b3cf73ef2127df9e7cc257ce01d96569b116)
> [Numpsy@830f42a](https://github.com/Numpsy/SharpZipLib/commit/830f42ae9b6b2b27c50fd4d3fded241264aaf046)
> 
> be a reasonable approach?
> I tried creating a unit test reading an encrypted zip file from a stream whose read function only returns one byte at once, and then tweaked a few places that read from the stream such that the test passes.
> 
@Numpsy this is a better approach. Hope to see a new nuget release soon. Thank you.
