### ISSUE TITLE
how to extract zip file with Russian characters???

### ISSUE THREAD

**Issue by antonlynnik** [icsharpcode/SharpZipLib#307]
### Steps to reproduce
i have a zip file with russian file name inside

### Expected behavior
FastZip fz = new FastZip();
fz.ExtractZip(zipFile, extractPath, null);

### Actual behavior
the file name is corrupted by "hieroglyphs"

### Version of SharpZipLib
1.1.0.145

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
Either the file contains UTF-8 encoded file names and the file does not have the Unicode bit set, or (less likely) it is encoded in 1251 and DOES have the bit set.
You can override this behaviour by explicitly setting the encoding:
```cs
ZipStrings.UseUnicode = true;
```

**Comment by antonlynnik** [comment]
It did not help.
I have attached the file.
Could you see what you can do?
https://drive.google.com/open?id=1oK4fEb31bKKudQ1FAIeAuZQrgx8N0-Hc

**Comment by piksel** [comment]
No, it seems like it is encoded using CodePage 1152. Unfortunately, I don't have that codepage in my windows installation (so even if I try to use it, it goes back to the fallback codepage, which also outputs gibberish).
You could try doing this:
```cs
ZipStrings.CodePage = 1152;
```

**Comment by antonlynnik** [comment]
many thanks 
ZipStrings.CodePage = 866;
helpd me.

**Comment by piksel** [comment]
Aw, I just found it too. Haha.

**Comment by antonlynnik** [comment]
may i ask one more question?)
archive have modifydate = 18 jan 2019
when i extract, file from arc receive modifedate = NOW
how to extract with original modifydate?

**Comment by piksel** [comment]
```cs
fz.RestoreDateTimeOnExtract = true;
```

**Comment by antonlynnik** [comment]
and one more time
many thanks
perfect!!!
