### ISSUE TITLE
FastZip exception when attempting to add locked file not well handled

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#31]
[SD-1369](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1369), originally created on 7/27/2007 13:17:35 by John Reilly

FastZip::AddFileContents can throw an exception at the using (FileStream
stream = File.OpenRead(name)) if the file is locked by another process. 
The exception is not caught until ZipOutputStream::CloseEntry() ~ line
483 where it checks the size.  Returns an error "size was 0 but I
expected dddddd".  This leaves the user with little indication of the
problem.

..

The above is likely already fixed, but a new enhancement is needed.

Add a new property to allow the adding of files that re open by another
for writing. This would change the FileShare parameter in File.Open to
ReadWrite.

Also update the NUnit test to set the property.

Forum thread
[community.sharpdevelop.net/forums/t/16183.aspx](http://community.sharpdevelop.net/forums/t/16183.aspx)

---

**Comment from John Reilly on 7/27/2007 13:20:04**:
Originated from forum post 18110.

Presumably using events would help to pick up on this somewhat more
elegantly.

---

**Comment from David Pierson on 2/19/2010 04:59:10**:
This may be related to this issue in this post ...

[http://community.sharpdevelop.net/forums/t/10314.aspx](http://community.sharpdevelop.net/forums/t/10314.aspx)

**Comment by piksel** [comment]
Not sure when, but the problem described has been fixed (probably by @jfreilly himself). It now opens the stream in a try/catch clause and triggers an event if it fails that let's the consumer handle the error.
