### ISSUE TITLE
Zip64 cannot be delete when it has more than one file

### ISSUE THREAD

**Issue by zhuxb711** [icsharpcode/SharpZipLib#310]
### Steps to reproduce
1.Create a zip64 which has multi file
2.BeginUpdate()
3.Delete one of the file ( Delete(ZipEntry entry) )
4.CommitUpdate()

### Expected behavior
Without Error

### Actual behavior
ZipException: Extra data extended Zip64 information length is invalid

### Version of SharpZipLib
Ver. 1.1.0
### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by Numpsy** [comment]
Same as #59?

Would something like @ https://github.com/Numpsy/SharpZipLib/commit/786785374fd3c9a5df12d8ff196c5f38ab8fb953 help? (looks like WriteCentralDirectoryHeader currently checks IsZip64Forced when deciding to write -1 to the base size fields but not when writing the extra data, so the length doesn't get written).
That seems anough to get the new test @ https://github.com/Numpsy/SharpZipLib/commit/5706bff4550104a7e28f145d13c62f4499231c1b passing at any rate,

**Comment by Numpsy** [comment]
PR sent - https://github.com/icsharpcode/SharpZipLib/pull/314

**Comment by piksel** [comment]
@zhuxb711 Would you mind testing if this solves your issue by trying the nuget packages from here:
https://ci.appveyor.com/project/icsharpcode/sharpziplib/builds/21919853/job/ikxom0i3vlb0m3al/artifacts
