### ISSUE TITLE
Zip files with BZip2 compression?

### ISSUE THREAD

**Issue by Numpsy** [icsharpcode/SharpZipLib#315]
Is there any official position on supporting Zip files that use BZip2 compression?

I tried wiring it up out of interest @ 

https://github.com/Numpsy/SharpZipLib/commit/c88def5888bea3062b4d499d09dc8e6278f832c3 https://github.com/Numpsy/SharpZipLib/commit/0ece0c9219a9053bff033d92f56d846f566ed9d2

and it does basically seem to work with some interop with 7-Zip (though reading AES encrypted files doesn't work due to issues reading bytes from the AES stream).

Is this something that would be of interest for official support?

**Comment by piksel** [comment]
I have neither encountered zipfiles with bz2 compression, nor seen any requests for us to support it. But since it seems like we basically already have all the foundation needed, it shouldn't add much of a support cost to maintain.

I'm guessing you had some use for this, since you found the incorrect Enum value and now this?

**Comment by Numpsy** [comment]
I work on a project that uses SharpZipLib to access zip files and process their contents (though that only needs to decompress rather than create), and I was thinking that BZip2 support might hypothetically be useful (I say hypothetically, because although 7-Zip can create such files, I don't know how much they really show up in the wild).

In any case, looks like it might be doable just using the existing BZip2 support, so worth a look.

**Comment by Numpsy** [comment]
I guess that #23 would be of more 'real' use, though more work as well.

**Comment by Numpsy** [comment]
I'll close this now that #355 is merged - can open seperate issues if any bugs are found in it
