### ISSUE TITLE
ZipFile.TestArchive seems to always return false for AES encrypted zips

### ISSUE THREAD

**Issue by Numpsy** [icsharpcode/SharpZipLib#317]
### Steps to reproduce

call

```
var zipFile = new ZipFile(@"AES.zip")
{
    Password = password
};

Assert.That(zipFile.TestArchive(false), Is.True, "Zip file should be valid");
```

On an AES encrypted zip file (happens with files generated with both SharpZipLib and 7-Zip).

### Expected behavior
I assume that the test should pass for a valid AES archive?

### Actual behavior
TestArchive returns false.

Looks like it fails @ https://github.com/icsharpcode/SharpZipLib/blob/master/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L1207 because the flags are different (localFlags just has the encrypted bit set, whereas entry.Flags has the StrongEncryption bit set I think).

If it gets past that, it will also fail on the compression method comparison, as entry.CompressionMethod is the compression format (Deflate), but compressionMethod is 99 (WinZipAES).

### Version of SharpZipLib
1.1.0

### Obtained from (only keep the relevant lines)
- Compiled from source, commit: 25ee644

**Comment by Numpsy** [comment]
Actually, looking at the encryption bits of the spec, is it correct to set the strong encryption flag @ 

https://github.com/icsharpcode/SharpZipLib/blob/25ee6440f444aa326ee8f0b98e6223296f35fa6d/src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs#L1137

?
(Seems that is supposed to be for a different encryption approach that the Winzip one)

**Comment by piksel** [comment]
Yes, the only thing that the [AE-1/2](https://www.winzip.com/win/en/aes_info.html) mentions are that the encrypted flag should be set to 1 (bit zero). Strong encryption is what pkzip generally uses to refer to it's (stronger) encryption, so this seems to imply that it should not be set. The APPNOTE only specifies that 
> Strong encryption.  If this bit is set, you MUST set the version needed to extract value to at least 50 and you MUST also set bit 0.  If AES encryption is used, the version needed to extract value MUST be at least 51

**Comment by Numpsy** [comment]
The logic in CreateAndInitDecryptionStream in Zipfile is currently checking for StrongEncryption being set to decide which crypto approach should be used, which seems wrong if StrongEncryption != AE-X, and only the latter is supported?

The check @ 
https://github.com/icsharpcode/SharpZipLib/blob/25ee6440f444aa326ee8f0b98e6223296f35fa6d/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L3561

is also checking if the version is equal to 51, when the line you quote above says 'at least 51' and the linked Winzip spec doesn't specify any explicit version - not sure if that is correct?

Possibly the logic should be keyed off the AE-x flags in the entry rather than the other bits?

**Comment by piksel** [comment]
Indeed, it fails with [Central header/local header compression method mismatch](https://archivediagstore.z16.web.core.windows.net/reports/hhVmFW-lb0-jVU8i4WDsyg.html). I am taking a look at this.

**Comment by piksel** [comment]
It should just be a case of changing the check to compare `entry.CompressionMethodForHeader` instead of `entry.CompressionHeader` at [src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L1207](https://github.com/icsharpcode/SharpZipLib/blob/master/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L1207)

**Comment by Numpsy** [comment]
#353 does that

**Comment by piksel** [comment]
Yeah, not sure how I missed that.

**Comment by Numpsy** [comment]
Something I noticed while looking at something else (partly related to this issue, partly related to #460):
Is the check at: 

https://github.com/icsharpcode/SharpZipLib/blob/b6ab9f5da988dbcc87b54def87e7340c19358844/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L1292

correct when considering AES encrypted directory entries (whose size might be larger than ZipCrypto encrypted directories)? (I'm not sure what the +2 in the calculation is for)

**Comment by Numpsy** [comment]
Should that comparison in my previous comment perhaps be using the EncryptionOverheadSize property added in #460 rather than CryptoHeaderSize?
