### ISSUE TITLE
Tar truncates the first character of filename when using CreateEntryFromFile

### ISSUE THREAD

**Issue by iUnknwn** [icsharpcode/SharpZipLib#334]
### Steps to reproduce
1. Create an output Tar Archive
2. Set the root path to an empty string (this happens when our code receives a relative path, so `rootPath = GetDirectoryName(targetFile)`).
3. Call CreateFileFromEntry using the filename targetFile - the tarEntry has the correct name property.
4. Call WriteEntry.
5. Check the generated output - the filename in the generated archive is missing the leading character. 

### Expected behavior
The filename in the archive should be the same as what is written.

### Actual behavior
The filename in the archive is missing the leading character.

### Version of SharpZipLib
1.1.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by Numpsy** [comment]
I haven't tested it, but maybe the check @ 

https://github.com/icsharpcode/SharpZipLib/blob/afcccb09488ac2cd0ed701b52b17a5959dee5a41/src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs#L787

should be checking if rootPath is empty rather than just null?

**Comment by iUnknwn** [comment]
Yep - that seems like the problem. I just did a quick test, and switching that for String.IsNullOrEmpty seemed to fix the problem. 

I opened a pull request with with the small change.
