### ISSUE TITLE
ZipOutputStream when size is unknown

### ISSUE THREAD

**Issue by KimikoMuffin** [icsharpcode/SharpZipLib#339]
Is there any way to specify that the file size is unknown at the time `ZipOutputStream.PutNextEntry()` is called, _without_ having the stream force it to Zip64?

**Comment by davidpierson** [comment]
Yes, just specify
zipOutputStream.UseZip64 = UseZip64.Off;
when creating the ZipEntry.

There are code samples in the wiki at https://github.com/icsharpcode/SharpZipLib/wiki/Zip-Samples
that can be useful.

**Comment by KimikoMuffin** [comment]
Ah, awesome, that makes sense!
