### ISSUE TITLE
Tar formats for files over 8GB such as Posix and Pax

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#34]
[SD-1647](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1647), originally created on 2/19/2010 05:02:23 by David Pierson

Current code matches the traditional tar format and limits the size of
an individual file being added to a tar to 8GB. (However, it can read up
to 64GB). 

 There are several format extensions that skirt this, such as GNU, PAX
and POSIX.

 GNU tar sets a bit in MSB of size field to specify that the content
should be interpreted as binary field instead of octal digits. 
 Pax on the other hand uses a type flag to specify some tar header field
has been extended by the next immediate block where for example,
filesize is written as a plain ascii string - the format is of a
"key=value" with other fields such as name being able to be extended
similarly. 

[http://community.sharpdevelop.net/forums/t/141.aspx](http://community.sharpdevelop.net/forums/t/141.aspx)

---

**Comment from David Pierson on 7/27/2012 08:54:18**:
Email received from Ivan Peev 26 Apr 2012 with code to update TarHeader
to extract Tar files over 8GB using binary instead of ascii.

---

**Comment from David Pierson on 11/8/2012 06:20:10**:
Implemented the binary field approach in August 2012 in this commit

[https://github.com/icsharpcode/SharpZipLib/commit/a74a38553bdcc870d9f065472414c569cd037f41](https://github.com/icsharpcode/SharpZipLib/commit/a74a38553bdcc870d9f065472414c569cd037f41)
 but not the PAX key=value.

[](https://github.com/icsharpcode/SharpZipLib/commit/a74a38553bdcc870d9f065472414c569cd037f41)

**Comment by piksel** [comment]
Closing this as the thing not implemented is handling of the POSIX.1-2001 extended headers (AFAIKT). This might be it's own issue, but is probably better suited for individual tickets per feature.
