### ISSUE TITLE
HostSystem is on ZipEntry is not respected

### ISSUE THREAD

**Issue by macsux** [icsharpcode/SharpZipLib#340]
### Steps to reproduce
1. Start with sample ZIP application https://github.com/icsharpcode/SharpZipLib/tree/master/samples/ICSharpCode.SharpZipLib.Samples/cs/CreateZipFile
2. Modify to set HostSystem = 3 on ZipEntry object

Also setting ExtraData is not saved as well...

Sample LinqPad script here: http://share.linqpad.net/fungmm.linq
### Expected behavior
Zip file is created with HostSystem set to *unx
Need to set the OS to be able to attach file permission information properly.
### Actual behavior
HostSystem flag is not respected

### Version of SharpZipLib
1.1

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by Numpsy** [comment]
related to / same as #325 ? (it mentions the setting of HostSystem being broken)

**Comment by macsux** [comment]
I've confirmed that the open PR fixes the issue I'm experiencing. Would be great if it can be merged a new pre-release nuget package minted, right now I've compiled myself and posted it here: https://www.myget.org/F/macsux/api/v3/index.json

**Comment by Numpsy** [comment]
Fixed by #325 / #350 ?

**Comment by macsux** [comment]
325 fixes this issue

**Comment by Numpsy** [comment]
The changes should be included in the new 1.2.0 release.
