### ISSUE TITLE
Decompressing zlib stream compressed by Cairo

### ISSUE THREAD

**Issue by GuardianCherubimJohn** [icsharpcode/SharpZipLib#344]
### Steps to reproduce
Export a PDF from InkScape, this will have its filter set to FlateDecode on streams within objects.
Try to decompress through ICSharpCode.SharpZipLib.Zip.ZipInputStream via NuGet.

Note: I looked at Cairo which is what InkScape uses and saw that it's just using zlib, but it doesn't seem to reproduce the header that SharpZipLib expects. 

( See: https://github.com/freedesktop/cairo/blob/61122127943dcaff41501e1b06df2a852c576e9b/src/cairo-deflate-stream.c )

### Expected behavior
Decompression of the object streams within the file.

### Actual behavior
Wrong local header exception. 

Note: If I manually prepend the binary data from the stream object within the object in the PDF with List<byte> byteList = new List<byte>() { 0x50, 0x4B, 0x03, 0x04 }; it will give an OutOfRangeException on versionRequired that's supposed to be passed to ZipEntry, expecting perhaps some more header information. 

### Version of SharpZipLib
1.1.0 by NuGet in Visual Studio for Mac

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by GuardianCherubimJohn** [comment]
Here's a solution. I found this here and it works here in 2019, I'd say this should be added to the doc samples when you can please, it would be very helpful for those trying to parse PDFs, as they have FlateDecode streams:

http://community.sharpdevelop.net/forums/t/1009.aspx

**Comment by GuardianCherubimJohn** [comment]
I just also wanted to share my love, care, and appreciation to you the developers of SharpZipLib, because it's really a life saver for those of us who don't understand compression or encryption all that well. Just sharing my thanks, and God bless.

**Comment by piksel** [comment]
Yeah, `ZipInputStream` expect a zip file header, which would not be present in a raw deflated stream. It would be helpful if the fact that in PDF, the "FlateDecode" just means "Inflate" (and that `InflaterInputStream` could be used to decompress it) was mentioned in the documentation somewhere.
