### ISSUE TITLE
Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'

### ISSUE THREAD

**Issue by Evangelink** [icsharpcode/SharpZipLib#345]
Hi there,

I have a WPF application using this library to create some zip file. I have recently updated the dependency from `0.86.0.518` to `1.1.0.145` (NuGet package) and I am starting to receive the following error: 

`Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Using fuslogvw, I get the following trace (anonymized):
```
System.IO.FileLoadException was unhandled
  FileName=ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
 (Fully-specified)
LOG: Appbase = file:///<PATH_TO_DEBUG_FOLDER>
LOG: Initial PrivatePath = NULL
Calling assembly : <MY_PROJECT>, Version=7.1.4.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: <PATH_TO_DEBUG_FOLDER>\<MY_PROJECT>.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
LOG: Attempting download of new URL file:///<PATH_TO_DEBUG_FOLDER>/ICSharpCode.SharpZipLib.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

  HResult=-2146234304
  Message=Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=<MY_PROJECT>
  StackTrace:
       at <MY_CLASS.cs>.Dispose(Boolean disposing)
       at <MY_CLASS.cs>.Finalize() in <PATH_TO_MY_CLASS.cs>:line 103
  InnerException: 

```

I have tried to remove the binding redirect and to change its value but nothing seems to be working.

Any idea of what could be wrong?

### Version of SharpZipLib
1.1.0.145

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
This definitely sounds like a binding problem. What version of .NET are you using? Perhaps an older version is in your GAC?

**Comment by Evangelink** [comment]
I have checked the old and new GAC and couldn't find the dll. 

What's strange is that when I create a new WPF app and add a reference to the package v1.1.0.145 I don't have an error. I only have it when migrating my current app...

As you have seen it does detect the app.config with the binding redirect, which redirect all versions between 0.0.0.0 and 1.1.0.145 to 1.1.0.145 and it still fails with some error mismatch.

**Comment by piksel** [comment]
Yes, I've had problems like this before with package linking (not related to SharpZipLib). Unfortunatly I think it's outside the libraries scope and somehow related to your environment. Closing the issue.

**Comment by Evangelink** [comment]
I finally managed to find the root cause of the issue and as you guessed this was linked to the `NPOI` package which depend on a specific version of this tool and somehow didn't picked up correctly the binding redirect. Anyway updating the dependency version fixed the issue,

Thanks!

**Comment by piksel** [comment]
Thanks for the update! Im glad you got it resolved.
