### ISSUE TITLE
Detect Codepage of zip file created on previous versions of SharpZipLib

### ISSUE THREAD

**Issue by artem-voropaev** [icsharpcode/SharpZipLib#348]
I start using SharpZipLib version 1.1.0, previosly i used 0.86.0. ZipStrings.CodePage is UTF-8 now. Is there a way to detect Codepage of zip file created on previous versions of SharpZipLib or created by another programs?

**Comment by piksel** [comment]
Well, detection is your only choice here I'm afraid. The choices for encoding is basically:
- UTF-8
- Whatever 8-bit charset the OS the file was created on was using  

If you know the origin of the file you can set the code page like this: 
```cs
ZipStrings.CodePage = 1252; // ISO-8859-1
```
