### ISSUE TITLE
Zip64 Central Directory skipped if not explicitly needed

### ISSUE THREAD

**Issue by piksel** [icsharpcode/SharpZipLib#357]
Other libraries handle Zip64 differently than SharpZipLib. This leads to issues when the library doesn't react the same way to non-compliant archives.  
  
The library should instead always attempt to find a Zip64 signature.

**Comment by Numpsy** [comment]
Related to #291 as well?

**Comment by Numpsy** [comment]
Should be fixed by #363 ?

**Comment by piksel** [comment]
Yes
