### ISSUE TITLE
TestArchive hangs on specific zip/password combination

### ISSUE THREAD

**Issue by marcsison81** [icsharpcode/SharpZipLib#358]
### Steps to reproduce
ZipFile zf = null;
FileStream fs = File.OpenRead("CSC933M_Homework1.zip"); //attached
zf = new ZipFile(fs);
zf.Password = "BSC9";
zf.TestArchive(true);
zf.Close();

### Expected behavior
Should return false since the password is invalid

### Actual behavior
Hangs

### Version of SharpZipLib
1.1.0
### Obtained from (only keep the relevant lines)
[CSC933M_Homework1.zip](https://github.com/icsharpcode/SharpZipLib/files/3304980/CSC933M_Homework1.zip)

- Package installed using NuGet

**Comment by Numpsy** [comment]
TestArchive returns false with the current code.
Just going from the exception it gets inside TestArchive, the hang might have been fixed by #316.

**Comment by piksel** [comment]
Yeah, that might be the case. The fact that it allowed an instruction that did not move the input cursor was a source of many "hangs".
