### ISSUE TITLE
Add Serializable attribute to ZipException

### ISSUE THREAD

**Issue by fatimagullmadni** [icsharpcode/SharpZipLib#365]
### Steps to reproduce
1. Use WCF service 
2. Call some Zip functionality where exception is triggered

### Expected behavior
the exception is serializable so it does not clash with WCF 

### Actual behavior
exception=System.Runtime.Serialization.SerializationException: Type 'ICSharpCode.SharpZipLib.Zip.ZipException' in Assembly 'ICSharpCode.SharpZipLib, Version=1.1.0.145, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' is not marked as serializable.

### Version of SharpZipLib
1.1.0.145
### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
I think this was skipped due to .NET Standard 1 not supporting it. But since we are now targeting .NET Standard 2, inclusion should no longer be an issue. A PR would be welcomed!

**Comment by fatimagullmadni** [comment]
Thanks for reply, Is there a ETA for the support ?

**Comment by piksel** [comment]
No, there is currently no ongoing effort to support this.

**Comment by Numpsy** [comment]
There are several exception types defined in the library - if this was going to be done, would it be worth looking over all of them rather than just ZipException?

**Comment by piksel** [comment]
Yeah, but it should just be a matter of adding `[Serializable]` in the declaration.

**Comment by Numpsy** [comment]
Ok (wasn't sure if they'd need the SerializationInfo constructor overloads adding as well.)

**Comment by Numpsy** [comment]
@fatimagullmadni Do the changes in the 1.2.0 release work for your use case?
