### ISSUE TITLE
.NET Standard 1.x support

### ISSUE THREAD

**Issue by NightOwl888** [icsharpcode/SharpZipLib#368]
I read #206 already, and it seems you could support .NET Standard 1.3 with no changes. Why did you only add support for .NET Standard 2.0?

We depend on this library and support .NET Standard 1.6, but had to go with an "unofficial" copy [SharpZipLib.NetStandard](https://www.nuget.org/packages/SharpZipLib.NETStandard/). However, that library is not strong named and we have recently added strong naming. So, now we are stuck either releasing yet another clone, or getting you to support .NET Standard 1.x.

**Comment by piksel** [comment]
I think you mean #106? The reason for 2.x had to do with the new Streams API that we rely on (see [System.IO.Stream.Close()](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.close?view=netstandard-2.0))

Why are you supporting 1.6? There are [hardly any benefits support-wise](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). For older frameworks we support `net45` which also contains the updated Streams API.

**Comment by NightOwl888** [comment]
We are supporting 1.6 primarily for .NET Core 1.x support. We already target `net45` and `netstandard2.0`, but neither of them support it.

Okay, so maybe you can't port the latest version to .NET Standard 1.x, what about doing an update to an older version to support it? We don't need the latest features, we just need a way to support `bzip2` and the version that we started with, `0.86.0` works fine for our purposes.

BTW - the top 2 projects on NuGet are NUnit and NewtonSoft.Json and both of them support .NET Standard 1.x, along with most of the other projects on the first page.

**Comment by piksel** [comment]
I see, we have no plans to add support for 1.x unfortunately.   
And re-releasing an older version for netstandard1.6 would add even more support overhead. We have intentionally limited the scope to ns2 and net45.

**Comment by Numpsy** [comment]
I suppose an older target would also conflict with #369, unless the extra bits were conditionally included.

**Comment by NightOwl888** [comment]
Thanks for closing this. Actually, we have already dropped support for .NET Standard 1.x because it became too difficult to support. So this problem has resolved itself.
