### ISSUE TITLE
IndexOutOfRange exception in DeflaterHuffman.BitReverse

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#37]
[SD-1653](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1653), originally created on 3/1/2010 23:59:36 by David Pierson

IndexOutOfRange exception in DeflaterHuffman.BitReverse

 This has been observed in gzip files that were sent via FTP as text
instead of binary. 

 Sample code to detect the corruption of the Huffman tree during the
deflate has been posted. This code is common to both zip and gzip. 

 See
[community.sharpdevelop.net/forums/t/10748.aspx](http://community.sharpdevelop.net/forums/t/10748.aspx)
 for full code.

**Comment by piksel** [comment]
This could be fixed by adding a check for
```cs
if(i > ushort.MaxValue)
{
    throw new SharpZipBaseException("Invalid tree bit length")
}
```
before updating the table (currently on line 134 in InflaterHuffmanTree.cs). But since this is essentially just changing what exception is thrown when bad input data is being decompressed, I am closing this in favor of keeping the issue count down.
