### ISSUE TITLE
FastZip.CreateZip() , filter "*.o" will show all files ,filter ".so" will show "*.*so*",it's bad

### ISSUE THREAD

**Issue by hygyh** [icsharpcode/SharpZipLib#375]
### Expected behavior
1.the directory has files,ex:xxx.o,xxx.so,xx.soc,xx.oso
2.aFileFiter = ".so" 
3.new FastZip().CreateZip(aZipedFileName, aFilePath, true, aFileFiter, aDirectoryFiter);
4.result will show xx.so ,xx.soc ,xx.oso

**Comment by Numpsy** [comment]
I think those filters are supposed to be regular expressions, so those cases might be  "anything that includes 'o'" and "anything that includes 'so'"?

(/regex knowledge is extremely basic)

**Comment by piksel** [comment]
Indeed!

https://regex101.com/r/0dG0vG/1

**Comment by piksel** [comment]
Closing this as it seems to have been answered.
