### ISSUE TITLE
Pre-compiled binary download on website downloads a copy of the website

### ISSUE THREAD

**Issue by jgscherber** [icsharpcode/SharpZipLib#376]
### Steps to reproduce
1. Go to http://icsharpcode.github.io/SharpZipLib/
2. Click 'Download Zip' button
3. Open zip file

### Expected behavior
Zip contains pre-compiled binaries for SharpZipLib

### Actual behavior
Zip contains all the assests for the github.io webpage

### Version of SharpZipLib
N/A

### Obtained from (only keep the relevant lines)
N/A

**Comment by piksel** [comment]
You're right in that it targets the wrong branch, but it's still only the source code that's supposed to be contained in those archives. For the binaries, use the nuget package or the Releases page.

**Comment by piksel** [comment]
The links now correctly downloads the master-branch instead of gh-pages and a bit of clarification has been added for what the links point to.
