### ISSUE TITLE
Invalid password of PHP ZipArchive  ZIPFile

### ISSUE THREAD

**Issue by HanaForward** [icsharpcode/SharpZipLib#377]
### Steps to reproduce
1.PHP Use ZipArchive Create ZIP File and zipfile::setEncryptionName use ZipArchive::EM_AES_256
2.C# Use SharpZipLib to unzip file
3.ICSharpCode.SharpZipLib.Zip.ZipException:“Invalid password”

4.I try to use the password to unzip the file of WinRAR,it was OK
### Actual behavior
“Invalid password”

### Version of SharpZipLib
1.2.0

### Obtained from (only keep the relevant lines)
Package installed using NuGet

**Comment by HanaForward** [comment]
i try to change SharpZipLib to v1.1.0
it tell me ICSharpCode.SharpZipLib Compression method not supported

**Comment by HanaForward** [comment]
Flie : [http://223.94.4.79:91/file/download?code=B40A153C8E05BDD0&id=8609](url)
Password:719ab606212b9710301f

**Comment by Numpsy** [comment]
is that using ZipFile or ZipInputStream to read the file? (ZipInputStream doesn't support AES encrypted files)

**Comment by HanaForward** [comment]
ZipInputStream

**Comment by HanaForward** [comment]
Ok,i to try use ZipFile

**Comment by HanaForward** [comment]
@Numpsy how to use ZipFile?
i dont know how to use it

**Comment by Numpsy** [comment]
There's an example in the wiki @ https://github.com/icsharpcode/SharpZipLib/wiki/Zip-Samples#unpack-a-zip-with-full-control-over-the-operation - you create a ZipFile with the stream containing the data, specify the password, and then either enumerate all the entries or search for a specific one.
