### ISSUE TITLE
Opening a tar.gz file directly from the network makes SharpZipLib to an attempt to access an already disposed Stream

### ISSUE THREAD

**Issue by koide** [icsharpcode/SharpZipLib#379]
I'm downloading a file from an FTP server and unzipping, untarring it on the fly, via the underlying streams. The code looks like this:
```cs
var request = WebRequest.Create("ftp://host/file.tgz");
request.Method = WebRequestMethods.Ftp.DownloadFile;
request.Credentials = new NetworkCredential("user","password");
var response = (FtpWebResponse) await request.GetResponseAsync();
using (var gzStr = new GZipInputStream(response.GetResponseStream()))
{
    gzStr.IsStreamOwner = false;
    var tar = TarArchive.CreateInputTarArchive(gzStr);
    Directory.CreateDirectory(_targetPath);
    tar.IsStreamOwner = false;
    tar.ExtractContents(_targetPath);
}
```
With the current 1.2.0 release (and 1.1.0 and 1.0.0) I get an ObjectDisposedException on the network socket stream, but it happens *after* the whole file has been extracted successfully, so it seems to be yet another exceptional case happening after finishing the file.

In my total ignorance of this code, I've tracked the issue to this line:

https://github.com/icsharpcode/SharpZipLib/blob/ab7f8c5b24c12e0656a9b8e9be55b29aeecc5593/src/ICSharpCode.SharpZipLib/GZip/GzipInputStream.cs#L122

```cs
 catch (Exception ex) when (completedLastBlock && 
    (ex is GZipException || ex is EndOfStreamException)) 
```
and, changing it to 

```cs
catch (Exception ex) when (completedLastBlock && 
    (ex is GZipException || ex is EndOfStreamException ||
     ex is ObjectDisposedException))
```

makes my specific case work successfully. I think that the server ends the connection after the file is downloaded so the stream is not there to be read from anymore.

**Comment by Numpsy** [comment]
The discussion @ https://stackoverflow.com/questions/48829032/streamreader-readline-throwing-disposed-exception-rather-than-returning-null suggests that the FTP response stream closes itself when all the data is read, which could cause issues with stacked streams?

Maybe the multiple-block handling loop in GZipInputStream.Read could check stream.CanRead before trying to read a second block?

**Comment by koide** [comment]
Yup, looks like it's not the server but the FtpWebRequest's FtpDataStream. 

I can confirm that doing

`while (toRead > 0 && inputStream.CanRead) `

instead of 

https://github.com/icsharpcode/SharpZipLib/blob/ab7f8c5b24c12e0656a9b8e9be55b29aeecc5593/src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/InflaterInputStream.cs#L119

Makes it work in my case as well, and looks a saner approach.
