### ISSUE TITLE
Tar extraction disk / directory

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#38]
[SD-1674](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1674), originally created on 6/3/2010 06:12:44 by David Pierson

The TarArchive.ExtractContents(string destinationDirectory) method does
not allow control over extraction in terms of resulting target folders.
See

[community.sharpdevelop.net/forums/t/11321.aspx](http://community.sharpdevelop.net/forums/t/11321.aspx)

 Also, it always strips off the drive spec from the entry name, and
overwrites this with the destinationDirectory spec. If you want to keep
the drive spec in the tar, leaving that blank does not work. See

[community.sharpdevelop.net/forums/t/10875.aspx](http://community.sharpdevelop.net/forums/t/10875.aspx)

 Provide a way to allow some control. 
 Or just suggest via sample a way using the [example in the
11322](http://community.sharpdevelop.net/forums/t/11332.aspx#31005)
thread using TarInputStream.

**Comment by piksel** [comment]
Closing in favor of #338.
