### ISSUE TITLE
"Item with the same key has already been added" extracting tar with duplicate headers

### ISSUE THREAD

**Issue by zarenner** [icsharpcode/SharpZipLib#383]
SharpZipLib fails to process a tar file that contains duplicate extended headers. Other tar programs (e.g. tar, 7-zip, SharpCompress) appear to handle this fine.

### Steps to reproduce
1. Download https://registry.npmjs.org/jasmine-data-provider/-/jasmine-data-provider-2.2.0.tgz
2. gunzip (either with sharpziplib or other software)
3. Attempt to extract, read entries, or list contents of the tar:
```cs
using (var fs = File.OpenRead("c:\\jasmine-data-provider-2.2.0.tar"))
using (TarArchive tar = TarArchive.CreateInputTarArchive(fs))
{
    tar.ListContents();
}
```

### Actual behavior

>An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)   at ICSharpCode.SharpZipLib.Tar.TarExtendedHeaderReader.Read(Byte[] buffer, Int32 length)   at ICSharpCode.SharpZipLib.Tar.TarInputStream.GetNextEntry()   at ICSharpCode.SharpZipLib.Tar.TarArchive.ListContents()

### Version of SharpZipLib
1.2.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by Numpsy** [comment]
I tried debugging it and got:

![image](https://user-images.githubusercontent.com/1178570/64921489-b8c0a580-d7bb-11e9-834b-9f8a0f794b20.png)

Looks like TarExtendedHeaderReader treats every newline as the end of a header, and goes wrong if the value of a header itself contains a newline, rather than just taking the amount of data specified by the length field?

**Comment by piksel** [comment]
Whoa, yeah, this seems to be a lot deeper than simply duplicate headers.

**Comment by piksel** [comment]
Adding the file to the issue in case it gets moved: [jasmine-data-provider-2.2.0.tar.gz](https://github.com/icsharpcode/SharpZipLib/files/3648167/jasmine-data-provider-2.2.0.tar.gz)

**Comment by zarenner** [comment]
Thanks for the analysis into the actual cause @Numpsy.
