### ISSUE TITLE
Nuget Package to Target Native platform

### ISSUE THREAD

**Issue by hoborm** [icsharpcode/SharpZipLib#388]
### Story
Nuget currently not supports adding managed packages into native projects so it returns with an error that the managed package not compatible with the native project. However, adding the package to target "native" thus making nuget think that it works with native projects seems to work. In my case I have a managed CPP/CLI project which wraps some CPP projects for the Managed C# layer, It uses some functions of SharpZipLib, However I'm unable to install it through any of the nuget tools because the SharpZipLib is not targeting native frameworks. Is there any chance you would include a native target framework for these cases when we want to use it in managed CPP projects? I know it's a nuget - CPP support issue, but it's yet to be resolved and adding native target seem to work.

### Steps to reproduce
1. Trying to install SharpZipLib to a managed CPP project
### Expected behavior
Installs

### Actual behavior

> Could not install package 'SharpZipLib 1.2.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Version of SharpZipLib
any
reproduced with 1.2.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet
Similar issue:
https://stackoverflow.com/questions/23571241/nuget-wont-install-entity-framework-into-c-cli-project

**Comment by piksel** [comment]
Sorry, I cannot find any documentation that supports making nuget packages that supports managed c++. I would suggest adding a dummy c# project that can handle the dependencies, and then just hard code a reference to the assembly in the .vcxproj
