### ISSUE TITLE
Change the temp folder location used by CommitUpdate

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#39]
[SD-1742](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1742), originally created on 11/2/2010 03:00:41 by David Pierson

Change the temp folder location used by CommitUpdate

 Mainly for Windows CE / WMP7 with limited storage

 Code provided in thread

[community.sharpdevelop.net/forums/t/9910.aspx](http://community.sharpdevelop.net/forums/t/9910.aspx)

 Also check the Silverlight version on codeplex.

**Comment by piksel** [comment]
Since neither CE or WMP7 is supported anymore I am closing this. If this feature is needed for some other reason, please create a new issue.
