### ISSUE TITLE
Multi-threaded zip extraction

### ISSUE THREAD

**Issue by ZeeNastalski** [icsharpcode/SharpZipLib#397]
Hi,
Is it possible to accomplish multi-threaded extraction of zip archives?
I've tried the approach of extracting individual files on separate threads but there's no benefit to this approach if a zip file contains just one large file.

Is it possible to extract a single entry using multiple threads?

Thanks!
Zee

**Comment by piksel** [comment]
I think it would be possible to inflate multiple blocks in parallel, but it would need some modifications to the internals. It's not something that is currently supported in the library.
