### ISSUE TITLE
How to get the encoded name of a ZipEntry?

### ISSUE THREAD

**Issue by TomGruenewald** [icsharpcode/SharpZipLib#401]
I have a ZIP file with "encoded" ZIP entries.

WinZIP 20.5 Pro shows the original "encoded" filename "_Cercle Ø168.115±0.01 N°2 H30_".
```
Current Location part 1 offset 10155653
Central directory entry PK0102 (4+42): #1
======================================
    part number in which file begins (0000):        1
    relative offset of local header:                0 (0x00000000) bytes
    version made by operating system (00):          MS-DOS, OS/2, NT FAT
    version made by zip software (51):              5.1
    operat. system version needed to extract (00):  MS-DOS, OS/2, NT FAT
    unzip software version needed to extract (20):  2.0
    general purpose bit flag (0x0000) (bit 15..0):  0000.0000 0000.0000
      file security status  (bit 0):                not encrypted
      extended local header (bit 3):                no
    compression method (08):                        deflated
      compression sub-type (deflation):             normal
    file last modified on (0x00004a7b 0x00006a82):  2017-03-27 13:20:04
    32-bit CRC value:                               0x40cd0fcc
    compressed size:                                238608 bytes
    uncompressed size:                              964553 bytes
    length of filename:                             28 characters
    length of extra field:                          0 bytes
    length of file comment:                         0 characters
    internal file attributes:                       0x0000
      apparent file type:                           binary
    external file attributes:                       0x00000020
      non-MSDOS external file attributes:           0x000000
      MS-DOS file attributes (0x20):                arc
    filename: Cercle Ø168.115±0.01 N°2 H30
    original: Cercle 168.115ñ0.01 Nø2 H30
```
But when I read the enty name using **ZipEntry.Name**, all I get is the original name "_Cercle 168.115ñ0.01 Nø2 H30_".

I have also tried to use the class **WindowsNameTransform** without any success. Sorry, I don't get it.

Any help or hint would be appreciated. Thank you.

**Comment by TomGruenewald** [comment]
Note:
The name was correctly read with ICSharpCode.SharpZipLib.dll Version 0.86.0.518. But we have updated to version 1.2.0.246.

**Comment by TomGruenewald** [comment]
Note:
The class **FastZip** shows the same problems.

**Comment by TomGruenewald** [comment]
Setting the codepage to 850 seems to help.

`ZipStrings.CodePage(850)`

I have to check this with none ASCII systems, like Japanese.

**Comment by TomGruenewald** [comment]
We thought we can solve this problem by using

`int codePage = Console.OutputEncoding.CodePage;`

would solve our problem. But this is not the case. On a Japanese system the returned the code page is 932, whereas it is on a German systen 1252, Not the required code page 850.

**Comment by TomGruenewald** [comment]
Looking at the code from version 0.86.0.518 the code looks like this:

```
#if NETCF_1_0 || NETCF_2_0
		// This isnt so great but is better than nothing.
        // Trying to work out an appropriate OEM code page would be good.
        // 850 is a good default for english speakers particularly in Europe.
		static int defaultCodePage = CultureInfo.CurrentCulture.TextInfo.ANSICodePage;
#else
		static int defaultCodePage = Thread.CurrentThread.CurrentCulture.TextInfo.OEMCodePage;
#endif
```

In Version 1.2.0 it looks like this:

```
		private static Encoding EncodingFromFlag(int flags)
			=> ((flags & (int)GeneralBitFlags.UnicodeText) != 0)
				? Encoding.UTF8
				: Encoding.GetEncoding(
					// if CodePage wasn't set manually and no utf flag present
					// then we must use SystemDefault (old behavior)
					// otherwise, CodePage should be preferred over SystemDefault
					// see https://github.com/icsharpcode/SharpZipLib/issues/274
					codePage == AutomaticCodePage? 
						SystemDefaultCodePage:
						codePage);

```
I think the comment "if CodePage wasn't set manually and no utf flag present then we must use SystemDefault (old behavior)" is wrong. I am thinking the "old behavior" is not working here.

**Comment by Numpsy** [comment]
Theres a bit of a description of what changed between versions @ https://github.com/icsharpcode/SharpZipLib/wiki/ZipStrings-and-Unicode

(Think the basic situation is that unless the UTF-8/Unicode flag is set in the zip, there is no record of what codepage was used stored inside the file. The spec suggests a default of IBM437, but it more often seems to just be whatever the creating system was using, and what default to use when reading such files seems to be a point of centention)

**Comment by TomGruenewald** [comment]
Numpsy, thank you for you answer.
I am on vacation now and will continue the work on my SharpZipLib problem by mid next January.
Have a good time.

**Comment by piksel** [comment]
Okay, so, the file names are encoded in the zipfile using code page 850 (where `0xf1` is ± and `0x9d` is Ø). Using many european localizations of windows will yield the default code page 1251 (which is basically ISO-8859-1 or Latin-1).
The codepage that you set on ZipStrings is what the library should use to translate the bytes in the file to C# strings. Since that information is not actually stored in the file, the library cannot deduce what code page to use (unless the Unicode bit is set, then it uses UTF-8).
Since you know the correct encoding for the file names, you should just set the `ZipStrings.CodePage` to `850` and it should read the file names and comments correctly.

If you would set the code page to the console encoding (your example with `Console.OutputEncoding.CodePage`) it would interpret the filename bytes using the operating systems default encoding (which is what we're doing in the first place).

**Comment by TomGruenewald** [comment]
Hello piksel. Thank you for your answer.

Using `int codePage = System.Globalization.CultureInfo.CurrentCulture.TextInfo.OEMCodePage;` works for both, for European as well as for Japanese systems. We will use this as our solution. I realy hope this will do the job.

Thank you for your answers.
