### ISSUE TITLE
ZipFile.TestArchive fails when using encryption

### ISSUE THREAD

**Issue by AqlaSolutions** [icsharpcode/SharpZipLib#404]
### Steps to reproduce
1. Archive files with ZipOutputStream (~350 mb), set password "test", AESKeySize = 256, UseZip64 = On
2. Open archive with ZipFile
3. Call ZipFile.TestArchive(false)

### Expected behavior
Should return true.

### Actual behavior
Returns false because WinZipAES compression method doesn't match Deflated method specified in entry header.

### Version of SharpZipLib 
dll version 1.2.0.246

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by AqlaSolutions** [comment]
Also testing or extracting archive in WinRAR 5.10 gives "Not enough memory" error

**Comment by Numpsy** [comment]
same as #317 ? (that one has PR #353 attached as a possible fix)

**Comment by AqlaSolutions** [comment]
Yes, same
