### ISSUE TITLE
Ignore "Compressed size mismatch" error from Xceed

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#41]
[SD-1801](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1801), originally created on 12/20/2010 02:06:14 by David Pierson

When a password is applied, Xceed is incorrectly setting values in the
local header. This results in a “Compressed size mismatch between
central header(2399) and local header(0)” exception in
ZipFile.TestLocalHeader. 
 
 Sample code in ZipFile.cs at line 1259 ...
 
 if (compressedSize != entry.CompressedSize &&
                         compressedSize != 0xFFFFFFFF && compressedSize
!= -1**&& compressedSize != 0**) {
                         throw new ZipException(
                             string.Format("Compressed size mismatch
between central header({0}) and local header({1})",
                             entry.CompressedSize, compressedSize));
                     }
 
 Forum thread:

[http://community.sharpdevelop.net/forums/t/12404.aspx](http://community.sharpdevelop.net/forums/t/12404.aspx)
 "Errors unzipping zip files created using Xceed V4.0"

**Comment by McNeight** [comment]
With commit 3bd09a702d3780bb7acbe4fe9ffcef5e2ca108e6 from both PR #18 and #93, this issue is now fixed.

-Neil
