### ISSUE TITLE
Binary OR Assembly

### ISSUE THREAD

**Issue by nsmith1024** [icsharpcode/SharpZipLib#410]
Hello,

I have this error in Unity.....

The Assembly ICSharpCode.SharpZipLib is referenced by taglib-sharp ('Assets/Rhythm Visualizator Pro PLUS/Plugins/taglib-sharp.dll'). But the dll is not allowed to be included or could not be found.

So how to i resolve this, is there a SharpZipLib DLL or something i can use to resolve this so i can build? I dont see any DLL in this project source code, can anybody help?

Thanks so much!

**Comment by piksel** [comment]
It's kind of hard to know what version of the dll that you need. Taglib-Sharp does not officially have an dependency on SharpZipLib as far as I can tell. The exact dependencies for "Rhythm Visualizator Pro PLUS" is probably easiest to get from the it's distributor.
That being said, if you want to try to find the DLL manually, you can download the .nupkg files from the [releases page](https://github.com/icsharpcode/SharpZipLib/releases) and open them as zip files (using for example 7-zip). Hopefully if you add the wrong version of the DLL you might be prompted with another error message that specifies what version it expects.

**Comment by Numpsy** [comment]
It looks like taglib-sharp did have a conditional dependancy on sharpziplib at one point, but that was removed in favour of just using System.IO.Compression (the changelog in the taglib repo mentions it from back in 2012, don't know what version that would have been wanting though)

**Comment by piksel** [comment]
For mono it used to be. This has casued a lot of head scratching...

**Comment by piksel** [comment]
Closing due to lack of response
