### ISSUE TITLE
Test WriteZipStreamWithNoCompression Failed

### ISSUE THREAD

**Issue by workgroupengineering** [icsharpcode/SharpZipLib#423]
### Steps to reproduce
1. Run test

### Expected behavior
testing must not fail

### Actual behavior
Test throw "No entry matching source file \"{0}\" found in archive, found \"{1}\""

### Version of SharpZipLib
cuurent SharpZipLib/master
### Obtained from (only keep the relevant lines)
- Compiled from source, commit: 803b4a2
- Downloaded from GitHub

**Comment by Numpsy** [comment]
Related to the discussion in #341 - I'm not sure whether the name transforming/cleaning should be done in ZipOutputStream, rather than always being left up to the caller.

**Comment by Numpsy** [comment]
should be fixed now?

**Comment by piksel** [comment]
Yeah, I moved this to it's own test in #502 and forgot to link this issue!

Since #497 the underlying cause should be fixed as well.
