### ISSUE TITLE
TarOutputStream kills base stream

### ISSUE THREAD

**Issue by 3dGrabber** [icsharpcode/SharpZipLib#428]
### Steps to reproduce
```
var ms = new MyStream();
var ts = new TarOutputStream(ms);   // 1
// Do something with ts
ts.Dispose();  
ms.DoSomething();   // BOOM: ObjectDisposedException
```

### Expected behavior
Base stream `ms` is usable after the `TarOutputStream` wrapper is disposed.

### Actual behavior
Base stream `ms` throws an `ObjectDisposedException` because it has been disposed by the  `TarOutputStream` wrapper.

### Version of SharpZipLib
SharpZipLib 1.2.0

### Obtained from NuGet
- Package installed using NuGet

### Comments
The behavior is unexpected, because we provide `TarOutputStream` a reference to an *external Stream*, and `TarOutputStream` just shuts it down, when we dispose it.
The problem can be mitigated by setting `TarOutputStream.IsStreamOwner = false` at (1).

### Proposed fix
`TarOutputStream.IsStreamOwner` should default to `false` when the constructors `TarOutputStream(Stream outputStream)` or `TarOutputStream(Stream outputStream, int blockFactor)` are used.

**Comment by piksel** [comment]
We cannot change the defaults for this (API breaking) even if it was considered a better one. By setting the IsStreamOwner, you take responsibility for freeing the resources when done.
The behaviour is mimicking that of StreamReader/[StreamWriter](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamwriter.-ctor?view=netcore-3.1#System_IO_StreamWriter__ctor_System_IO_Stream_System_Text_Encoding_System_Int32_System_Boolean_)

**Comment by 3dGrabber** [comment]
> The behaviour is mimicking that of StreamReader/StreamWriter

Wow, just checked, ` StreamReader/StreamWriter` indeed exhibit the same behavior (`bool leaveOpen = false`).   
Bad API design IMO.  

Anyways, given the precedent, and the need for backwards compatibility I'll close this.
