### ISSUE TITLE
[Wiki] Status of the roadmap page?

### ISSUE THREAD

**Issue by Numpsy** [icsharpcode/SharpZipLib#429]
The [Roadmap](https://github.com/icsharpcode/SharpZipLib/wiki/Roadmap) page on the wiki is somewhat out of date with regards to features supported in the current release.

Not sure if there is much of a roadmap at the moment to update the page with, or if it would be simpler to remove it?

**Comment by piksel** [comment]
Yeah, the current roadmap, if written down, would probably not be that inspiring. I guess the old one left with the last maintainer.

**Comment by piksel** [comment]
Removed the roadmap for now.
