### ISSUE TITLE
[Wiki] out of date licence information on the FAQ page

### ISSUE THREAD

**Issue by Numpsy** [icsharpcode/SharpZipLib#430]
The "Can I use SharpZipLib in my commercial application?" section of the [FAQ](https://github.com/icsharpcode/SharpZipLib/wiki/FAQ) wiki page still states that the source code is GPLed, which is incorrect at this point, so I assume it should be updated?

**Comment by piksel** [comment]
Good point. Didn't even realize w had a FAQ :/

**Comment by Numpsy** [comment]
I can't say that i've payed much attention before, was just browsing and noticed the out of date text.

It also mentions a HTML help file - does the project still have one of those?

**Comment by christophwille** [comment]
From the "sidelines" of our other projects in this org - in AvalonEdit we are using Sandcastle HFB (only because it was there already, not because I would choose it for a new project). I cannot remember what was used way back in SharpZipLib, but I think it was directly from the doc xml without any other additional sources.

**Comment by piksel** [comment]
@christophwille this sounds like the discussion about using a 3rd-party encryption library? Or is it related to the FAQ?

**Comment by christophwille** [comment]
I was referring to building the help file.

**Comment by piksel** [comment]
Right, sorry. We do build docfx documentation in HTML format, but it's not distributed with the package. Perhaps we should just remove that question to avoid confusion? I updated the "commercial use" answer at least.

**Comment by christophwille** [comment]
Right, it's not distributed with the package but online at https://icsharpcode.github.io/SharpZipLib/help/api/index.html - maybe link that there instead.

**Comment by piksel** [comment]
Yeah. Done!
Also changed some references to #Zip and made the questions into headers for easier scanning through

**Comment by jtbrower** [comment]
Gents, thanks for getting the licensing concerns taken care of.  I have wanted to use this library for years and now I am happy to see that I can.  Cheers.
