### ISSUE TITLE
Q. Multi-targeted unit tests?

### ISSUE THREAD

**Issue by Numpsy** [icsharpcode/SharpZipLib#434]
Think i've wondered this before after seeing differences between the way that .NET and .NET Core handle validation of characters in paths, but thinking about it again in regards to code page handling with #427:

The unit tests are currently run as .NET Core 2.0 only, but they could be made to multi-target both some version of Core, and .NET 4.5 as well (to match the targets on the lib itself) ?

VS 2019 and the dotnet command line tools will handle that ok (will run under multiple frameworks and display multiple results sets), though the test runner in VS 2017 will only run one of the targets.

**Comment by piksel** [comment]
Yeah, good point.

**Comment by Numpsy** [comment]
The tests are multi-targeted now, but only the NET Core version is run on the CI builds.

Not sure if running both sets of tests would be easier to do with #419 and / or made as part of that change?

**Comment by piksel** [comment]
#419 runs all platforms/frameworks/configurations as of now
