### ISSUE TITLE
unzip，digital signature of the EXE lost

### ISSUE THREAD

**Issue by BigQ517** [icsharpcode/SharpZipLib#438]
### Steps to reproduce
1.A zip containing an exe file
2.This exe file is digitally signed
3.unzip with SharpZipLib
4.the exe digital signature lost

### Expected behavior
Retain the digital signature of the file

### Actual behavior
the exe digital signature lost

### Version of SharpZipLib
v1.2.0
### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by Numpsy** [comment]
That sounds odd. Is the file being corrupted in any other way? (does it still work etc)

**Comment by BigQ517** [comment]
Files can be used, just missing signature information, when using System.IO.Com pression. ZipFile. ExtractToDirectory method, work fine.

**Comment by BigQ517** [comment]
Files work fine, just missing signature information. when using System.IO.Com pression. ZipFile. ExtractToDirectory method, no missing.

**Comment by Numpsy** [comment]
When extracting with SharpZipLib, are you using FastZip, or one of the lower level apis (ZipFile, ZipInputStream) ?

**Comment by piksel** [comment]
Are the extracted files the same size? An embedded signature is appended to the end of the PE binary, so if it is missing, the file should be smaller. I wonder if there could be some kind of extra data fields for this. The best thing would of course be if you could provide a sample .zip file where the problem occurs.

**Comment by Numpsy** [comment]
I *think* Windows Explorer will hide the signature tab on the file properties if the file has been modified, not just if the signing data has been removed?

e.g. if you extract the file using the code snippet from #394 then the extracted file will be slightly larger than the original, won't be classed as signed by explorer, but might still be classed as a valid exexutable and still run
