### ISSUE TITLE
ArgumentNullException is thrown if we use AESKeySize = 256. 128 does work

### ISSUE THREAD

**Issue by davspan** [icsharpcode/SharpZipLib#447]
### Steps to reproduce
1. Install SharpZipLib.NETStandard on a Xamarin Android Project
2. Execute:

```
private static async Task AddRawContentToZipAsync(ZipOutputStream zipStream, byte[] rawContent, string fileName) {
   var file = new ZipEntry(fileName) { AESKeySize = 256, Size = rawContent.Length };
   zipStream.PutNextEntry(file); -> EXCEPTION THROWN
   await zipStream.WriteAsync(rawContent, 0, rawContent.Length);
   zipStream.CloseEntry();
}
```

### Expected behavior
Any Exception should be thrown

### Actual behavior
An _ArgumentNullException_ is thrown if we use **AESKeySize = 256** after we call "zipStream.PutNextEntry()". _**It works with AESKeySize = 128**_

### Version of SharpZipLib
1.0.7

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by Numpsy** [comment]
> ### Version of SharpZipLib
> 
> 1.0.7
> ### Obtained from (only keep the relevant lines)
> 
>     * Package installed using NuGet

Is that the official package or one of the forks that you're using? (there hasn't been a 1.0.7 release out of this repo as far as I know, it went from 1.0.0 to 1.1.0).

**Comment by davspan** [comment]
Oh, it is actually "https://github.com/PingmanTools/SharpZipLib"

**Comment by Numpsy** [comment]
There have been issues along these lines in the past, e.g #181, but I think that should be fixed now (that other fork seems to be some way behind and missing a lot of fixes that went into that area)

**Comment by piksel** [comment]
Yes, the issue summary actually contains the row
1. Install **SharpZipLib.NETStandard** on a Xamarin Android Project

Try using the latest "SharpZipLib" package (v1.2.0)

**Comment by davspan** [comment]
Thank you very much. It seems to work now :D
