### ISSUE TITLE
Add files to zip more efficiently

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#45]
[SD-1881](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1881), originally created on 1/27/2012 06:22:03 by David Pierson

The ability to add to a zip more efficiently has been asked for.

 1) When the source is already zipped, to add to another zip (either
with BeginUpdate/Add/Commit or via standard zip creation) requires
unpacking and repacking. For efficiency allow adding already compressed
data. 

 2) When updating, the process requires disk or memory for a temporary
copy. Requested to add to a zip without either.

 Threads:
 [Add files to a zip without saving temp
files](http://community.sharpdevelop.net/forums/t/14110.aspx)

**Comment by piksel** [comment]
1. This could be done, but I don't think the use case is big enough. If we should spend time on this feature there needs to be a fresh request with a motivation.
2. Directly modifying zip-files is both hard to do correctly and will have data-destroying consequences when done incorrectly. I would avoid doing this unless there is a very good reason to do so.

Closing this  as I don't think these are very requested features and they have been left unimplemented for over 8 years.
