### ISSUE TITLE
Zip a stream on the network

### ISSUE THREAD

**Issue by Prabhuss** [icsharpcode/SharpZipLib#459]
Can you give me an example to compress the network stream? I used a memory stream and flushing periodically to the network stream, however, the network stream file seems to be corrupted. While I debug I found that ZipOutputStream is trying to seek previously written data. Due to which it is creating a corrupted stream in case of network stream as CanSeek is false.

**Comment by Numpsy** [comment]
If you give ZipOutputStream a seekable stream then it will try to seek back in the stream after writing each entry in order to patch the entry header with the final file information (size etc), and I suppose that could go wrong if the original entry data has already been sent over the network.

You might need to always give it a non-seekable stream in this case - if compressing straight into the network stream is no good, then maybe a non-seekable MemoryStream, or perhaps a BufferedStream?

**Comment by Prabhuss** [comment]
Yes, I created my own stream and made it as non-seekable. After making this change, zip seems to be corrupted. As i'm able to see only one entry(when i add more number of items) in the zip. Unable to extract the same even that single entry.

**Comment by piksel** [comment]
The zip format allows for setting the size in a `descriptor` field after the data for this purpose. I have very limited experience in using it, but that's what `ZipOutputStream` should do when the output stream returns `false` from `CanSeek`. Does the Seek method / Position property throw exceptions? If so, could you provide the stack trace for the calls, since that should not be happening.

**Comment by Numpsy** [comment]
Quick extra question: what are you using the extract the zip? (really just wondering if its ZipInputStream or something else)

**Comment by Prabhuss** [comment]
@piksel , 

In my custom Stream implementation,  CanSeek returns false and doesn't throw an exception. 
There is no exception while creating the zip. i'm able to open using 7z tool (but it always shows only one entry). But unable to extract it.

But when I open the zip it says, 

![image](https://user-images.githubusercontent.com/26796392/81695051-b5330a80-947f-11ea-82ad-5d419d9f8e16.png)


Used the below code to create zip,

using (var zipStream = new ZipOutputStream(outputMemStream)) //outputMemStream is my custom memorystream implementation, where in CanSeek returns false.
            {
                foreach (var it in files)
                {
                    zipStream.SetLevel(3);

                    ZipEntry newEntry = new ZipEntry(Path.GetFileName(it));
                    //Console.WriteLine("Name is " + it + ":::" + Path.GetFileName(it));
                    newEntry.DateTime = DateTime.Now;
                    FileStream fr = File.OpenRead(it);
                    newEntry.Size = fr.Length;
                    zipStream.PutNextEntry(newEntry);
                    StreamUtils.Copy(fr, zipStream, new byte[4096]);
                    zipStream.CloseEntry();
                }
                zipStream.IsStreamOwner = false;
            }

@Numpsy,
I'm using a 7z tool to view and extract.

**Comment by Numpsy** [comment]
Ok, the info that it's using Zip64 might be useful and that file entry does look rather large, so that's something to look at.

**Comment by Prabhuss** [comment]
I'm adding multiple files to the same zip.I tried with Zip64 and without zip64 also. Both are yielding the same result. 

here is the screenshot without zip64.

![image](https://user-images.githubusercontent.com/26796392/81700031-c252f800-9485-11ea-9e14-1c454adf23f3.png)

Here is the sample zip,

[12345.zip](https://github.com/icsharpcode/SharpZipLib/files/4616019/12345.zip)

**Comment by piksel** [comment]
Yeah, that CRC does not look correct...  I'll try to make a minimal repro...

**Comment by Prabhuss** [comment]
@piksel 

Any update on this issue.

**Comment by Numpsy** [comment]
I had a quick go at tweaking the unit tests to try to repro the issue and didn't manage to, though i have seen an intermittent failure in the ```SingleLargeEntry``` zip unit test (I haven't tracked down if it;s a bug or a test issue)

**Comment by piksel** [comment]
I have not been able to reproduce either, but it really does seem like SharpZipLib thinks that the output is seekable, that would result in what we are seeing now. What I meant by throwing an exception was doing this:
```cs
public override bool CanSeek => false;

public override long Seek(long offset, SeekOrigin loc) => throw new NotSupportedException();
```

That way, if SharpZipLib was actually calling the `Seek()` method, you could follow the stack trace to issue perhaps? How do you know that it is trying to seek?

**Comment by Prabhuss** [comment]
@piksel 

I added log statements in my custom stream seek method. I was able to multiple seeks calls on the console. If I make Nonseekable (CanSeek = false), then it never executed the Seek method. However, the zip is corrupted.  It is easily reproducible for me, but the scenario is as follows,

> Adding different sizes of files into the zip. (overall RAW size 200 MB)
> My custom In-Memory(CanSeek=false) limit is 100 MB, That means after 100 MB of size, it flushes into the network stream.
> Final zip is in corrupted format

**Comment by Numpsy** [comment]
I'll have a go with multiple files when I get a chance.

Something going wrong with the position on the stream maybe? (I don't *think* ZipOutputStream should use the position for non-seekable streams though)

**Comment by piksel** [comment]
So, the file you submitted was *not* created with CanSeek = false? That would explain why it looks the way it does. Could you upload a corrupted file where no Seek calls have been made? Then I might be able to deduce what goes wrong with the stream. My guess is that it might be related to endianess or something similar since network is involved.
Does the file get corrupted if it's less than the threshold (100mb)?

**Comment by Prabhuss** [comment]
@piksel ,

Earlier submitted was using CanSeek == false. To test this, instead of writing to the network, was verifying locally by storing the in memory into the zip file. In my test environment, I'm not using a network yet. I just want to make sure if I'm able to create zip using my custom stream then I will test with the network stream.

I was trying to create a sample code to reproduce the issue. But found that it is a problem with my custom stream. But I'm not sure what is wrong with my custom stream. If i use MemoryStream it is working fine. Here is my code, Can you please let me know what could be the issue here,

`class CMemoryStream : Stream
    {
        private MemoryStream _memoryStream = new MemoryStream();
        private bool canSeek;
        public CMemoryStream(bool canSeek)
        {
            this.canSeek = canSeek;
        }

        public override bool CanRead => true;

        public override bool CanSeek
        {
            get => canSeek;
        }
        public void EnableSeek()
        {
            canSeek = true;
        }

        public override bool CanWrite => true;

        public override long Length => _memoryStream.Length;

        public override long Position { get => _memoryStream.Position; set { _memoryStream.Position = value; } }

        public override void Flush()
        {
            _memoryStream.Flush();
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            return _memoryStream.Read(buffer, offset, count);
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            return _memoryStream.Seek(offset, origin);
        }

        public override void SetLength(long value)
        {
            _memoryStream.SetLength(value);
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            for (int i = 0; i < buffer.Length; i++)
            {
                _memoryStream.WriteByte(buffer[i]);
            }
        }
    }`

**Comment by piksel** [comment]
Okay, I have updated my repro with your stream and set up a test that shows that the files do not pass zipfile verification  when ran through your class:
![image](https://user-images.githubusercontent.com/807383/83554446-0ed1a680-a50d-11ea-84cd-c38b2e97f090.png)
Now let's start experimenting!

**Comment by piksel** [comment]
Found the issue!

The Write() override does not use the supplied `offset` and `count` variables!
```cs
public override void Write(byte[] buffer, int offset, int count)
{
	for (int i = 0; i < buffer.Length; i++)
	{
		_memoryStream.WriteByte(buffer[i]);
	}
}
```

This successfully passes:
```cs
public override void Write(byte[] buffer, int offset, int count)
{
	for (int i = offset; i < count; i++)
	{
		_memoryStream.WriteByte(buffer[i]);
	}
}
```

Or even better:
```cs
public override void Write(byte[] buffer, int offset, int count) 
    => _memoryStream.Write(buffer, offset, count);
```

**Comment by Prabhuss** [comment]
@piksel,

Looks my understanding of the Write method was wrong. 
 
Thanks for the help. My test program is passing now. I will test with my code and update it here.

--Srinu

**Comment by Prabhuss** [comment]
@piksel, @Numpsy,

Thank you for your patience, time and support. My code is working beautifully. 

--Srinu
