### ISSUE TITLE
Intellisense help XML file: include in distribution

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#47]
[SD-1883](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1883), originally created on 1/27/2012 06:30:08 by David Pierson

Binary distribution should include the XML intellisense help file
 

[http://community.sharpdevelop.net/forums/t/14329.aspx](http://community.sharpdevelop.net/forums/t/14329.aspx)

**Comment by McNeight** [comment]
ICSharpCode.SharpZipLib.xml is now automatically generated by compiling either the Debug or the Release configuration. This file will be included in future binary distributions.

-Neil
