### ISSUE TITLE
Dont create TarArchive with smaller files.

### ISSUE THREAD

**Issue by Saimon2k** [icsharpcode/SharpZipLib#474]
### Steps to reproduce
1. Create TarArchive with smaller files.
2. Dont open this is tar file.

### Expected behavior
Created correct file.

### Actual behavior
Dont opening file.

### Version of SharpZipLib
1.2.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

[file1.txt](https://github.com/icsharpcode/SharpZipLib/files/4798220/file1.txt)
[file2.txt](https://github.com/icsharpcode/SharpZipLib/files/4798221/file2.txt)

**Comment by Numpsy** [comment]
If you're having issues with small files in 1.2, that might be the issue described in #409 ?
