### ISSUE TITLE
ZipFile.Delete on a folder entry fails

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#48]
[SD-1915](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1915), originally created on 10/10/2012 01:39:29 by David Pierson

ZipFile.Delete on a folder entry fails with an exception.

 The call to FindExistingUpdate changes the name of what is being looked
for and it fails to find the key.

[community.sharpdevelop.net/forums/t/16314.aspx](http://community.sharpdevelop.net/forums/t/16314.aspx)

**Comment by Numpsy** [comment]
Is the deleting of folder entries all fixed now?

**Comment by piksel** [comment]
It should be. Otherwise a new ticket should be created anyway since the mentioned root cause here should at least not trigger it anymore.
