### ISSUE TITLE
Unable to extract the zip generated using this library

### ISSUE THREAD

**Issue by rsrini83** [icsharpcode/SharpZipLib#480]
### Steps to reproduce
1. We are using MemoryStream + CanSeek = false.
2. Generated zip is not able to uncompress using windows explorer. And able to extract using 7zip, but gives a warning.

### Expected behavior
Should be able to extract without any error.

### Actual behavior
Windows throw below exception

![image](https://user-images.githubusercontent.com/16274962/86010314-def8be80-ba38-11ea-85ba-299635f51c54.png)

7zip extract gives below error

![image](https://user-images.githubusercontent.com/16274962/86019651-7c0d2480-ba44-11ea-8f77-2ca0125f81ef.png)

### Version of SharpZipLib
1.2.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

Here is the sample zip:

[CC_Sub-2_202006291422448602.zip](https://github.com/icsharpcode/SharpZipLib/files/4846178/CC_Sub-2_202006291422448602.zip)

**Comment by rsrini83** [comment]
Hi,

Any help is appreciated. Would like to understand what is going wrong with my code. 

Thanks in advance.  

--Srinu

**Comment by Numpsy** [comment]
Is this creating the zip with ZipOutputStrem or FastZip? (I assume it isn't ZipFile given the comment about non-seekable streams).

**Comment by rsrini83** [comment]
@Numpsy,
 
I have created a custom stream that has a non-seekable stream (which internally uses MemoryStream). I have tried with 0.86 as well as with the latest zip. Both versions generating the similar behavior zip files.

I suspect i might be doing something wrong here, but need your guidance what is the issue with the attached zip file. 

--Srinu

**Comment by Numpsy** [comment]
Opening the file in 7-zip, it looks similar ot the one discussed in #459, which describes a similar sitation when writing to a custom non-seekable stream.

**Comment by piksel** [comment]
Yeah, that file has no Central Directory:
![image](https://user-images.githubusercontent.com/807383/86513110-bf321380-be07-11ea-8555-6cbbd8e72e3b.png)

I think it doesn't get flushed correctly.
The easiest solution would be to expliclitly call `zipOutputStream.Flush()` after you are done writing to it, but that shouldn't normally be required.
If you post the source of your compression code we might be able to spot whats going on.

**Comment by Numpsy** [comment]
Lack of central directory could maybe happen if you don't either Finish() or Dispose ZipOutputStream after writing all the entries?

**Comment by piksel** [comment]
Exactly. Flush (which I previously wrote) wouldn't be enough on the `OutputStream`s. My guess is that the `ZipOutputStream` is not  closed before the underlying stream is being read.

**Comment by rsrini83** [comment]
@piksel 

Yes, your point helped me to fix the issue. Able to resolve the issue after invoking ZipOutputStream.Finish method inside using block.
`using (zipper = new Zipper2(token, "a123.zip"))
            {
                string[] files = Directory.GetFiles(@"C:\Users\Downloads\test", "*.*", SearchOption.AllDirectories);
                foreach (var it in files)
                {
                    ByteItem b = new ByteItem();
                    b.Content = File.ReadAllBytes(it);
                    b.Name = Path.GetFileName(it);
                    zipper.Create(b);
                }
                zipper.Finish(); // This was not there, after adding this it is working fine. 
                zipper.CompleteWriteToFile(@"C:\Users\Desktop\a1234.zip");
            }
`
I'm closing this ticket.

@Numpsy, @piksel ,

Thank you for your time and help. 

--Srinu
