### ISSUE TITLE
Corrupted tar archive with entries created from the memory stream

### ISSUE THREAD

**Issue by tkhametov** [icsharpcode/SharpZipLib#486]
### Steps to reproduce
1. Read the file from file to `Stream`.
2. Put this stream into tar archive.

### Expected behavior
Tar archive isn't corrupted and I'm able to extract files from this one.

### Actual behavior
Tar archive is corrupted:
```
[root@user-pc Work]$ tar xvfp archive.tar 
app.txt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
```

### Version of SharpZipLib
ICSharpCode.SharpZipLib.Patched 1.2.0.9

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

Hi guys. I'm trying to compress files on the fly on the server-side. So the client sends a file and server returns compressed file within tar archive. That's why I can't use `TarEntry.CreateEntryFromFile()` and so on and I have to work only with `FileStream` or `MemoryStream`.

But the server returns the corrupted archive and I can't extract files from this one. I've tried to rewrite this code for the console application, but I have the same problem, here is the code I use below:
```csharp
       static void Main(string[] args)
        {
            string inputFilePath, outputArchivePath;
            ...
            
            var fileToCompress = new FileToCompress
            {
                FileName = Path.GetFileName(inputFilePath),
                FileStream = File.OpenRead(inputFilePath)
            };

            var readyArchive = Compress(fileToCompress);
            using var archive = File.Create(outputArchivePath);

            archive.Write(readyArchive.ToArray());
            
            ...
        }

        static MemoryStream Compress(FileToCompress file)
        {
            using TarOutputStream archiveStream = new TarOutputStream(new MemoryStream(), Encoding.Default);

            string fileName = file.FileName;
            Stream fileContent = file.FileStream;
            TarEntry entry = TarEntry.CreateTarEntry(fileName);
            entry.Size = fileContent.Length;

            archiveStream.PutNextEntry(entry);
            StreamUtils.Copy(file.FileStream, archiveStream, new byte[32 * 1024]);
            archiveStream.CloseEntry();

            archiveStream.IsStreamOwner = false;
            MemoryStream finalStream = new MemoryStream();
            archiveStream.Seek(0, SeekOrigin.Begin);
            archiveStream.CopyTo(finalStream);

            return finalStream;
        }

        public class FileToCompress
        {
            public Stream FileStream { get; set; }

            public string FileName { get; set; }
        }
```

What am I doing wrong?

**Comment by Numpsy** [comment]
think you might need to Close or Finish the TarOutputStream before trying to read from it, to ensure that it's written/flushed everything to the output first?

(untested: pass finalStream to the TarOutputStream constructor to use as its output stream, then return that after disposing archiveStream. The test @ https://github.com/icsharpcode/SharpZipLib/blob/b6ab9f5da988dbcc87b54def87e7340c19358844/test/ICSharpCode.SharpZipLib.Tests/Tar/TarTests.cs#L75 does something similar, as does the wiki entry at https://github.com/icsharpcode/SharpZipLib/wiki/GZip-and-Tar-Samples#-create-a-tar-or-tgz-with-control-over-filenames-and-data-source)

**Comment by tkhametov** [comment]
@Numpsy thanks a lot, I've rewritten it as the following and now it works!
```csharp
        static MemoryStream Compress(FileToCompress file)
        {
            MemoryStream finalStream = new MemoryStream();
            using TarOutputStream archiveStream = new TarOutputStream(finalStream, Encoding.Default);

            string fileName = file.FileName;
            Stream fileContent = file.FileStream;
            TarEntry entry = TarEntry.CreateTarEntry(fileName);
            entry.Size = fileContent.Length;

            archiveStream.PutNextEntry(entry);
            StreamUtils.Copy(file.FileStream, archiveStream, new byte[32 * 1024]);
            archiveStream.CloseEntry();

            archiveStream.IsStreamOwner = false;
            archiveStream.Close();
            archiveStream.Flush();

            return finalStream;
        }
```
