### ISSUE TITLE
throwing "Unexpected EOF" in version 1.2

### ISSUE THREAD

**Issue by TonyDTX** [icsharpcode/SharpZipLib#490]
Where decompressing gzipped data, throws "Unexpected EOF" in InflaterINputStream.Fill() Line: 493

Test code:
byte[] oCompressed = oData.Compress(); // oData is a byte[],size: 415,164 bytes
byte[] oDecompressed = oCompressed.Decompress(); // throws exception

Compress/Decompress methods follow:

      static public byte[] Compress(this byte[] oValue)
      {
         if (oValue == null)
            return null;

         using (MemoryStream oClearStream = new MemoryStream(oValue))
         using (MemoryStream oCompresedStream = new MemoryStream())
         using (GZipOutputStream oGZipOutputStream = new GZipOutputStream(oCompresedStream, 1048576))
         {
            oClearStream.CopyTo(oGZipOutputStream, 1048576);
            byte[] oCompressed = oCompresedStream.ToArray();

            return oCompressed;
         }
      }

      static public byte[] Decompress(this byte[] oValue)
      {
         if (oValue == null)
            return null;

         using (MemoryStream oCompressedStream = new MemoryStream(oValue))
         using (MemoryStream oDecompresedStream = new MemoryStream())
         using (GZipInputStream oGZipInputStream = new GZipInputStream(oCompressedStream, 1048576))
         {
            oGZipInputStream.CopyTo(oDecompresedStream, 1048576);
            return oDecompresedStream.ToArray();
         }
      }      

### Expected behavior
It should be capable of decompressing anything it compresses.

### Actual behavior
throw new SharpZipBaseException("Unexpected EOF"); 

### Version of SharpZipLib
v1.2.0

### Obtained from (only keep the relevant lines)
- Downloaded from GitHub

**Comment by Numpsy** [comment]
I think you'll need to Finish() or Close/Dispose the GZipOutputStream before reading the data from oCompresedStream, otherwise it won't contain the footer information for the GZip stream (which will otherwise be written when the stream is disposed, which wil be after oCompressed is created).

**Comment by TonyDTX** [comment]
That appears to be the problem, rookie mistake.
Thanks for your time.
