### ISSUE TITLE
Include recent releases on the release-history wiki page?

### ISSUE THREAD

**Issue by Numpsy** [icsharpcode/SharpZipLib#496]
The Release History wiki page (https://github.com/icsharpcode/SharpZipLib/wiki/Release-History) only lists up to the 0.86 release,.

There are seperate pages of the 1.0/1.1/1.2 versions, but given that the Release history page is linked on the front page of the Wiki, and also from the ```change log``` section of http://icsharpcode.github.io/SharpZipLib/, and objections to extending the history page with links to the other pages?

**Comment by piksel** [comment]
I added some summaries to the v1.0+ releases and linked to their corresponding pages. I fully trust you to make good changes, so you don't need to ask before doing things like this. Worst case, we can always just roll back wiki edits!😄

**Comment by Numpsy** [comment]
Ok, thanks, wasn't sure which bits need to be reviewed.
