### ISSUE TITLE
Windows Store app library error

### ISSUE THREAD

**Issue by ghost** [icsharpcode/SharpZipLib#50]
Could not install package 'SharpZipLib 0.86.0'. You are trying to install this package into a project that targets '.NETCore,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by christophwille** [comment]
The -alpha packages are now netstandard1.3. (aside: with netstandard2.0 changes you might even be able to reference the old .86 package)

**Comment by Numpsy** [comment]
Is there any issue or thing to look at here at this point? (the ops account also seems to have gone from the look of it)

**Comment by piksel** [comment]
Nope.
