### ISSUE TITLE
Simple API utilities for common cases!

### ISSUE THREAD

**Issue by EliasCK** [icsharpcode/SharpZipLib#508]
I just don't understand why I'm wasting so much time fucking around with streams!!! And writing 30 freaking lines of bullshit code. Why is there no one-liner methods for the common cases? 

var newBytes = Utilities.ZipMyData(bytes, method)
or
Utilities.ZipAFile(srcPath, dstPath)
bytes Utilities.UnzipFile(srcPath, dstPath)

Gaaargh!!! Not a single freaking dotnet zip library out of the 10 I visited had a simple code example in the readme.md where it shows you hard easy it is! Every library just wants me to waste time.

Sorry I had to vent here. You where number 1, and 10. Guss I'll copy paste this fucking monster https://github.com/icsharpcode/SharpZipLib/wiki/Create-a-Zip-from-to-a-memory-stream-or-byte-array And move on with my life.

**Comment by piksel** [comment]
Calm down, I understand your frustration, but the library have many different consumers with different needs. 
The "Simple API utilities" class is called `FastZip`, but it doesn't cover your specific case. Zip files have multiple entries (ie. files) and just creating a zip file containing a single entry from a byte-array is not the most common scenario.
There is also the `ZipFile` class that is an intermediate abstraction where you can add zip entries from data sources (such as a byte-array/MemoryStream). The wiki doesn't contain examples of those, though, we should definitely add some!
