### ISSUE TITLE
A bug on decompressing empty files

### ISSUE THREAD

**Issue by KKacer** [icsharpcode/SharpZipLib#515]
I think there is a bug in de-compressing an empty file.
I am using your complete sample of zipping an entire directory,
At the same time added AES256 encryption based on an advice here and set a password for the Zip files.
Tested in tens of samples, when it reaches empty files, the zip de-compressor (WinRar)
will ask again for the password (which will not accept the correct password), and then will throw a wrong password exception.

**Comment by Numpsy** [comment]
Is this creating the zips using FastZip or ZipOutputStream?

If you're using version 1.2. it might be that you're hitting one of the issues with flushing, or possibly #460 - if so, you could try it with the latest code and see if that fixes it for you?

**Comment by KKacer** [comment]
Hello @Numpsy 
Sorry for the late reply,
I was in a trip.
As you said, the official release had that bug,
After downloading the latest source seems that didn't happen.
Will back to you if it happened again.
