### ISSUE TITLE
TAR extractcontents stuck in loop

### ISSUE THREAD

**Issue by SimonJMBrown** [icsharpcode/SharpZipLib#524]
### Steps to reproduce
1. Not sure as happens on some Tar files
2. Tar opens and extracts with 3rd party apps so not corrupt
3. Tar in question has over 1100 files.

### Expected behavior
Tell us what should happen
Files extracted to a temp folder for me to then process

### Actual behavior
Tell us what happens instead
Program hangs in sharp dll, no exception thrown.

File explorer view of destinationfolder shows final 2 files in tar with their file size alternating between 0 and the actual file size, constantly flicking between the two.

### Version of SharpZipLib
Latest 1.4 via nuget in vs2017 
### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
Hello. I think you mean v1.3.0? That is the latest version that was just released. If so, could you try using v1.2.0 and see if you get the same behaviour?

Is it possible to share one of the files that trigger this problem?

You should be able to see exactly where it gets stuck using SourceLink, but that might not be available in VS2017.

**Comment by SimonJMBrown** [comment]
Apologies, it was 1.3. I was raising issue later in evening away from work laptop.
I have tried 1.2 version but same exact issues.

The tar contains 1496 files and exhibits same issue on same 2 files.

Afraid I cannot share TAR as it contains sensitive data, I also cannot run it under debug locally as I am not allowed a copy of the TAR file.

**Comment by Numpsy** [comment]
Is this just a plain tar file, or a tar.gz file? (I don't know if that matters, but it's useful to confirm I think).

**Comment by piksel** [comment]
Okay, so it wasn't any of the recent changes at least. If it is a tar.gz like @Numpsy asked, could you try removing the compression first (either with another tool, or by using a intermediate buffer), just to rule out the compression.
I should be able to figure out what situations could lead to an infinite loop in the tar handling code.

**Comment by SimonJMBrown** [comment]
Plain TAR file, no compression involved.

I have since tried Sharpcompress library and that worked on this problem tar file. It is now running against the other 60,000 tar files to see if any others cause a problem.

The Sharpcompress library is not as elegant to implement and doesn't appear to have a method to extract all files to destination in one pass, and requires multiple supporting DLLs but I have something I can use now.

If this bug is fixed I am happy to test against problem TAR again to confirm, maybe prevent some other person having same issue in future.

**Comment by piksel** [comment]
I have tried my best to reproduce it by corrupting various bits of a tar archive, but I cannot get it to loop. Perhaps there were some other code around it invovled?
The `TarArchive.ExtractContents` and `TarArchive.ListContents` loops both moves the buffer ahead one block (512 byte) on each spin, so it shouldn't be possible to get stuck.
Closing this until we can reproduce it :/

**Comment by BouRHooD** [comment]
I'm trying to create a tar archive, then extract all the contents to a file using [SharpZipLib](https://github.com/icsharpcode/SharpZipLib). I am able to create the tar archive, but the program hangs when trying to extract it. I'm wondering if anyone else can reproduce this problem and see why it is happening. I've also tried using [an example that allows for full control](https://github.com/icsharpcode/SharpZipLib/wiki/GZip-and-Tar-Samples#extractFull), and while debugging, it seems that my program hangs when tarIn.GetNextEntry() is called.

Here is my code  

        public void CreateTarAndExtract()
        {
            // create tar file
            string tarFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "tartest.tar");
            string inputFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "testfolder"); 
            using (var output = File.OpenWrite(tarFile))
            {
                using (var archive = TarArchive.CreateOutputTarArchive(output, Encoding.UTF8))
                {
                    var trimLength = inputFolder.Length + 1;

                    foreach (var fsEntry in Directory.GetFileSystemEntries(inputFolder, "*", SearchOption.AllDirectories))
                    {
                        var entry = TarEntry.CreateEntryFromFile(fsEntry);
                        entry.Name = fsEntry.Substring(trimLength);
                        archive.WriteEntry(entry, false);
                    }
                }
            }

            // extract file
            string outputPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "tartest");
            using (var input = File.OpenRead(tarFile))
            {
                using (var archive = TarArchive.CreateInputTarArchive(input, Encoding.UTF8))
                {
                    archive.ExtractContents(outputPath, true);
                }
            }
        }
