### ISSUE TITLE
Version 1.3.0 uses the wrong File Version (1.2.0.8)

### ISSUE THREAD

**Issue by dittodhole** [icsharpcode/SharpZipLib#527]
[Version 1.2.0](https://www.nuget.org/packages/SharpZipLib/1.2.0) contains "File version: 1.2.0.246"
[Version 1.3.0](https://www.nuget.org/packages/SharpZipLib/1.3.0) contains "File version: 1.2.0.8"

Please fix for future releases, as this has a massive impact on msi-installers (if no REINSTALLMODE is supplied, default behavior), and will break existing installations of programs using this assembly.

```
PS C:\Users\anne\.nuget\packages\sharpziplib\1.2.0\lib\net45> (Get-Item -Path '.\ICSharpCode.SharpZipLib.dll').VersionInfo | Format-List -Force


OriginalFilename  : ICSharpCode.SharpZipLib.dll
FileDescription   : ICSharpCode.SharpZipLib
ProductName       : ICSharpCode.SharpZipLib
Comments          : SharpZipLib (#ziplib, formerly NZipLib) is a compression library for Zip, GZip, BZip2, and Tar written entirely in C# for .NET. It is implemented as an assembly
                    (installable in the GAC), and thus can easily be incorporated into other projects (in any .NET language)
CompanyName       : ICSharpCode
FileName          : C:\Users\anne\.nuget\packages\sharpziplib\1.2.0\lib\net45\ICSharpCode.SharpZipLib.dll
FileVersion       : 1.2.0.246
ProductVersion    : 1.2.0+56cbe991dfbc629a155c6739501a658cf2f75cff
IsDebug           : False
IsPatched         : False
IsPreRelease      : False
IsPrivateBuild    : False
IsSpecialBuild    : False
Language          : Language Neutral
LegalCopyright    : Copyright © 2000-2019 SharpZipLib Contributors
LegalTrademarks   :
PrivateBuild      :
SpecialBuild      :
FileVersionRaw    : 1.2.0.246
ProductVersionRaw : 1.2.0.0

PS C:\Users\anne\.nuget\packages\sharpziplib\1.3.0\lib\net45> (Get-Item -Path '.\ICSharpCode.SharpZipLib.dll').VersionInfo | Format-List -Force


OriginalFilename  : ICSharpCode.SharpZipLib.dll
FileDescription   : ICSharpCode.SharpZipLib
ProductName       : ICSharpCode.SharpZipLib
Comments          : SharpZipLib (#ziplib, formerly NZipLib) is a compression library for Zip, GZip, BZip2, and Tar written entirely in C# for .NET. It is implemented as an assembly
                    (installable in the GAC), and thus can easily be incorporated into other projects (in any .NET language)
CompanyName       : ICSharpCode
FileName          : C:\Users\anne\.nuget\packages\sharpziplib\1.3.0\lib\net45\ICSharpCode.SharpZipLib.dll
FileVersion       : 1.2.0.8
ProductVersion    : 1.3.0+8f7d89201afa13c814f9b3d1813884ffe0ec7025
IsDebug           : False
IsPatched         : False
IsPreRelease      : False
IsPrivateBuild    : False
IsSpecialBuild    : False
Language          : Language Neutral
LegalCopyright    : Copyright © 2000-2020 SharpZipLib Contributors
LegalTrademarks   :
PrivateBuild      :
SpecialBuild      :
FileVersionRaw    : 1.2.0.8
ProductVersionRaw : 1.3.0.0
```

**Comment by Numpsy** [comment]
looks like #520 changed ```AssemblyVersion``` from 1.2.0.7 to 1.3.0.8 and ```FileVersion``` from 1.2.0.7 to 1.2.0.8, which sounds like an oversite to me

**Comment by piksel** [comment]
Yeah, that was my mistake. The correct version should be 1.3.0.8 (the last digit was taken from the CI build number earlier instead of the release number).
I will try to get `v1.3.1.9` out soon.

**Comment by dittodhole** [comment]
Thanks for the prompt follow up guys! Much appreciated!<3

**Comment by dittodhole** [comment]
As a "workaround" I've set `REINSTALLMODE` to [`amus`](https://docs.microsoft.com/en-us/windows/win32/msi/reinstallmode), like so:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product ...>

    <Package .../>

    <Property Id="REINSTALLMODE" Value="amus"/>

    <.../>

  </Product>
</Wix>
```

**Comment by sheitmann** [comment]
> 
> 
> Yeah, that was my mistake. The correct version should be 1.3.0.8 (the last digit was taken from the CI build number earlier instead of the release number).
> I will try to get `v1.3.1.9` out soon.
when is soon? facing the msi problem now too :(

**Comment by piksel** [comment]
@sheitmann The last digit is not a separate version, it's only a rolling release counter since FileVersion and AssemblyVersion has to be 4 numbers.

**Comment by sheitmann** [comment]
@piksel 
ok.

**Comment by dittodhole** [comment]
> > Yeah, that was my mistake. The correct version should be 1.3.0.8 (the last digit was taken from the CI build number earlier instead of the release number).
> > I will try to get `v1.3.1.9` out soon.
> 
> when is soon? facing the msi problem now too :(
> btw msi installer only recognizes the first 3 number to determine if it should update an file. see https://docs.microsoft.com/en-us/windows/win32/msi/productversion for reference.
> so 1.3.1.10 will not update 1.3.1.9 because it only sees 1.3.1 in both cases. So you should consider to change your versioning to semver which is using MAJOR.MINOR.PATCH to make us msi users happy. :)
> 
> I added a new issue #535

**Comment by piksel** [comment]
Version 1.3.1 was just released. It's `FileVersion` and `AssemblyVersion` is `1.3.1.9`
