### ISSUE TITLE
Consider using semver 2.0 for versioning

### ISSUE THREAD

**Issue by sheitmann** [icsharpcode/SharpZipLib#535]
this is a floow up from the issue #527

I use the assembly in a msi installer. The msi installer is doing major updates and for this it checks the version of the dlls to decide if an update is required. the msi installer is using the first three numbers of the version. see https://docs.microsoft.com/en-us/windows/win32/msi/productversion for reference.

So it would be great if you switch to the MAJOR.MINOR.PATCH versioning.

**Comment by piksel** [comment]
We are using Semver 2 versioning. I am not sure what you want us to change?

**Comment by sheitmann** [comment]
Yes, you use semver for the nuget package version, but not for the assembly version / product version.
Because this can cause some issues, lets say you publish 1.2.9.1 and later 1.2.9.2, there is no way to update this with msi.

**Comment by piksel** [comment]
Yeah, exactly. The nuget version is set automatically on build, but the Assembly/FileVersion were manually added, but I will make sure it's set in the CI for the next release.

**Comment by sheitmann** [comment]
Thanks. You can close this issue. 🙂

**Comment by dittodhole** [comment]
fyi - you can adapt `REINSTALLMODE` like so https://github.com/icsharpcode/SharpZipLib/issues/527#issuecomment-709870841 to force an overwrite regardless of the version installed.

**Comment by sheitmann** [comment]
> 
> 
> fyi - you can adapt `REINSTALLMODE` like so [#527 (comment)](https://github.com/icsharpcode/SharpZipLib/issues/527#issuecomment-709870841) to force an overwrite regardless of the version installed.

Thanks for the tip. 👍 
However we have a large installer and when only a few files changed the reduced install time is a real benefit.
I created a new fixed package for me that works so far. Just have to replace it in the near future with an official one. 😃
