### ISSUE TITLE
Random() is not secure because it provides insufficient entropy. CWE ID 331.

### ISSUE THREAD

**Issue by tdhintz** [icsharpcode/SharpZipLib#536]
### Steps to reproduce
1. Static code security scan.  Example:
```
		private static void WriteEncryptionHeader(Stream stream, long crcValue)
		{
			byte[] cryptBuffer = new byte[ZipConstants.CryptoHeaderSize];
			var rnd = new Random();
			rnd.NextBytes(cryptBuffer);
			cryptBuffer[11] = (byte)(crcValue >> 24);
			stream.Write(cryptBuffer, 0, cryptBuffer.Length);
		}
```

### Expected behavior
Replace all uses of System.Random() with a cryptographic version such as that provided by RNGCryptoServiceProvider.

### Actual behavior
SharpZipLib fails security scans.

### Version of SharpZipLib
1.3.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
The referenced code is this:
https://github.com/icsharpcode/SharpZipLib/blob/716b91307de9bc4acd5701e2bc75a4f6360fdb4a/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L3727

But the same method is also used in:
https://github.com/icsharpcode/SharpZipLib/blob/9e027502d1aaca863d9035deac1ec320c0e6f31f/src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs#L629

**Comment by tdhintz** [comment]
There are possibly 3 uses of the insecure Random() found throughout the codebase.
