### ISSUE TITLE
Does not extract folders correctly in OSX (Mono)

### ISSUE THREAD

**Issue by augiem** [icsharpcode/SharpZipLib#54]
A zip file containing a single .bundle package (essentially a folder structure) when unzipped using Libraries.ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip extracts incorrectly in OSX, but works in Windows.

The resulting unzip extracts all files inside the .bundle package as files named for the folders they were in. For example, a .bundle containing 3 files which should be extracted to a single .bundle file will instead be extracted as follows:

name.bundle/Contents/MacOS/name
name.bundle/Contents/Resources/en.lproj/InfoPlist.strings
name.bundle/Contents/Info.plist

Keep in mind these are not folders being created -- its creating 3 files with the folder structure baked into their names.

I haven't tested a regular compressed folder, but .bundles are not being extracted correctly.

EDIT: Same problem happens with regular directories not in a bundle.

I've determined its because it's using "\" for the directory separator char instead of Path.DirectorySeparatorChar throughout due to the processing by the WindowsNameTransform class.

**Comment by McNeight** [comment]
This issue was resolved when PR #65 was merged into master at e01215507cf25a5978a0bd850c9e67dbabf515b7

-Neil
