### ISSUE TITLE
Build warnings: Assembly has non matching file name

### ISSUE THREAD

**Issue by StephenHodgson** [icsharpcode/SharpZipLib#540]
### Steps to reproduce
1. Import SharpZipLib in Unity package Manager
2. Switch to windows build target
3. Build

### Expected behavior
No warnings when building 

### Actual behavior
```
Assembly 'ICSharpCode.SharpZipLib' has non matching file name: 'SharpZipLib.dll'. This can cause build issues on some platforms.
```

### Version of SharpZipLib
1.2.2-preview.1

### Obtained from (only keep the relevant lines)
- Package installed using UPM

**Comment by Numpsy** [comment]
I'm not sure what that means - the official builds should have the file name ```ICSharpCode.SharpZipLib.dll``` already.
Also not sure where version 1.2.2 comes from  - the official releases are just 1.2.0 and 1.3.0.

**Comment by StephenHodgson** [comment]
Ah I see. [It seems Unity write their own wrapper](https://github.com/Halodi/halodi-unity-package-registry-manager/pull/21#issuecomment-723995659)

https://github.com/needle-mirror/com.unity.sharp-zip-lib

**Comment by StephenHodgson** [comment]
Sorry I thought the upm package came directly from this repository.

**Comment by piksel** [comment]
@StephenHodgson I were looking into providing a Unity package, but since there doesn't seem to be any "default" package source (like nuget.org) I dropped it.
I'm also not too thrilled about them using different versioning. Perhaps there is a good reason?
But yeah, their package seem to build from our source but then rename the output assembly for whatever reason.

**Comment by StephenHodgson** [comment]
Check out [OpenUPM](https://openupm.com/). It's a good up and coming default package source. Also you can host directly on npm for upm packages.

OpenUPM uses GitHub directly as the source and just caches as needed.

> I'm also not too thrilled about them using different versioning. Perhaps there is a good reason?
Yeah doesn't surprise me that Unity is doing their own thing. They like to recycle good developer work with their subpar crap.

**Comment by piksel** [comment]
I tried created a branch for UPM, and adding it works in Unity using this URL: `https://github.com/icsharpcode/SharpZipLib.git#upm`

I also managed to add [v1.3.1 to OpenUPM](https://openupm.com/packages/org.icsharpcode.sharpziplib/?subPage=versions).
Not sure if this is a good way to do it, but it does seem to work. 🤷‍♀️
