### ISSUE TITLE
Avoid Path.GetTempFileName() due to CWE 377 in TarArchive.cs.

### ISSUE THREAD

**Issue by tdhintz** [icsharpcode/SharpZipLib#543]
### Steps to reproduce
1. Static code security scan line 827 TarArchive.cs. Example:
https://github.com/icsharpcode/SharpZipLib/blob/b7bc4e08620f4410b721a3bd59fe53537f774909/src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs#L823-L831

### Expected behavior
Use sufficiently random names for temporary files to prevent attacks which can predict the name of the file. For example, a Guid or crypto generated random number.

### Actual behavior
Security scan failure. #537  

### Version of SharpZipLib
1.3.1

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
Yeah, not sure how I didn't catch that.
