### ISSUE TITLE
Zip64 Archive cannot be updated

### ISSUE THREAD

**Issue by ghost** [icsharpcode/SharpZipLib#59]
The code from https://github.com/icsharpcode/SharpZipLib/wiki/Updating will not work if a Zip64 archive is used. 

Instead the following error will occur:
ZipException: "Extra data extended Zip64 information length is invalid"
or alternatively (if zipFile.CommitUpdate() is executed in QuickWatch):
"BeginUpdate has not been called"

it works fine if a Zip file which was generated with UseZip64.Off is being updated.

**Comment by tinygipxy** [comment]
I got same issue, any update for this ?

**Comment by Numpsy** [comment]
fixed by #314 ?

**Comment by oporko** [comment]
I had the same issue with 1.1.0, it is fixed in 1.2.0.

**Comment by piksel** [comment]
I think so. We can reopen (or create a new one) if this resurfaces.
