### ISSUE TITLE
GZipOutputStream.Password doesn't work

### ISSUE THREAD

**Issue by proy27** [icsharpcode/SharpZipLib#590]
### Expected behavior
GZipOutputStream.Password doesn't work

### Actual behavior
Tell us what happens instead

### Version of SharpZipLib
1.3.1
### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
Please fill out the issue template. You are currently claiming that you don't expect it to work (whatever that even means).

The GZip format does not support encryption, so I am not even sure what you are trying to do...

**Comment by Numpsy** [comment]
It *does* seem a bit unfortunate that ```DeflaterOutputStream``` has a public ```Password``` property, given that the encryption it refers to only actually applies to zip files (and the doc comments on the property don't say anything to that effect, so that might be misleading?)

**Comment by Numpsy** [comment]
Fixed by #604 ?
