### ISSUE TITLE
Uncompilable Code in Unzip example on Wiki

### ISSUE THREAD

**Issue by ChettDM** [icsharpcode/SharpZipLib#596]
### Steps to reproduce
1. Navigate to the wiki page titled: Unpack a Zip with full control over the operation
2. Read through the first C# example (I've provided a screen shot below.)

![image](https://user-images.githubusercontent.com/9888661/110574788-67307700-8123-11eb-9052-5fff6da51c96.png)

The variable name `fs` should be named `fsInput`

**Comment by piksel** [comment]
Yeah, and also there is a missing type declaration on the next line. Fixed! Thanks.
