### ISSUE TITLE
Abort a zipping process.

### ISSUE THREAD

**Issue by mdeangelo-CT** [icsharpcode/SharpZipLib#597]
### Expected behavior
Create a method to abort zipping in FastZip. As seen in issue #373, we see that it is unsafe to abort a running thread. Could we implement a method that could safely abort the zipping process?

### Version of SharpZipLib
1.3.1

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
You can use the `ZipFile.CompletedFileHandler` event and cancel the compression there if you want, something like:

```cs
var fastZip = new FastZip(new FastZipEvents() {
    CompletedFile = (_, args) => { 
        args.ContinueRunning = !aborted;
    }
});

fastZip.CreateZip(zipFileName, sourceFolderPath, true, "");
```

Not that this is single threaded, so if you want to listen for some kind of external event you probably have to do threading and sync/lock
