### ISSUE TITLE
Bug: ZipFile does not release Handle on File

### ISSUE THREAD

**Issue by RazStorm** [icsharpcode/SharpZipLib#60]
When modifying a Filestream the zipFile keeps a handle after closing. The following code results in a System.IO.Exception when File.Delete is executed:

```
    using (FileStream msZip = File.Open("FILELOCATION", FileMode.Open)) {
      using (ZipFile zipFile = new ZipFile(msZip)) {
      zipFile.IsStreamOwner = false;

      zipFile.BeginUpdate();
      // DO SOMETHING

      // commit and close
      zipFile.CommitUpdate();
      zipFile.Close();
      }
      msZip.Close();
    }
    File.Delete("FILELOCATION");
```

A temporary fix is setting the  zipFile.IsStreamOwner = true, which will actually release the file handle.

**Comment by piksel** [comment]
This would suggest that `FileStream.Dispose()` does not close the file handle, which it does.

Either this is invalid or something has changed since the this was filed.
