### ISSUE TITLE
UnZip Failed

### ISSUE THREAD

**Issue by LiShiFeng6688** [icsharpcode/SharpZipLib#613]
### Steps to reproduce
Canon CR3 Format Unzip is unusable

### Expected behavior
Canon CR3 Format Unzip is unusable

### Version of SharpZipLib
1.3.1

**Comment by piksel** [comment]
Sorry, I have no idea what you are talking about. Please update the ticket with reproduceable steps.

**Comment by LiShiFeng6688** [comment]
Dear Piksel:
    Sorry,this question has been resolved.Thanks
