### ISSUE TITLE
EndOfStream bug in LZWInputStream

### ISSUE THREAD

**Issue by mr-miles** [icsharpcode/SharpZipLib#63]
Hi,

At the end of the stream, LZWInputStream returns -1 as the bytes read, which makes any stream reader throw an exception.  The ReadToEnd() call on the streamreader always throws as per this test (with any LZW compressed file):

            using (var file = new FileStream(testFile, FileMode.Open))
            using (var lzw = new LzwInputStream(file))
            using (var reader = new StreamReader(lzw))
            {
                reader.ReadToEnd();
            }

The same test using this class can successfully read the stream:

    public class FixedLzwInputStream : LzwInputStream
    {
        public FixedLzwInputStream(Stream baseInputStream)
            : base(baseInputStream)
        { }

        public override int Read(byte[] buffer, int offset, int count)
        {
            var res = base.Read(buffer, offset, count);
            return res == -1 ? 0 : res;
        }
    }

It took me ages to work out what was going on ... and I found there is a pull request to fix this:
https://github.com/icsharpcode/SharpZipLib/pull/10

Please could it be merged?  I can contribute a test for this if that is currently a blocker

**Comment by jfreilly** [comment]
This is a little tricky in that the code was dumped in by me but the licensing for the source code was never sorted out.  It was never included in the project and never tested.  It was in the todo list which never got done  The fix itself is trivial so could be done but the licensing issue may be harder to sort out.

**Comment by mr-miles** [comment]
I see: you do know it's included in the nuget package?

**Comment by jfreilly** [comment]
No I had nothing to so with the nuget package

**Comment by McNeight** [comment]
@christophwille 

I'm not sure what licensing issue @jfreilly is referring to, but it might be about the expired LZW patent?

-Neil

**Comment by christophwille** [comment]
To me @jfreilly (please chime in) the license comment seems like the code file's origins were never of the proper license (and the file was intended for reference initially).

**Comment by jfreilly** [comment]
The code originates from an email whose origins are unknown.

**Comment by McNeight** [comment]
Then, going forward, should we just delete this code completely?

**Comment by jfreilly** [comment]
Yes it's the only real option I think.

Cheers john.

**Comment by McNeight** [comment]
Perhaps not. After a bit of digging through Google, it would appear I've found the source of the source.

* http://stackoverflow.com/questions/4544066/is-there-a-library-to-unzip-z-files-using-vb-net
  * http://ebixio.com/blog/2009/12/06/uncompressing-unix-z-files/
    * http://ebixio.com/blog/wp-content/uploads/2009/12/LzwInputStream.cs

Now, if the magic incantation of @gburca works correctly, then perhaps we may even get this bit of code relicensed to MIT as per issue #103.

-Neil

**Comment by jfreilly** [comment]
Ok sounds cool, nice digging.

**Comment by gburca** [comment]
I'm fine with releasing it under MIT. What's the best way of doing that? Should I modify the copyright and send a pull request?

**Comment by gburca** [comment]
Looks like @McNeight modified the copyright in https://github.com/icsharpcode/SharpZipLib/commit/3fae4cfa7524b9a357a69cd324bc520d114665a4. While I'm OK with licensing the code under MIT, I'm NOT OK with relinquishing the copyright.

**Comment by McNeight** [comment]
@gburca

No one has relinquished copyright. The main contributors, myself included, have signed a [Joint Copyright Assignment](http://www.icsharpcode.net/TechNotes/JointCopyrightAssignment.pdf), under which each contributor continues to own the copyright on their contribution.

@christophwille has been leading the effort to relicense to MIT. We have an open issue for obtaining the proper rights in order to relicense [here](https://github.com/icsharpcode/SharpZipLib/issues/103#issuecomment-206696820). Up until now, the only thing he has required from patch contributors (>5 lines) is the following statement:

_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

With all that said, your contribution is fairly sizeable. I don't know where the line is between needing a signed JCA and simply adding the above statement. Before I do anything, I'd prefer that Chris respond first.

-Neil

**Comment by christophwille** [comment]
Even in SharpDevelop, PRs only require that paragraph. Contributors with full commit permission to the repository are asked for the JCA, simply so we have full documentation on their work (otherwise it would be kind of hard to track).

**Comment by McNeight** [comment]
If I am understanding it correctly then, I think what we would like is for @gburca to fork, make a slight modification to the three LZW files, and the submit a PR with the statement in the comment. If we wanted to be pedantic about it, we could delete the files in our repository, and then have him submit a PR to include them again. 

Either way, the repository history will remember and track his contribution, he will have verified his claim to the code, maintaining his copyright on it, and we will be able to include it under the MIT license.

Simple enough, eh?

**Comment by McNeight** [comment]
@gburca

Please let us know if you would like to switch your code to the MIT license and contribute to the project. If we don't receive a response from you soon, your code will be deleted from the repository and this issue will be closed out.

-Neil

**Comment by McNeight** [comment]
With the change in license to MIT, as well as the new copyright statement ("﻿Copyright © 2000-2016 SharpZipLib Contributors"), I am going to consider the statement above by @gburca that "While I'm OK with licensing the code under MIT, I'm NOT OK with relinquishing the copyright." as permission to include the LZW code as part of the SharpZipLib distribution.

Gabriel,

Thanks for taking the time to respond, and thank you for your contribution.

-Neil
