### ISSUE TITLE
Get SharpZipBaseException when set ZipInputStream.Password to "000671" 

### ISSUE THREAD

**Issue by leeveel** [icsharpcode/SharpZipLib#643]
### Steps to reproduce
1.    ZipInputStream s = new ZipInputStream(File.OpenRead("test.zip"));
2.    s.Password = "000671";    //the correct password of test.zip is 123456
3.    s.Read()  

### Expected behavior
Unhandled exception. ICSharpCode.SharpZipLib.Zip.ZipException: Invalid password

### Actual behavior
Unhandled exception. ICSharpCode.SharpZipLib.SharpZipBaseException: Illegal rep dist code
       at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.DecodeHuffman()
       at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Decode()
       at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Inflate(Byte[] buffer, Int32 offset, Int32 count)

### Version of SharpZipLib
Version="1.3.2"

**Only this string(000671) will get SharpZipBaseException, Is it special?**

**Comment by piksel** [comment]
Well, the way the password is checked is that it's checked against a 1-byte CRC:
https://p1k.se/appnote.md#s616-decrypting-the-encryption-header

That means that there is 1 in 255 chance of a wrong password is not detected. That means that the "decrypted" archive will just appear to be corrupted instead.

**Comment by leeveel** [comment]
@piksel thanks

**Comment by leeveel** [comment]
@piksel How to check a password is correct?
