### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by 792747481** [icsharpcode/SharpZipLib#647]
### Steps to reproduce
1.decompression buffer
2.Unity 2018
3.

### Expected behavior
```
     GZipInputStream gZipInputStream = new GZipInputStream(new MemoryStream(bytes));
            MemoryStream outStream = new MemoryStream();
            try
            {
                int count = 0;
                byte[] data = new byte[256];

                while ((count = gZipInputStream.Read(data, 0, data.Length)) != 0)
                {
                    outStream.Write(data, 0, count);
                }
            }
            catch (Exception ex)
            {
                throw new Exception("GZipcompress error:" + ex.Message);//unexpected eof
            }

```
### Version of SharpZipLib
0.86.0

**Comment by piksel** [comment]
Don't remember if there were any quirks in v0.86
Try the latest version:
**GIT**: https://github.com/icsharpcode/SharpZipLib/tree/upm/v1.3.1
**UPM**: https://openupm.com/packages/org.icsharpcode.sharpziplib/

**Comment by 792747481** [comment]
![Gzip](https://user-images.githubusercontent.com/29562377/124899867-1c603680-e013-11eb-8c6e-afb584ed982c.png)
![Gzip_code](https://user-images.githubusercontent.com/29562377/124900289-84af1800-e013-11eb-826d-d1bc0c256446.jpg)

**Comment by 792747481** [comment]
In no case can Available be less than 0

**Comment by piksel** [comment]
What this means is that when it's trying to decompress the data, it reaches a point where there needs to be more data to fully decompress, but it reaches the end of the file. 

I would guess that one of three things causes this:
1. The .gz file is corrupt (if you could attach a problematic file I can analyze it)
2. Something is going wrong with the buffering/stream, is the above the source for `UnZipStream`?
   Also, is it in Zip or GZip format? `UnZipStream` seems to point to Zip, but `GZipInputStream` is for GZip.
3. Some error in the old 0.86 code (it was released 10 years ago!)

**Comment by 792747481** [comment]
1.





2.

3.





If you have some spare time！
Check the source code！
I'm sorry, I can't provide the problem file right now！
I unzipped a base64 JSON stream
Unexpected EOF cannot be run after looking at the source code







发件人:                                                                                                                        "icsharpcode/SharpZipLib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月8日(星期四) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [icsharpcode/SharpZipLib] Unexpected EOF (#647)





 
What this means is that when it's trying to decompress the data, it reaches a point where there needs to be more data to fully decompress, but it reaches the end of the file.
 
I would guess that one of three things causes this:
  
The .gz file is corrupt (if you could attach a problematic file I can analyze it)
 
Something is going wrong with the buffering/stream, is the above the source for UnZipStream?
 Also, is it in Zip or GZip format? UnZipStream seems to point to Zip, but GZipInputStream is for GZip.
 
Some error in the old 0.86 code (it was released 10 years ago!)
