### ISSUE TITLE
SharpZipLib creates invalid tar.gz

### ISSUE THREAD

**Issue by trampster** [icsharpcode/SharpZipLib#652]
### Steps to reproduce

Run the following code (I'm using blazor)
```
    public byte[] CreateTarGZ()
    {
        using (var outStream = new MemoryStream())
        using (var gzoStream = new GZipOutputStream(outStream))
        using (var tar = new TarOutputStream(gzoStream, Encoding.ASCII))
        using (var tarArchive = TarArchive.CreateOutputTarArchive(tar))
        {
            tarArchive.RootPath = "MyFolder";
            var fileContents = Encoding.UTF8.GetBytes("This is my file");
            var tarEntry = TarEntry.CreateTarEntry("MyFile.txt");
            tarEntry.Size = fileContents.Length;
            tar.PutNextEntry(tarEntry);
            tar.Write(fileContents, 0, fileContents.Length);
            tar.CloseEntry();
        
            tar.Flush();
            outStream.Position = 0;
            return outStream.ToArray();
        }
    }
```

### Expected behaviour
A valid tar.gz is create and can be decompressed

### Actual behaviour
I'm on Ubuntu, if I right click the file and click 'Extract here' I get the following error:
`'file.tar.gz':` truncated gzip input

### Version of SharpZipLib
1.3.2
Used form .net 5 on blazor server on linux

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
Don't use both TarArchive and TarOutputStream.

**Comment by piksel** [comment]
I guess this was solved as well (only read the discussion just now).

**Comment by trampster** [comment]
I'm confused.

Should I stop using the TarArchive or the TarOutputStream?

If I stop using the tarArchive how do I set the RootPath

If I stop using the TarOutputStream  how do I write the tar entry from a byte array.

**Comment by trampster** [comment]
I tried without the TarArchive, but that results in exactly the same error.

I tried removing the TarOutputStream and using tarArchive.WriteEntry but that results in System.ArgumentNullException: Path cannot be null. When calling WriteEntry. TarEntry doesn't seem to have a path property, I also cannot see any way of writing the content.  TarEntry doesn't seem to have anyway of setting the content.

**Comment by trampster** [comment]
So I've looked at the SarpZipLib source code for WriteEntry and it uses TarEntry.File property which is a file name. It reads the contents from the file system. I cannot do this, I'm running on blazor and need to create the file form a byte array, I don't have a file.

So this means I need to use TarOutputStream. Here is my code which still results in an invalid archive: 

```
            using (var outStream = new MemoryStream())
            using (var gzoStream = new GZipOutputStream(outStream))
            using (var tar = new TarOutputStream(gzoStream, Encoding.ASCII))
            {
                var fileContents = Encoding.UTF8.GetBytes("This is my file");
                var tarEntry = TarEntry.CreateTarEntry("MyFile.txt");
                
                tarEntry.Size = fileContents.Length;
                tarEntry.Name = "MyFile.txt";

                tar.PutNextEntry(tarEntry);
                tar.Write(fileContents, 0, fileContents.Length);
                tar.CloseEntry();
                tar.Flush();

                outStream.Position = 0;
                return outStream.ToArray();
            }
```

**Comment by trampster** [comment]
I;vve attached the bad tar file
[test.tar.gz](https://github.com/icsharpcode/SharpZipLib/files/6951766/test.tar.gz)

**Comment by piksel** [comment]
> WriteEntry [..] uses TarEntry.File property which is a file name. It reads the contents from the file system. I cannot do this

That is exactly why TarOutputStream exists 😁

> If I stop using the tarArchive how do I set the RootPath

RootPath is only relevant if you are reading files from a file system (and need to remove a path prefix).

> Here is my code which still results in an invalid archive

You are not flushing the gzip stream before reading.
This should work:

```cs
using (var outStream = new MemoryStream()){
	  using (var gzoStream = new GZipOutputStream(outStream))
	  using (var tar = new TarOutputStream(gzoStream, Encoding.ASCII))
	  {
          // Prevent closing of the memory stream
          gzoStream.IsStreamOwner = false;

	      var fileContents = Encoding.UTF8.GetBytes("This is my file");
	      var tarEntry = TarEntry.CreateTarEntry("MyFile.txt");
	      
	      tarEntry.Size = fileContents.Length;
	      tarEntry.Name = "MyFile.txt";
	  
	      tar.PutNextEntry(tarEntry);
	      tar.Write(fileContents, 0, fileContents.Length);
	      tar.CloseEntry();
	  }
	  outStream.Position = 0;
	  return outStream.ToArray();
}
```

**Comment by trampster** [comment]
Yes that works.

 I tried adding a gzoStream.Flush() instead of nested usings but that wasn't enough. There must be something that dispose does that flush doesn't that is necessary in this case.

**Comment by piksel** [comment]
Yeah, flushing just makes sure all pending writes are passed through, but leaving the stream writable. Tar archives ends with two null blocks, so you need to close the stream to actually make it a valid archive. There may be some equivalent finishing required for gzip, but I always close them to properly indicate the end of the stream.
