### ISSUE TITLE
An extra flag may be set in the "Include" flag in the "ExtendedUnixData" class.

### ISSUE THREAD

**Issue by rougemeilland** [icsharpcode/SharpZipLib#655]
It may be a format violation of the original ZIP file, but I'm dissatisfied with the behavior of "SharpZipLib" for such files, so I'd like to report the details.
Since such a ZIP file actually exists in the file that can be downloaded from a certain e-book sales site even now, there may be software that compresses it like this.

### Steps to reproduce
1. Create a ZIP file with an entry containing "extra field 0x5455 (extended timestamp)". At that time, the first byte of the extra field should have all bits 0-2 set, and the length of the extra field should be 5 bytes.
2. Read the ZIP file with "SharpZipLib" and use the "ExtendedUnixData" class to read the entry "extra field 0x5455". Specifically, run the following code.

```c#
var zipFilePath = @"(zip file path)";
using (var zipFile = new ZipFile(zipFilePath))
{
    foreach (ZipEntry entry in zipFile)
    {
        DateTime? modificationTime = null;
        DateTime? createTime = null;
        DateTime? accessTime = null;
        using (var extraData = new ZipExtraData(entry.ExtraData))
        {
            var unixExtraData = extraData.GetData<ExtendedUnixData>();
            if (unixExtraData != null && (unixExtraData.Include & ExtendedUnixData.Flags.ModificationTime) != 0)
                modificationTime = unixExtraData.ModificationTime;
            if (unixExtraData != null && (unixExtraData.Include & ExtendedUnixData.Flags.CreateTime) != 0)
                createTime = unixExtraData.CreateTime;
            if (unixExtraData != null && (unixExtraData.Include & ExtendedUnixData.Flags.AccessTime) != 0)
                accessTime = unixExtraData.AccessTime;
        }
        if (modificationTime.HasValue == true && modificationTime.Value.Kind == DateTimeKind.Unspecified)
            throw new Exception("unexpected! (ModificationTime is invalid )");
        if (createTime.HasValue == true && createTime.Value.Kind == DateTimeKind.Unspecified)
            throw new Exception("unexpected! (CreateTime is invalid )"); // I got an exception here
        if (accessTime.HasValue == true && accessTime.Value.Kind == DateTimeKind.Unspecified)
            throw new Exception("unexpected! (AccessTime is invalid )");
    }
}
```

### Expected behavior
In the "ExtendedUnixData" class, if any of ModificationTime / CreateTime / AccessTime is meaningless, please reset the corresponding "Include" flag.

### Actual behavior
In the "ExtendedUnixData" class, even if any of ModificationTime / CreateTime / AccessTime is meaningless, the corresponding "Include" flag may be set.
In this case, the "CreateTime" flag was set in the "Include" flag, so when I read the "CreateTime" property, the value of the "Kind" property of the read value ("DateTime" class) was "DateTimeKind.Unspecified". And the date and time was "1970-01-01 00:00:00".

### Version of SharpZipLib
SharpZipLib 1.3.2

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
What do you mean by "meaningless"? 
```cs
createTime.Value.Kind == DateTimeKind.Unspecified
```

DateTimeKind just declares whether it is relative to UTC or local time, setting it to `Unspecified` means that "we" don't know and the consumer reading the time needs to adjust it accordingly.
https://docs.microsoft.com/en-us/dotnet/api/system.datetimekind?view=net-5.0#fields

But I *think* I know what you mean, the extended unix data does not have a `CreateTime` field, so whatever it's doing with that flag, it's bound to be wrong.
https://p1k.se/appnote.md#s457--unix-extra-field-0x000d

**Comment by rougemeilland** [comment]
I'm sorry, I seem to have misunderstood.
When I referred to the "Extended Timestamp Extra Field" section of the document below, it was exactly what you said.
https://opensource.apple.com/source/zip/zip-6/unzip/unzip/proginfo/extra.fld

I would like to consider if there is any other alternative.
Thank you for your answer.
