### ISSUE TITLE
C# code: I'm using sharpziplib.dll to compress bitmap to byte [], and I want to know how to use JavaScript to decompress byte []

### ISSUE THREAD

**Issue by xiaogao2021** [icsharpcode/SharpZipLib#658]
C# code:
```cs
      public static byte[] Compress(byte[] pBytes)
        {
            MemoryStream mMemory = new MemoryStream();
            Deflater mDeflater = new Deflater(Deflater.BEST_COMPRESSION);
            using (DeflaterOutputStream mStream = new DeflaterOutputStream(mMemory, mDeflater, 131072))
            {
                mStream.Write(pBytes, 0, pBytes.Length);
            }

            return mMemory.ToArray();
        }
```
I transmit the byte array to the web page through websocket, but the problem now is that I need to unzip the byte array. I want to know how to do it?

**Comment by SpiritBob** [comment]
> If you use the bare `DeflaterOutputStream` to compress, you can use `InflaterInputStream` to decompress.
> 
> Is that not working? Or is it more a generic question about the format of the byte stream?

I think he's asking how to do it in Javascript code, which has no access to any C# classes like `InflaterInputStream`?

**Comment by piksel** [comment]
Perhaps. If that's the case, feel free to open a discussion for it, but I don't think it's in the scope of this project, sorry.
