### ISSUE TITLE
Efficient way to test if a TarInputStream is a valid stream to a Tar archive?

### ISSUE THREAD

**Issue by SpiritBob** [icsharpcode/SharpZipLib#661]
First thing that comes to mind is to simply extracting every `TarEntry` in the archive. But is there a solution without actually extracting any data? For example - would listing all of the tar entries via `TarInputStream.GetNextEntry()` be sufficient for validating if the stream is indeed a stream to a valid Tar archive?

**Comment by piksel** [comment]
Yeah, I think that would be the easiest test. There isn't much else to verify in tar files except for the header CRC and content lengths, both of which are verified by iterating over the entries.

**Comment by SpiritBob** [comment]
Thanks for the prompt response! Closing this issues as I believe it is resolved.
