### ISSUE TITLE
DosTime gets corrupted

### ISSUE THREAD

**Issue by Temtaime** [icsharpcode/SharpZipLib#677]
### Steps to reproduce
1. var e = new ZipEntry("file.txt"); 
2. e.DosTime = 0;
3. Console.WriteLine(e.DosTime);

### Expected behavior
Zero printed

### Actual behavior
2162688 printed

### Version of SharpZipLib
Latest

### Obtained from
- Package installed using NuGet

Why the library changes passed values ?
It shouldn't.

**Comment by piksel** [comment]
What time would say that `0` represents? That is not a valid DosTime (as it would be the 0th day of the 0th month 1980). So the value returned from `DosTime {get}` is the lowest valid DosTime: `1980-01-01 00:00:00`.
