### ISSUE TITLE
ZipOuputStream does not support writing custom entries

### ISSUE THREAD

**Issue by Temtaime** [icsharpcode/SharpZipLib#682]
### Steps to reproduce
1. Create ZipEntry and set Crc, CompressedSize, Size and CompressionMethod(Deflate).
2. Try to write deflated stream to zip.

### Expected behavior
Archive is created from compressed data.

### Actual behavior
There are plently of checks for crc/size/compressed size and many of them are wrong for such a case, also library tries to compress futher compressed stream.

### Version of SharpZipLib
Latest

**Comment by piksel** [comment]
This is not how `ZipOutputStream` is designed to work. Do you have a specific use case?
Adding a new state and custom logic for this adds to the complexity and maintenance cost, and would need to be fully covered by tests...

**Comment by Temtaime** [comment]
Ok, i'll add some tests.
It can be used to serve files from webserver that are stored already precompressed to avoid CPU resources on compression

**Comment by piksel** [comment]
Okay, so for combining a variable set of files into a single download by creating a ZIP archive on-the-fly?

**Comment by Temtaime** [comment]
Exactly, i was using my own solution, but found this library with rich functional and found that adding this possibility into existing codebase should not be a problem
