### ISSUE TITLE
[Proposal] Add a helper method to get the Unix file permissions off of ZipEntry

### ISSUE THREAD

**Issue by IvanLH** [icsharpcode/SharpZipLib#691]
### Steps to reproduce
1. Zip a file on Linux using Info-Zip
2. Unzip using the library
3. There's no easy or well documented way to retrieve the file permissions whose structure is this: https://unix.stackexchange.com/questions/14705/the-zip-formats-external-file-attribute

### Expected behavior
I am proposing to add a method called int GetUnixStyleFilePermissions() to ZipEntry which will get the necessary bits and return them as int.

### Actual behavior
No such functionality exists

### Version of SharpZipLib
1.2.0
### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
`ZipEntry.ExternalFileAttributes` is what you are looking for.
