### ISSUE TITLE
NPOI 2.5.5 INTERNALY using SharpZipLib 1.3.2 version but SharpZipLib 1.3.2 flaged by blackduck as security vunerbilty

### ISSUE THREAD

**Issue by Sureshrcm09** [icsharpcode/SharpZipLib#725]
If i change SharpZipLib to 1.3.3 NPOI packege is not working.but Npoi using 1.3.2 SharpZipLib which is a security vuneable by blackduck tool.

**Comment by piksel** [comment]
NPOI does not use the affected parts of SharpZipLib (tar archives) AFAIK (since it deals with zip files). In any case, we can't do anything about what version they are using internally.
