### ISSUE TITLE
When I build the project the dll is not copied

### ISSUE THREAD

**Issue by sonomirco** [icsharpcode/SharpZipLib#726]
### Steps to reproduce
Building project solution in 4.8NetFramework.

### Expected behavior
I am expecting the DLL to be copied into the build folder, like all the other references.
If I revert to version 1.3.2.10 the DLL is copied.

### Actual behavior
The DLL is not copied

### Version of SharpZipLib
1.3.3.11

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
This is how I interpret your  issue:
 - You have a .NET project, targeting .NET Framework 4.8
 - You have added `SharpZipLib` as a package reference
 - When building your project, the `bin/Debug/` (or equivalent) folder does not contain `ICSharpCode.SharpZipLib.dll`

If this is correct, then
  1.  Does your project still build? Any errors?
  2.  If it does build, does it run?
  3.  If it does run, why is this a problem?

I don't know why this would be the case, but it would help with finding a solution.

**Comment by piksel** [comment]
Couldn't you just add a reference to `NPOI` to `SandboxGh`? Or to `SharpZipLib` if that's what you want. It seems odd that msbuild wouldn't put a meta-dependency in your build directory, but you really should have explicit dependencies.

**Comment by sonomirco** [comment]
Yeah sure I can reference directly to 'SandboxGh' but this wasn't a problem using the previous version.

The project build.
The project runs.
The project runs with an error when a tool using 'NPOI' is used because the dependency is missed.

**Comment by piksel** [comment]
> When a tool using 'NPOI'

Are you using dynamic code perhaps?
That might explain why it doesn't add some dependencies, but it's not something we can control in any case.
It might have worked "by accident" before, but using explicit dependencies is always recommended. It's also a bit weird, since NPOI uses SharpZipLib v1.3.2, not v1.3.3.

**Comment by sonomirco** [comment]
Nope I am not.
But, probably is because NPOI is not using the new version that the problem occurs.
Thanks for your help, and suggestion.
