### ISSUE TITLE
Set a non-string password from byte-array

### ISSUE THREAD

**Issue by Imagine-Programming** [icsharpcode/SharpZipLib#728]
Is it possible to set the `zipFile.Password` to something other than a string? In libzip, it is possible to use any NUL-terminated char array as a password for i.e. unzipping files, however that appears to be a challenge in SharpZipLib. As the password char/byte array I'm referring to does not represent a string, encoding the array into a string yields the unwanted result of interpreting it differently than it is supposed to. 

An example password is shown below, how would one use that to decrypt an entry with SharpZipLib?

```c#
byte[] passwordData = { 
    0x90, 0xd2, 0xcf, 0x42, 0xb5, 0x4f, 0x95, 0x59, 
    0xca, 0xa7, 0x12, 0x6f, 0xaf, 0x68, 0x20, 0x53,
    0x66, 0x30, 0x30, 0xed, 0x9e, 0x43, 0x33, 0xf5, 
    0x24, 0x61, 0x6a, 0x7a, 0x6f, 0x4f, 0x33, 0x32,
    0xe4, 0x74, 0x99, 0xac, 0x21, 0x71, 0xb8, 0x7f, 
    0x53, 0x55, 0x4c, 0xf7, 0x16, 0x0c, 0x83, 0xf2, 
};
```

**Comment by Imagine-Programming** [comment]
Example zip files and passwords (md5 hash of password is filename of .zip and .cs)

[samples.zip](https://github.com/icsharpcode/SharpZipLib/files/8102505/samples.zip)

**Comment by piksel** [comment]
Yeah, that probably isn't possible right now. The library tries to be as easy to use (or hard to misuse) as possible for the generic cases, which includes having a password that is in text form. Making the password bytes public should not be too hard to implement though... but it's not possible right now.

**Comment by Imagine-Programming** [comment]
All right, thanks for your reply :) Too bad, I'd love to be able to use SharpZipLib for this!
