### ISSUE TITLE
Avoiding RegexOptions.Compiled

### ISSUE THREAD

**Issue by iivok** [icsharpcode/SharpZipLib#73]
The library works fine with Unity and .Net subset, except when trying to use filters with FastZip.CreateZip(), since NameFilter.cs uses RegexOptions.Compiled, which is not included in the .Net subset of Unity.

Is there a way to avoid using RegexOptions.Compiled while still being able to use filters?

**Comment by McNeight** [comment]
To enable the use of RegexOptions.Compiled, switch to using the full .NET 2.0 API. From the edit menu, select Project Settings -> Player then click on the Other Settings button. Under Optimization, switch the API Compatibility Level from .NET 2.0 Subset to .NET 2.0.

As I have time, I will try to find a replacement for RegexOptions.Compiled but this will at least allow the library to work.

-Neil

**Comment by Numpsy** [comment]
Is this relevant any more?
I know very little about Unity, but if it was fixed by using the full .NET 2.0, that sounds like something that would no longer be relevant?

**Comment by piksel** [comment]
I haven't tried Regex.Compiled, but I haven't found any such limitations whilst using Unity (current LTS). Should either be fixed or would need an update.
