### ISSUE TITLE
.Net 6/7 IAsyncDisposable uses wrong DisposeAsync method

### ISSUE THREAD

**Issue by roddone** [icsharpcode/SharpZipLib#730]
### Steps to reproduce
1. Create a project targeting .net 6 or higher
2. use ZipOutputStream with "await using"
3. Or call directly .DisposeAsync() on previously created ZipOutputStream

### Expected behavior
When Disposing, or calling `.DisposeAsync()`, it uses `DeflaterOutputStream.DisposeAsync()`

### Actual behavior
When Disposing, it uses the base class `Stream.DisposeAsync()`  instead of `DeflaterOutputStream.DisposeAsync()` method.
This is caused by a compilation directive `#if NETSTANDARD2_1` that does not take in consideration recent .net versions (.Net 6 and 7, and probably 5, I have not tested this version)
![image](https://user-images.githubusercontent.com/34140141/155166266-107b4e02-7578-4c61-a8b8-0b1e0cd3da48.png)

### Version of SharpZipLib
- Compiled from source (latest commit on master)

full sample to reproduce (must create a .net 6 project) : 
```csharp
using ICSharpCode.SharpZipLib.Zip;
using System.Text;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", async (HttpContext context) =>
{
	await using (var outputStream = new MemoryStream())
	{
		await using (var stream = new ZipOutputStream(outputStream))
		{
			//add file without compression
			await stream.PutNextEntryAsync(new ZipEntry("test.txt") { CompressionMethod = CompressionMethod.Stored });

			var bytes = Encoding.UTF8.GetBytes("ah ah !");
			await stream.WriteAsync(bytes);

			await stream.FinishAsync(CancellationToken.None);
			outputStream.Position = 0;
			await outputStream.CopyToAsync(context.Response.Body);
		}
	}
});

app.Run();
```

**Comment by piksel** [comment]
Good catch, it should be `NETSTANDARD2_1_OR_GREATER` instead. It shouldn't happen unless you change the `TargetFrameworks` in the .csproj though? Right now we are only targeting `netstandard2.0`, netstandard2.1` and `net45`, so it shouldn't be a problem.

**Comment by roddone** [comment]
It also happens when you generate the nuget package from source and reference it in a .net 6 project. That's how I spotted the issue.
To find what caused it, I've added the .net6.0 in targetframeworks (for testing only) ;)

**Comment by piksel** [comment]
When running the example you provided above, I don't get any errors and it seems to work fine.
The compiler directives are interpreted when you are building the library, and since the targets does not include `net6.0` you should get the library targeting `netstandard2.1` when using it with a NET 6.0 project.
