### ISSUE TITLE
Unable to set password to ZipOutputStream to a csv file

### ISSUE THREAD

**Issue by Reet-Kaur** [icsharpcode/SharpZipLib#732]
```cs
private IHttpActionResult RunReport(String reportCode)
{
    // Get the report data into a memory stream
    using (var stream = new System.IO.MemoryStream())
    {
        uint pos = 0;
        IChunk chunk = null;

        // Append to the memory stream in chunks
        do
        {
            chunk = report.GetChunk(REPORT_CHUNK_SIZE, pos);  // internal method
            stream.Write(chunk.Bytes, 0, (int)chunk.BytesCopied);
            pos = chunk.EndPos;
        } while (chunk.HasMore);
        

        // Make sure the controller doesn't dispose the session until the report stream is finished
        HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);

        byte[] bytes;
        byte[] fileBytes = stream.ToArray();   //where stream is a System.IO.MemoryStream()
        MemoryStream outStream = new System.IO.MemoryStream();
        using (var zipStream = new ZipOutputStream(outStream))
        {
            zipStream.Password = reportPasswordDetails.sReportPassword;
            //zipStream.SetLevel(9);

            ZipEntry newEntry = new ZipEntry(reportCode + ".csv"); 
            zipStream.PutNextEntry(newEntry);
            

            using (var inStream = new MemoryStream(fileBytes))               
                StreamUtils.Copy(inStream, zipStream, new byte[4096]);

            //clean up
            //inStream.Close();
            //zipStream.CloseEntry();

            //zipStream.IsStreamOwner = false;    // False stops the Close also Closing the underlying stream.
        }
        //outStream.Position = 0;   //This throws exception
        bytes = outStream.ToArray();
    }
    
    response.Content = new ByteArrayContent(bytes);
    response.Content.Headers.ContentType = ResolveContentType(report, isCrystal, isZipContent);

    var contentDispositionHeader = new ContentDisposition
    {
        DispositionType = fields.contentDisposition.ToString(),
        FileName = " Test.Zip"
    };
    response.Content.Headers.Add("Content-Disposition", contentDispositionHeader.ToString());

    return ResponseMessage(response);
}
```

### Expected behavior
The zip generates with a password protected Csv file

### Actual behavior
The zip generates with a CSV, but the file is not password protected

**Comment by Reet-Kaur** [comment]
Looking at the code in ZipOutputStream.PutNextEntry(entry), it first checks
```
if (Password != null)
      {
        entry.IsCrypted = true;
        if (entry.Crc < 0)
        {
          entry.Flags |= 8;
        }
      }

```
and then it later does this 

 ```
if (entry.IsCrypted)
      {
        if (entry.AESKeySize > 0)
        {
          WriteAESHeader(entry);
        }
        else if (entry.Crc < 0)
        {
          WriteEncryptionHeader(entry.DosTime << 16);
        }
        else
        {
          WriteEncryptionHeader(entry.Crc);
        }
      }
```

I am not sure if there's a setting that I am missing here? Could someone please advise on the same?

Thanks!

**Comment by Reet-Kaur** [comment]
![image](https://user-images.githubusercontent.com/40193051/155584198-7efba87e-5141-4716-9f35-7ce271a70258.png)

This is really weird, the generated csv file is marked as Password protected = Yes , but when I open the file it doesn't ask me for a password. It is read-only for sure.
Is this ZipOutputStream.Password functionality even supposed to work like how I am expecting it to work?

**Comment by piksel** [comment]
If you want to use the old ZipCrypto encryption, then this looks correct. If you instead want to use the newer AES encryption, then set the `.AESKeySize` on the entry to `128` or `256`.

I am not sure why it wouldn't ask you for a password... perhaps the password is set to an empty string?

**Comment by Reet-Kaur** [comment]
I have hard-coded the password for my test.  The ZipOutputStream.Password does get set correctly.
Ihaven't set any .AESKeySize  and the ZipEntry looks like this. 

![image](https://user-images.githubusercontent.com/40193051/155857755-a2aae2e8-3f3b-4076-a95e-376788f93041.png)

Does it look like that it's missing a setting? I am clue less.

However, following your suggestion I tried setting .AESKeySize to 128.
![image](https://user-images.githubusercontent.com/40193051/155857926-ff73307c-a59e-4ccd-a7ab-833a3f849ba0.png)

 The Zip folder gets created with a csv file, but I am unable to open the generated csv. I get the following error. 

![image](https://user-images.githubusercontent.com/40193051/155857946-92b2ca2d-58b7-46c2-879b-8f6f040e8bd6.png)

**Comment by piksel** [comment]
I don't think windows have support for AES decryption of zip files.

I made a sample zip file with one entry using AES, and one using ZipCrypto, it looks like this in 7z and prompts for a password for both entries:
![image](https://user-images.githubusercontent.com/807383/156147001-d572e336-a473-4392-873d-486ddad7a42e.png)

I made it from a simplified version of your code:
```cs
using ICSharpCode.SharpZipLib.Zip;
using ICSharpCode.SharpZipLib.Core;

var fileBytes = new byte[] { (byte)'h', (byte)'e', (byte)'l', (byte)'l', (byte)'o' };

var outStream = File.Open("output-dual.zip", FileMode.Create);
using (var zipStream = new ZipOutputStream(outStream))
{
    // Set the password for all subsequent entries
    zipStream.Password = "password";

    // Add zipcrypto file (no `.AESKeySize` set)
    var entryZipCrypto = new ZipEntry("file-zipcrypto.csv"); 
    zipStream.PutNextEntry(entryZipCrypto);
    // Write data
    using (var inStream = new MemoryStream(fileBytes))               
        StreamUtils.Copy(inStream, zipStream, new byte[4096]);

    // Add AES encrypted file (`.AESKeySize` set to 128)
    var entryAes = new ZipEntry("file-aes.csv"); 
    entryAes.AESKeySize = 128;
    zipStream.PutNextEntry(entryAes);
    // Write data
    using (var inStream = new MemoryStream(fileBytes))               
        StreamUtils.Copy(inStream, zipStream, new byte[4096]);
}

```

Opening the `zipcrypto` file works from windows as well, prompting for the password.

**Comment by Reet-Kaur** [comment]
Thanks for your response. 
My old code worked.  I had to do 2 things:

1.  //zipStream.SetLevel(9);   Comment the setLevel
2. entryAes.AESKeySize = 0;  // I don't know why this is necessary though
