### ISSUE TITLE
Problem reading archives containg Zip64 files 

### ISSUE THREAD

**Issue by andrea-parisi** [icsharpcode/SharpZipLib#735]
### Steps to reproduce
1. Create a ZipFile using on iOS with password for example 
[Moduli.zip](https://github.com/icsharpcode/SharpZipLib/files/8331142/Moduli.zip) (Password DEDALUS)
2. Extract the previous file

### Expected behavior
Extract the contained file

### Actual behavior
Throw ZipException "Size invalid for descriptor"

### Version of SharpZipLib
1.3.3 but also verified against master

### Obtained from (only keep the relevant lines)
- Compiled from source
- Package installed using NuGet 1.3.3

I think that the condition _size != -1_ in the method TestLocalHeader is wrong. but must be _size > 0_. In my case the value of size is 0 and also compressedSize value is 0.

**Comment by piksel** [comment]
Hm, yeah, I think you are right. The correct local header value for an entry with a descriptor ought to be `0`, not `-1`. The only mention of `-1` (or rather "all bits set", 0xFFFFFFFF) is for the Zip64 indicator.
https://p1k.se/appnote.md#s439-data-descriptor

The question is, why has this not been a problem for other files? There might be a "de facto" standard of putting `-1` in the field, or it's just that the combination of reading an archive with Zip64 and descriptors using ZipFile is rare enough for this not to have been a problem?
