### ISSUE TITLE
SonarQube vulnerability issue

### ISSUE THREAD

**Issue by busrau** [icsharpcode/SharpZipLib#743]
Lucene.Net has dependencies with SharpZipLib 0.86.0 and sonarqube reports are saying 

Category: CWE-22 | SharpZipLib (or #ziplib) is a Zip, GZip, Tar and BZip2 library. Prior to version 1.3.3, a TAR file entry `../evil.txt` may be extracted in the parent directory of `destFolder`. This leads to arbitrary file write that may lead to code execution. The vulnerability was patched in version 1.3.3.

Do you think is there any way to prevent this error, any path or update?

**Comment by christophwille** [comment]
https://github.com/apache/lucenenet/search?q=SharpZipLibPackageVersion According to this search, SZL is only used for benchmarks.

**Comment by busrau** [comment]
What can I do for avoiding this error on sonar reports?

**Comment by piksel** [comment]
Either ask Lucene.Net to update to a newer version or stop using Lucene.Net, I guess? Or check the sonar docs for a way to ignore. Either way, it's not something we can do.
