### ISSUE TITLE
Setting AESKeySize = 256 on Windows creates a corrupted file.

### ISSUE THREAD

**Issue by mjanulaitis** [icsharpcode/SharpZipLib#747]
### Steps to reproduce
Run the following program.  Open the output zip file test.zip through Windows Explorer. 

`

        static void Main(string[] args)
        {
            string zipFileName = "test.zip";
            string pswd = "test";
            string fileName = "test.log";

            File.WriteAllText(fileName, "Hello World");

            using (var stream = new ZipOutputStream(File.Create(zipFileName)))
            {
                stream.SetLevel(9);

                if (!string.IsNullOrEmpty(pswd))
                    stream.Password = pswd;

                WriteFile(stream, new FileInfo(fileName));
                stream.Finish();
                stream.Close();
            }
        }

        private static void WriteFile(ZipOutputStream stream, FileInfo fi)
        {
            WriteFile(stream, null, fi);
        }
         
        private static void WriteFile(ZipOutputStream stream, string pathInZip, FileInfo fi)
        {
            var fullPathInZip = pathInZip == null ? fi.Name : Path.Combine(pathInZip, fi.Name);
            var entry = new ZipEntry(fullPathInZip);

            if (!string.IsNullOrEmpty(stream.Password))
                entry.AESKeySize = 256;

            stream.PutNextEntry(entry);

            var buffer = new byte[4096];
            using (var fs = File.OpenRead(fi.FullName))
            {
                int sourceBytes;
                do
                {
                    sourceBytes = fs.Read(buffer, 0, buffer.Length);
                    stream.Write(buffer, 0, sourceBytes);
                } while (sourceBytes > 0);
            }
        }

`

### Expected behavior
The file should open.

### Actual behavior
The following error is thrown:

Windows cannot complete the extraction.

The destination file could not be created.

### Version of SharpZipLib
1.3.3

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by mjanulaitis** [comment]
After downloading the source code and running the ZipOutputStreamEncryptEmptyEntries I quickly learned the encryption requires 7-Zip which just happened to have on my machine.  I am able to open the file with 7-Zip.

**Comment by piksel** [comment]
Well, Explorer doesn't support AES encryption. But  all other major archivers do (including 7zip).

**Comment by mjanulaitis** [comment]
@piksel Thanks.  Yes I didn't realize that the same file format, or at least extension, wasn't processable by Windows.  I see it working in 7-Zip as well as WinRar.  It's ashamed that Windows can't at least thrown an Encryption not supported error.  I'm pretty sure it would be really easy for them to update the OS.

**Comment by piksel** [comment]
It's complicated. From what I have gathered, it's because of how the zip implementation was licensed by Microsoft from a third party. But I have no official source for this.

**Comment by mjanulaitis** [comment]
@piksel, I see thanks for the clarification.

**Comment by piotrsrodka** [comment]
But! If I just specify: `zipStream.Password = "myPassword";` it works under Windows, but I dont know what size of AES key is used then? File behave normal and requires password.

**Comment by piksel** [comment]
@piotrsrodka Then it uses "ZipCrypto", which is not based on AES and considered weak.
