### ISSUE TITLE
can not use ZipFile.add in android (unity3d)

### ISSUE THREAD

**Issue by iamnewaplayer** [icsharpcode/SharpZipLib#748]
ZipFile.add  will make a lot of tmp file to 'data/local' path
so do not work in android  
how can i use it?

zipFile.Add($"{VersionDownloadPath(textureSurface.md5)}", index);
zipFile.CommitUpdate();

**Comment by piksel** [comment]
What is  the error you are getting? Why wouldn't temporary files work on android?
