### ISSUE TITLE
some folder in UPM should be set end with ~ otherwise get error missing .meta

### ISSUE THREAD

**Issue by xinatcg** [icsharpcode/SharpZipLib#749]
### Steps to reproduce
1. upm import the package
 

### Expected behavior
No error

### Actual behavior
Asset Packages/org.icsharpcode.sharpziplib/appveyor.yml.old has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/org.icsharpcode.sharpziplib/CONTRIBUTING.md has no meta file, but it's in an immutable folder. The asset will be ignored.

arround 383 errors

### Version of SharpZipLib
1.3.3
### Obtained from (only keep the relevant lines)
- Compiled from source, commit: _______
- Downloaded from GitHub
- Package installed using NuGet

**Comment by xinatcg** [comment]
yes, i am using the openupm, also get same error.

**Comment by xinatcg** [comment]
i test both manually install by openupm and  openupm cli install, get same error after package download:

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/55399567/165701244-cfb6a612-7600-4f4e-b359-aac4e281c199.png">

**Comment by piksel** [comment]
Yeah, not sure how I missed this when testing the package. I pushed a repackage v1.3.3 tagged `v1.3.3-repkg.1`, and upcoming releases should include this fix as well.
