### ISSUE TITLE
Retier sourceforge Links, packages and anything else.

### ISSUE THREAD

**Issue by Minx-SigEp** [icsharpcode/SharpZipLib#75]
Sourceforge is no longer the once reliable and upstanding code repository it once use to be. A quick google search will bring up tons of horror stories and articles about the fall of this once credible service. 

https://www.google.com/search?q=stackoverflow+malware&ie=utf-8&oe=utf-8#q=sourceforge+malware

**Comment by McNeight** [comment]
@christophwille 

What would it take to completely remove any official distributions from SF?

**Comment by christophwille** [comment]
Correct me if I am wrong, but do we need a download distribution at all when we do NuGet?

**Comment by McNeight** [comment]
I'd prefer to have the option, especially since I don't think we have a NuGet package for SharpZipLib. I don't recognize any of the names out of [this list](https://www.nuget.org/packages?q=sharpziplib).

**Comment by christophwille** [comment]
We never published on NuGet that is true. (suggested package name ICSharpCode.SharpZipLib, or ask bigsan to allow us to take his package over - which I think might be the best option)

**Comment by christophwille** [comment]
I used the NuGet contact owner form to get in touch with bigsan

**Comment by McNeight** [comment]
@christophwille 
I've attached the binaries available at SourceForge to the [releases here at GitHub](https://github.com/icsharpcode/SharpZipLib/releases). Between using that for the 1.0 release and the upcoming NuGet package, I don't believe there is a reason to continue using SourceForge.

-Neil

**Comment by christophwille** [comment]
Links have been retargetted.
