### ISSUE TITLE
.Net Remoting Sink zip error

### ISSUE THREAD

**Issue by zimuyanghua** [icsharpcode/SharpZipLib#756]
Borrowing code when using Demoting channel compression, there is no problem with using it at first, but occasionally encounter the following exception, the error shows that the array is out of bounds when the compression is written, but is this an internal problem of NZlib? How do I need to fix it. The actual test environment cannot be reproduced at all, and this phenomenon can only occur in the production environment. If it can be solved by upgrading, what is the reason for this?

[https://www.cnblogs.com/openkava/archive/2007/08/10/850203.html](url)

![超出数组提示](https://user-images.githubusercontent.com/46125819/173043095-1e4d2de1-6ccc-42d8-928a-91074476eb60.jpg)

**Comment by piksel** [comment]
Since the library (and namespace) was renamed to SharpZipLib in version 0.3, you must be using a  **really** outdated version. I have no idea what the code base was like then (10+ years ago?).

**Comment by zimuyanghua** [comment]
> Since the library (and namespace) was renamed to SharpZipLib in version 0.3, you must be using a **really** outdated version. I have no idea what the code base was like then (10+ years ago?).

Thanks！I guess the only way to solve this problem is to use the new version.

**Comment by piksel** [comment]
Yeah. Sorry I can't be of any more help.
