### ISSUE TITLE
Stream returned by ZipFile.GetInputStream() hangs when accessing Length property

### ISSUE THREAD

**Issue by Sardelka9515** [icsharpcode/SharpZipLib#767]
### Steps to reproduce
1. Create a new ZipFile instance
2. Get a `Stream` object returned by ZipFile.GetInputStream(), and try to get it's length.
3. Program stuck

### Expected behavior
Return the acutal length of the decompressed file. Or throw an expection if it's not possibile.

### Actual behavior
When accesing  `Stream.Length` propperty from the object returned by  ZipFile.GetInputStream(), execution hangs.

### Obtained from (only keep the relevant lines)
- Package installed using NuGet
1.3.3

**Comment by piksel** [comment]
It should throw, not sure what is happening in your case:

https://github.com/icsharpcode/SharpZipLib/blob/519ed7367daf0a5ad7f2d36bee6e994ffcd7e9e8/src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/InflaterInputStream.cs#L534-L544

**Comment by Sardelka9515** [comment]
Ah, my bad. Exception not caught correctly, nevermind
