### ISSUE TITLE
ZIP file cannot be open in a mobile device

### ISSUE THREAD

**Issue by cntmnl** [icsharpcode/SharpZipLib#77]
Hello,
I am following your documentation and compressing a folder with multiple files in a zip. The ZIP file can be opened without any problem in any kind of DESKTOP, but it cannot in any kind of device mobile: Iphone, Windows Phone or Android. The error is always the same "Archive is unsupported or corrupted" and troubleshooting is not very much possible. 

Any idea? 

Thanks,

Manuel

**Comment by Numpsy** [comment]
This one seems rather light on context as well as being rather old?

**Comment by piksel** [comment]
Yeah. Closing.
