### ISSUE TITLE
FastZip.CreateZip(Stream, ...) closes provided stream

### ISSUE THREAD

**Issue by gtbuchanan** [icsharpcode/SharpZipLib#78]
`FastZip.CreateZip(Stream, string, bool, string, string)` uses a `ZipOutputStream` wrapper around the provided output stream without setting `IsStreamOwner = false`. This closes the external output stream.

https://github.com/icsharpcode/SharpZipLib/blob/master/src/Zip/FastZip.cs#L369

```
using ( outputStream_ = new ZipOutputStream(outputStream) ) {
    ...
}
```

**Comment by siddhsuper** [comment]
Hi, I am still seeing this issue . The objectdisposed exception is coming when I use fastZip.CreateZip(outputstream. and when I try to use outptustream after that.Pls let me know if there is any fix for this

**Comment by Numpsy** [comment]
does #455 count as a fix for this one?

**Comment by piksel** [comment]
Yeah, I'd say so.
