### ISSUE TITLE
TarInputStream does not run synchronously when used non-async

### ISSUE THREAD

**Issue by piksel** [icsharpcode/SharpZipLib#788]
This is a follow up from #786.

`TarInputStream.GetNextEntry()` seems to use the thread pool to run "asynchronously", even though it should be fully sync.
The async implementation takes an `isAsync` argument that should make it run totally synchronous when passed with `false`.

As of #787, deadlocks are avoided using `.ConfigureAwait(false)`, but there is still a bug somewhere that caused this to happen in the first place.

**Comment by flensrocker** [comment]
https://sharplab.io/ is a good place to see the generated Async-StateMachine. It's just a bit of work to get all the relevant classes into one file to get an overview.

**Comment by flensrocker** [comment]
I copied all relevant classes used by `TarInputStream` into one file and added the output from sharplab.io.

If someone wants to take a look... I don't know, when I have the time for it.

[TarInputStream-SharpLabIo.zip](https://github.com/icsharpcode/SharpZipLib/files/9828507/TarInputStream-SharpLabIo.zip)

**Comment by piksel** [comment]
Just for reference, this is how a "async with isAsync" method **should** work:
https://sharplab.io/#v2:CYLg1APgAgDABFAjAVgNwFgBQWoGYEBMcAwnAN5ZxUL5QAcCAbADwCWAdgC4B8cAsgAoARgHsRAGzisAzgEFpAT3YBjAJTlK1LawBmcATPlK1GzFvPUoATiYA6ACIBTcQEMFAxDBiqMZi3ABfTQsoAHY4NGDArACgA==

As you can see in the output, the goto just skips the entire state-machine logic and, most importantly, does not call `AwaitUnsafeOnCompleted`.
