### ISSUE TITLE
ZipOutputStream calls sync DeflaterOutputStream.Finish from async

### ISSUE THREAD

**Issue by Christianschrodahl** [icsharpcode/SharpZipLib#801]
### Steps to reproduce
1.  Create http get request.
2.  set AllowSynchronousIO to false
3. Start zip json data and pdf docs
4. Only use async methods to run the code. 

### Expected behavior
Return a zipped file

### Actual behavior
You can se it crash on PutNextEntryAsync and/or finnishAsync.
Looks like PutNextEntryAsync  calls Finish() and not FinnishAsync()

### Exception:
Exception has occurred: CLR/System.InvalidOperationException
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll: 'Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.'

![image](https://user-images.githubusercontent.com/26057919/201852133-09cf2fc7-85b3-46dd-9308-9aa3c04eec19.png)

### Version of SharpZipLib
1.4.1
### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment]
Yeah, this is caused by the following line:
https://github.com/icsharpcode/SharpZipLib/blob/cdd0931e3c476faaf829963b2567619431c871bb/src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs#L608

It shouldn't be called inside `WriteEntryFooter`, but rather in the CloseEntry(Async) methods.
