### ISSUE TITLE
.NET 4.8 Framework Support?

### ISSUE THREAD

**Issue by devmaestro1** [icsharpcode/SharpZipLib#804]
Hello,

I noticed that as of v1.4.0 support for .NET 4.5 Framework has been dropped in favor of .NET 6. I'm not sure why SharpZipLib wouldn't also support .NET 4.8 Framework since it is LTS and shouldn't require any code changes? Are future SharpZipLib releases no longer going to guarantee being able to compile under the .NET 4.8 framework? 

Thanks.

**Comment by piksel** [comment]
.NET 4.8 support has not been dropped. It's supported via the .NET Standard target, and will likely continue to be supported as long as it's seeing large usage and/or until it's EOL.

**Comment by devmaestro1** [comment]
Thank you for the clarification!
