### ISSUE TITLE
Release notes missing for 1.4.2

### ISSUE THREAD

**Issue by davisnw** [icsharpcode/SharpZipLib#826]
### Describe the bug

https://www.nuget.org/packages/SharpZipLib/1.4.2#release-body-tab says to see https://github.com/icsharpcode/SharpZipLib/wiki/Release-1.4.2 for release notes.

However https://github.com/icsharpcode/SharpZipLib/wiki/Release-1.4.2 does not exist.

The last public commit to https://github.com/icsharpcode/SharpZipLib.wiki.git was on November 5, 2022

### Steps to reproduce

1. Go to https://www.nuget.org/packages/SharpZipLib/1.4.2#release-body-tab
2. Click the link for the release notes (https://github.com/icsharpcode/SharpZipLib/wiki/Release-1.4.2)
3. There are no release notes for 1.4.2

### Expected behavior

Release notes page exists.

### Tags

Documentation

**Comment by piksel** [comment]
The release notes are written on the releases page, but I forgot to copy it to the wiki. Thanks!

**Comment by piksel** [comment]
Fixed!
