### ISSUE TITLE
incorrect fsf address

### ISSUE THREAD

**Issue by rapgro** [icsharpcode/SharpZipLib#89]
The Free Software Foundation address in the doc/COPYING.txt file seems to be outdated or
misspelled.
Current license text can be found here:
http://www.gnu.org/licenses/old-licenses/gpl-2.0.html

**Comment by rapgro** [comment]
Files with incorrect fsf address, found with licensecheck scrpt:

SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/AssemblyInfo.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/BZip2/BZip2.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/BZip2/BZip2Constants.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/BZip2/BZip2Exception.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/BZip2/BZip2InputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/BZip2/BZip2OutputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Checksums/Adler32.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Checksums/Crc32.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Checksums/IChecksum.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Checksums/StrangeCrc.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Core/FileSystemScanner.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Core/INameTransform.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Core/IScanFilter.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Core/NameFilter.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Core/PathFilter.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Core/StreamUtils.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Core/WindowsPathUtils.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Encryption/PkzipClassic.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Encryption/ZipAESStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Encryption/ZipAESTransform.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/GZip/GZipConstants.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/GZip/GZipException.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/GZip/GzipInputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/GZip/GzipOutputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Lzw/LzwConstants.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Lzw/LzwException.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Lzw/LzwInputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Main.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/SharpZipBaseException.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Tar/InvalidHeaderException.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Tar/TarArchive.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Tar/TarBuffer.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Tar/TarEntry.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Tar/TarException.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Tar/TarHeader.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Tar/TarInputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Tar/TarOutputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/Deflater.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/DeflaterConstants.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/DeflaterEngine.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/DeflaterHuffman.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/DeflaterPending.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/Inflater.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/InflaterDynHeader.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/InflaterHuffmanTree.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/PendingBuffer.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/Streams/DeflaterOutputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/Streams/InflaterInputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/Streams/OutputWindow.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/Compression/Streams/StreamManipulator.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/FastZip.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/IEntryFactory.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/WindowsNameTransform.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipConstants.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipEntry.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipEntryFactory.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipException.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipExtraData.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipFile.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipHelperStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipInputStream.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipNameTransform.cs
SharpZipLib-e01215507cf25a5978a0bd850c9e67dbabf515b7/src/Zip/ZipOutputStream.cs

**Comment by McNeight** [comment]
Closed by pull request #101 

-Neil
