### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [icsharpcode/SharpZipLib#91]
I cannot find a clear explanation why the project is licensed GPL + exception and not either GPL or LGPL (or something else).

What's the problem with using a standard license?

**Comment by rapgro** [comment]
sharpziplib-doc.noarch: E: incorrect-fsf-address
/usr/share/doc/sharpziplib-doc/COPYING.txt
sharpziplib-doc.noarch: E: incorrect-fsf-address
/usr/share/licenses/sharpziplib-doc/COPYING.txt

Please use a current license text.
https://gnu.org/licenses/gpl.html

**Comment by McNeight** [comment]
The nice thing about standards is that there are so many to choose from, and that includes the GPL.

http://www.gnu.org/software/classpath/license.html

-Neil

**Comment by jfreilly** [comment]
The not nice thing about open source is that it can be very hard to change licenses.  A whole lot of people have signed  the existing license.  What happens when you can't easily get in contact with all those people any more?   Easy thing is to leave the license alone.

**Comment by rapgro** [comment]
What? My point is about wrong / old license text, there's a new address of FSF.
